force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture and display the application log for custom development and custom batch processing.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>APPLOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <label>Application Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <label>Debug Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is used to store the actual detail of the job run or error message.</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Integration_Payload__c.field-meta.xml
<CustomField>
    <fullName>Integration_Payload__c</fullName>
    <description>For Integration related to store the integration payload</description>
    <label>Integration Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>This is used to store the Class Name or Job that trigger the logging</description>
    <label>Module</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <description>Id of the record being processed</description>
    <label>Reference Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <description>This is used to store the Function within the class that trigger the exception</description>
    <label>Source Function</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Raw Exception Stack Trace for Unhandled Error</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error Log</fullName>
            </value>
            <value>
                <fullName>Integration Log</fullName>
            </value>
            <value>
                <fullName>Job Log</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicationLogWrapper.cls
/*******************************************************************
Description: This class is used to wrap the creation of Application Log record
*******************************************************************/
global without sharing class ApplicationLogWrapper {
    global Application_Log__c applicationLog;
    
    // constructor
    global ApplicationLogWrapper() {
        applicationLog = new Application_Log__c();
    }
    
    global String logLevel {
        get {
            return applicationLog.Debug_Level__c;
        }
        
        set {
            logLevel = value;
            applicationLog.Debug_Level__c = logLevel;
        }
    } // end logLevel
    
    global String sourceClass {
        get {
            return applicationLog.Module__c;
        }
        
        set {
            sourceClass = value;
            applicationLog.Module__c = sourceClass;
        }
    } // end sourceClass
    
    global String sourceFunction {
        get {
            return applicationLog.Source_Function__c;
        }
        
        set {
            sourceFunction = value;
            applicationLog.Source_Function__c = sourceFunction;
        }
    } // end sourceFunction
    
    global String referenceId {
        get {
            return applicationLog.Reference_Id__c;
        }
        
        set {
            referenceId = value;
            applicationLog.Reference_Id__c = referenceId;
        }
    } // end referenceId
    
    global String referenceInfo {
        get {
            return applicationLog.Reference_Info__c;
        }
        
        set {
            referenceInfo = value;
            applicationLog.Reference_Info__c = referenceInfo;
        }
    } // end referenceInfo
    
    global String logMessage {
        get {
            return applicationLog.Description__c;
        }
        
        set {
            logMessage = value;
            applicationLog.Description__c = logMessage;
        }
    } // end logMessage
    
    global String payLoad {
        get {
            return applicationLog.Integration_Payload__c;
        }
        
        set {
            payLoad = value;
            applicationLog.Integration_Payload__c = payLoad;
        }
    } // end payLoad
    
    global String applicationName {
        get {
            return applicationLog.Application_Name__c;
        }
        
        set {
            applicationName = value;
            applicationLog.Application_Name__c = applicationName;
        }
    } // end applicationName
    
    global Exception exceptionThrown {
        get;
        
        set {
            exceptionThrown = value;
            if (exceptionThrown != null) {
                applicationLog.Stack_Trace__c = 'Root Cause: '+exceptionThrown.getMessage()+'\r\n';
                applicationLog.Stack_Trace__c = applicationLog.Stack_Trace__c + exceptionThrown.getStackTraceString();
            } // end if    
        }
    } // end exception
    
    global DateTime startDate {
        get {
            return applicationLog.Start_Date__c;
        }
        
        set {
            startDate = value;
            applicationLog.Start_Date__c = startDate;
        }
    } // end startDate
    
    global DateTime endDate {
        get {
            return applicationLog.End_Date__c;
        }
        
        set {
            endDate = value;
            applicationLog.End_Date__c = endDate;
        }
    } // end endDate
    
    global String type {
        get {
            return applicationLog.Type__c;
        }
        
        set {
            type = value;
            applicationLog.Type__c = type;
        }
    } // end type
    
    global boolean isDebug {
        get;
        set;
    }
    
    global boolean isInfo {
        get;
        set;
    }
    
    global boolean isWarning {
        get;
        set;
    }
    
    global boolean isError {
        get;
        set;
    }
} // end ApplicationLogWrapper