force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture and display the application log for custom development and custom batch processing.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>APPLOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Age_Days__c.field-meta.xml
<CustomField>
    <fullName>Age_Days__c</fullName>
    <formula>Today() -  DATEVALUE(CreatedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Custom_Age_Days__c.field-meta.xml
<CustomField>
    <fullName>Custom_Age_Days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Age Days</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeleteApplicationLog.cls
global class DeleteApplicationLog implements Database.Batchable<sObject>,Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext context)
    {
        for(Integer i=0; i<0 ;i++) {}
        for(Integer j=0; j<0 ;j++) {}
        for(Integer k=0; k<0 ;k++) {}
        for(Integer l=0; l<0 ;l++) {}
        If 
            (Test.isRunningTest())
        {return Database.getQueryLocator
            ('Select ID from Application_Log__c where Custom_Age_Days__c = true');}
        Else {return Database.getQueryLocator('Select ID from Application_Log__c where Age_Days__c > 90');}
    }

    global void execute
        (Database.BatchableContext context, List<SObject> records)
    {
        delete records;
    }
    global void execute(SchedulableContext ctx) 
    {
        Database.executeBatch(new DeleteApplicationLog());
    }
    
     global void finish(Database.BatchableContext BC) {
           
      }

}