force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture and display the application log for custom development and custom batch processing.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>APPLOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <label>Application Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <label>Debug Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is used to store the actual detail of the job run or error message.</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>This is used to store the Class Name or Job that trigger the logging</description>
    <label>Module</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <description>This is used to store the Function within the class that trigger the exception</description>
    <label>Source Function</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error Log</fullName>
            </value>
            <value>
                <fullName>Integration Log</fullName>
            </value>
            <value>
                <fullName>Job Log</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Additional_Filter__c.field-meta.xml
<CustomField>
    <fullName>Additional_Filter__c</fullName>
    <label>Additional Filter</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <label>Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Date_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Date_Field_API_Name__c</fullName>
    <label>Date Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Is_Permanent_Delete__c.field-meta.xml
<CustomField>
    <fullName>Is_Permanent_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Permanent Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/SObject_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Api_Name__c</fullName>
    <label>SObject Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_GlobalPurgeData_Test.cls
/*******************************************************************
Description: This is the test class for Batch_globalPurgeData class.
*******************************************************************/
@isTest
public class Batch_GlobalPurgeData_Test {
    private static String mooduleName='Batch_GlobalPurgeData';
    
    /** when application log record exist to be deleted.**/
    static testMethod void testAppLogPurgeWhenAppLogExist() {
        
        //create Application log test data
        Map < String, Object > appLogFieldValueMap = new Map < String, Object > ();
        appLogFieldValueMap.put('Start_Date__c', (DateTime.now() - 20));
        appLogFieldValueMap.put('End_Date__c', (DateTime.now() - 20));
        appLogFieldValueMap.put('Module__c', 'Test Class');
        appLogFieldValueMap.put('Source_Function__c', 'Test Function');
        appLogFieldValueMap.put('Description__c', 'test');
        appLogFieldValueMap.put('Debug_Level__c', 'Info');
        appLogFieldValueMap.put('Type__c', 'Job Log');
        appLogFieldValueMap.put('Application_Name__c', 'TestAppName');
        
        TestUtility.createApplicationLogs(appLogFieldValueMap, 10);
        
        List < String > appLogQueryFieldsList = new List < String > {
            'Start_Date__c',
                'End_Date__c',
                'Module__c',
                'Source_Function__c',
                'Description__c',
                'Debug_Level__c',
                'Type__c',
                'Application_Name__c'
                };
                    
        // make sure log created.
        List<Application_Log__c> appLogCreatedList =  (List<Application_Log__c>) TestUtility.getApplicationLogs(appLogQueryFieldsList);
        System.assertEquals(10, appLogCreatedList.size());
        
        // build query
        DateTime StartTime = DateTime.now();
        List < System_Settings__mdt > sysSettingMD = [Select Id, MasterLabel, Label, Date_Field_API_Name__c, Additional_Filter__c,
                                                      Batch_Size__c, SObject_Api_Name__c, Debug__c, Info__c, Warning__c, Error__c, Is_Permanent_Delete__c
                                                      From System_Settings__mdt Where MasterLabel = : 'Application Log Purge Batch'
                                                      limit 1
                                                     ];
        
        DateTime closeDateCriteria = StartTime + 1; // Add 1 day
        String closeDateCriteriaStr = closeDateCriteria.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');

        String dateTime_field = sysSettingMD[0].Date_Field_API_Name__c;
        String sobj_api_name = sysSettingMD[0].SObject_Api_Name__c;
        String query = 'Select Id From ' + sobj_api_name + ' Where ' + dateTime_field + ' <= ' + closeDateCriteriaStr;
        
        // calling batch
        Test.startTest();
        Database.executeBatch(new Batch_GlobalPurgeData(query,sysSettingMD[0]), 10);
        Test.stopTest();
        
        // make sure record deleted   
        List < Application_Log__c >    appLogList = [Select Id, IsDeleted from Application_Log__c where IsDeleted=true ALL ROWS];
        System.assertEquals(10, appLogList.size());
        System.assertEquals(true, appLogList[0].IsDeleted);
    }
    
    /** When there is no app log to be deleted **/
    static testMethod void testAppLogPurgeWhenNoAppLogs() {
        
        // make sure log there is no created APP logs.
        List<Application_Log__c> appLogCreatedList =  (List<Application_Log__c>) TestUtility.getApplicationLogs();
        System.assertEquals(0, appLogCreatedList.size());
        
        // build query
        DateTime StartTime = DateTime.now();
        List < System_Settings__mdt > sysSettingMD = [Select Id, MasterLabel, Label, Date_Field_API_Name__c, Additional_Filter__c,
                                                      Batch_Size__c, SObject_Api_Name__c, Debug__c, Info__c, Warning__c, Error__c, Is_Permanent_Delete__c
                                                      From System_Settings__mdt Where MasterLabel = : 'Application Log Purge Batch'
                                                      limit 1
                                                     ];
        DateTime closeDateCriteria = StartTime;
        String closeDateCriteriaStr = closeDateCriteria.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        String dateTime_field = sysSettingMD[0].Date_Field_API_Name__c;
        String sobj_api_name = sysSettingMD[0].SObject_Api_Name__c;
        String query = 'Select Id From ' + sobj_api_name + ' Where ' + dateTime_field + ' <= ' + closeDateCriteriaStr;
        
        // calling batch
        Test.startTest();
        Database.executeBatch(new Batch_GlobalPurgeData(query, sysSettingMD[0]), 10);
        Test.stopTest();
        
        // make sure record deleted   
        List < Application_Log__c >    appLogList = [Select Id, IsDeleted from Application_Log__c where IsDeleted=true ALL ROWS];
        System.assertEquals(0, appLogList.size());
    }
}