force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object will be used to capture and display the application log for custom development and custom batch processing.</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>APPLOG-{0000000000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <label>Application Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Custom_Age_Days__c.field-meta.xml
<CustomField>
    <fullName>Custom_Age_Days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Age Days</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <label>Debug Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>This is used to store the Class Name or Job that trigger the logging</description>
    <label>Module</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <description>This is used to store the Function within the class that trigger the exception</description>
    <label>Source Function</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error Log</fullName>
            </value>
            <value>
                <fullName>Integration Log</fullName>
            </value>
            <value>
                <fullName>Job Log</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteApplicationLogTest.cls
@isTest
private class DeleteApplicationLogTest {

    @isTest static void testDeleteApplicationLog() {
        // Create test records
        List<Application_Log__c> testRecords = new List<Application_Log__c>();
        for(Integer i=0; i<100; i++) {
           testRecords.add(new Application_Log__c(
               Application_Name__c = 'ABC',
               Start_Date__c=Date.today(),
               Debug_Level__c= 'Error', 
               Module__c='123', 
               Source_Function__c='123', 
               Type__c='Error Log',
               Custom_Age_Days__c = true));
        }
        insert testRecords;

        // Call the batch class
        Test.startTest();
        Database.executeBatch(new DeleteApplicationLog(),200);
        Test.stopTest();
        
        // Verify that the records were deleted
        Integer recordCount = [SELECT COUNT() FROM Application_Log__c WHERE Custom_Age_Days__c=true];
        System.assertEquals(0, recordCount);
    }
}