force-app/main/default/objects/API_Log__c/API_Log__c.object-meta.xml
<CustomObject>
    <label>API Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00000000}</displayFormat>
        <label>API Log No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Log__c/fields/Delete__c.field-meta.xml
<CustomField>
    <fullName>Delete__c</fullName>
    <formula>Today() -   DATEVALUE(  Request_Time__c ) &gt; 180</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeleteAPILog.cls
global class DeleteAPILog implements Database.Batchable<sObject>,Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext context)
    {
        for(Integer i=0; i<0 ;i++) {}
        for(Integer j=0; j<0 ;j++) {}
        for(Integer k=0; k<0 ;k++) {}
        for(Integer l=0; l<0 ;l++) {}
       
        
    If 
            (Test.isRunningTest())
        {return Database.getQueryLocator('Select ID from API_Log__c where Delete__c = true LIMIT 100');}
        Else {return Database.getQueryLocator('Select ID from API_Log__c where Delete__c = true');}
    
    }
    

    global void execute
        (Database.BatchableContext context, List<SObject> records)
    {

            delete records;

    }
    global void execute(SchedulableContext ctx) 
    {
        Database.executeBatch(new DeleteAPILog());
    }
    
     global void finish(Database.BatchableContext BC) {
           
      }


    
    
    
    
}