force-app/main/default/objects/Name_List__c/Name_List__c.object-meta.xml
<CustomObject>
    <label>Name List</label>
    <nameField>
        <displayFormat>NL{YYYY}{MM}{0000000000}</displayFormat>
        <label>Name List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Name_List__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_340, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_340)) &amp;  Seat_Allocation_and_Ticketing__r.Case_ID__c,  Seat_Allocation_and_Ticketing__r.Case_ID__r.CaseNumber, &quot;_self&quot; )</formula>
    <label>Case ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>Given Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
                <isActive>false</isActive>
                <label>Female</label>
            </value>
            <value>
                <fullName>Male</fullName>
                <isActive>false</isActive>
                <label>Male</label>
            </value>
            <value>
                <fullName>Undisclosed Gender</fullName>
                <isActive>false</isActive>
                <label>Undisclosed Gender</label>
            </value>
            <value>
                <fullName>Unspecified Gender</fullName>
                <isActive>false</isActive>
                <label>Unspecified Gender</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>INF_Date_of_Birth__c</fullName>
    <label>INF_Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_First_Name__c.field-meta.xml
<CustomField>
    <fullName>INF_First_Name__c</fullName>
    <label>INF_First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>INF_Last_Name__c</fullName>
    <label>INF_Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Meal_Selection_All_Sector__c.field-meta.xml
<CustomField>
    <fullName>INF_Meal_Selection_All_Sector__c</fullName>
    <label>INF_Meal Selection(All Sector)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BBML</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Meal_Selection_Departing_Only__c.field-meta.xml
<CustomField>
    <fullName>INF_Meal_Selection_Departing_Only__c</fullName>
    <label>INF_Meal Selection(Departing Only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BBML</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Meal_Selection_Returning_Only__c.field-meta.xml
<CustomField>
    <fullName>INF_Meal_Selection_Returning_Only__c</fullName>
    <label>INF_Meal Selection(Returning Only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BBML</fullName>
            </value>
            <value>
                <fullName>BBML,BBML</fullName>
                <isActive>false</isActive>
                <label>BBML,BBML</label>
            </value>
            <value>
                <fullName>N</fullName>
                <isActive>false</isActive>
                <label>N</label>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
            <value>
                <fullName>bbml
=bbml</fullName>
                <isActive>false</isActive>
                <label>bbml
=bbml</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Passenger_Type__c.field-meta.xml
<CustomField>
    <fullName>INF_Passenger_Type__c</fullName>
    <label>INF_Passenger Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Passenger_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>infant</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Title__c.field-meta.xml
<CustomField>
    <fullName>INF_Title__c</fullName>
    <label>INF_Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MSTR</fullName>
            </value>
            <value>
                <fullName>MISS</fullName>
            </value>
            <value>
                <fullName>Mister</fullName>
                <isActive>false</isActive>
                <label>Mister</label>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Surname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Meal_Selection_All_Sector__c.field-meta.xml
<CustomField>
    <fullName>Meal_Selection_All_Sector__c</fullName>
    <label>Meal Selection(All Sector)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meal_Selection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Meal_Selection_Departing_Only__c.field-meta.xml
<CustomField>
    <fullName>Meal_Selection_Departing_Only__c</fullName>
    <label>Meal Selection(Departing Only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meal_Selection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Meal_Selection_Returning_Only__c.field-meta.xml
<CustomField>
    <fullName>Meal_Selection_Returning_Only__c</fullName>
    <label>Meal Selection(Returning Only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meal_Selection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Passenger_Type__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Type__c</fullName>
    <label>Passenger Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>adult</fullName>
            </value>
            <value>
                <fullName>child</fullName>
            </value>
            <value>
                <fullName>false</fullName>
                <isActive>false</isActive>
                <label>false</label>
            </value>
            <value>
                <fullName>null</fullName>
                <isActive>false</isActive>
                <label>null</label>
            </value>
            <value>
                <fullName>r</fullName>
                <isActive>false</isActive>
                <label>r</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Seat_Allocation_and_Ticketing__c.field-meta.xml
<CustomField>
    <fullName>Seat_Allocation_and_Ticketing__c</fullName>
    <label>Seat Allocation and Ticketing</label>
    <referenceTo>Seat_Allocation_and_Ticketing__c</referenceTo>
    <relationshipLabel>Name Lists</relationshipLabel>
    <relationshipName>Name_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Special_Service_Departing__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Departing__c</fullName>
    <label>Special Service(Departing)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Special_Service</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Special_Service_Returning__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Returning__c</fullName>
    <label>Special Service(Returning)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Special_Service</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MR</fullName>
            </value>
            <value>
                <fullName>MRS</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSTR</fullName>
            </value>
            <value>
                <fullName>MISS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Add_Name_List_Status__c.field-meta.xml
<CustomField>
    <fullName>Add_Name_List_Status__c</fullName>
    <label>Add Name List Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Allocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Type__c</fullName>
    <label>Allocation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SRS</fullName>
            </value>
            <value>
                <fullName>ADC</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Booking_Reference_PNR__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference_PNR__c</fullName>
    <description>Temp PNR by B2B</description>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Seat Allocations and Ticketings</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Departing_PNR_Status__c.field-meta.xml
<CustomField>
    <fullName>Departing_PNR_Status__c</fullName>
    <label>Departing PNR Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Allocated_Seats__c</fullName>
    <label>Final Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Returning_PNR_Status__c.field-meta.xml
<CustomField>
    <fullName>Returning_PNR_Status__c</fullName>
    <label>Returning PNR Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Sync_SAT_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_SAT_Status__c</fullName>
    <label>Sync SAT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/tour_Guide_email__c.field-meta.xml
<CustomField>
    <fullName>tour_Guide_email__c</fullName>
    <label>tour Guide email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/tour_Guide_phone__c.field-meta.xml
<CustomField>
    <fullName>tour_Guide_phone__c</fullName>
    <label>tour Guide phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/recordTypes/Planned_Allocation.recordType-meta.xml
<RecordType>
    <fullName>Planned_Allocation</fullName>
    <active>true</active>
    <description>For STARLUX to create Seat Allocation for Travel Agency</description>
    <label>Planned Allocation</label>
</RecordType>

force-app/main/default/classes/PaxUtil.cls
public class PaxUtil {
    public static List<String> addPax(List<Case> caseList) {
        System.debug('[4i] Add pax starting');
        Id plannedAllocationRecordTypeId = [SELECT Id FROM RecordType 
                                            WHERE DeveloperName = 'Planned_Allocation' and SObjectType = 'Seat_Allocation_and_Ticketing__c'].Id;
        Set<String> ConIdSet=new Set<String>();				//2022/11/18 Edit by Jetwell set query Contact Condition
        Set<String> CaseIdSet=new Set<String>();
        for(Case C:caseList)
        {
            ConIdSet.add(C.ContactId);
            CaseIdSet.add(C.Id);
        }
        List<Seat_Allocation_and_Ticketing__c> satList = [SELECT Id, Case_ID__c, Name, Booking_Reference_PNR__c, Departing_Flight_Number__c,
                                                          Returning_Flight_Number__c, Departing_PNR_Status__c, Returning_PNR_Status__c,
                                                          Tour_Guide_Email__c,Tour_Guide_Phone__c
                                                          FROM Seat_Allocation_and_Ticketing__c 
                                                          WHERE (Allocation_Type__c = :Constants.PICKLIST_SAT_ALLOCATION_TYPE_SRS 
                                                                 OR Allocation_Type__c = :Constants.PICKLIST_SAT_ALLOCATION_TYPE_ADC) 
                                                          AND Final_Allocated_Seats__c > 0 
                                                          AND Sync_SAT_Status__c = :Constants.PICKLIST_STATUS_SUCCEEDED 
                                                          AND Add_Name_List_Status__c != :Constants.PICKLIST_STATUS_SUCCEEDED 
                                                          AND recordTypeId = :plannedAllocationRecordTypeId 
                                                          AND Case_ID__c IN :CaseIdSet];
        Map<String, List<Seat_Allocation_and_Ticketing__c>> caseIdSatListMap = new Map<String, List<Seat_Allocation_and_Ticketing__c>>();
        for (Seat_Allocation_and_Ticketing__c currSat : satList) {
            if (caseIdSatListMap.get(currSat.Case_ID__c) == null) {
                List<Seat_Allocation_and_Ticketing__c> satListByCaseId = new List<Seat_Allocation_and_Ticketing__c>();
                satListByCaseId.add(currSat);
                caseIdSatListMap.put(currSat.Case_ID__c, satListByCaseId);
            } else {
                caseIdSatListMap.get(currSat.Case_ID__c).add(currSat); 
                caseIdSatListMap.put(currSat.Case_ID__c, caseIdSatListMap.get(currSat.Case_ID__c));
            }
        }
        
        Map<String, Contact> ContactMap = new Map<String, Contact>([SELECT Id, Amadeus_Post__c FROM Contact WHERE Id IN:ConIdSet]);
        // add new field for Middleware api
        List<Name_List__c> nameListList = [SELECT Id, Seat_Allocation_and_Ticketing__c, Name, 
                                           Date_Of_Birth__c, Title__c, First_Name__c, Last_Name__c, 
                                           Passenger_Type__c, Meal_Selection_All_Sector__c, 
                                           Meal_Selection_Departing_Only__c, Meal_Selection_Returning_Only__c, 
                                           Special_Service_Departing__c, Special_Service_Returning__c, 
                                           INF_Date_Of_Birth__c, INF_First_Name__c, INF_Last_name__c, 
                                           INF_Passenger_Type__c, INF_Title__c, INF_Meal_Selection_All_Sector__c,
                                           INF_Meal_Selection_Departing_Only__c, INF_Meal_Selection_Returning_Only__c,
                                           Gender__c,InfantGender__c, Passport_Issue_Country__c, Passport_No__c,
                                           Passport_Country__c, Passport_Expiry_Date__c, VISA_No__c, VISA_Country__c,
                                           VISA_Expiry_Date__c, INF_Passport_Issue_Country__c, INF_Passport_No__c,
                                           INF_Passport_Country__c, INF_Passport_Expiry_Date__c, INF_VISA_No__c,
                                           INF_VISA_Country__c, INF_VISA_Expiry_Date__c
                                           FROM Name_List__c WHERE Seat_Allocation_and_Ticketing__r.Case_ID__c IN:CaseIdSet];
        Map<String, List<Name_List__c>> satIdNameListListMap = new Map<String, List<Name_List__c>>();
        for (Name_List__c currNameList : nameListList) {
            if (satIdNameListListMap.get(currNameList.Seat_Allocation_and_Ticketing__c) == null) {
                List<Name_List__c> nameListListBySatId = new List<Name_List__c>();
                nameListListBySatId.add(currNameList);
                satIdNameListListMap.put(currNameList.Seat_Allocation_and_Ticketing__c, nameListListBySatId);
            } else {
                satIdNameListListMap.get(currNameList.Seat_Allocation_and_Ticketing__c).add(currNameList); 
                satIdNameListListMap.put(currNameList.Seat_Allocation_and_Ticketing__c, satIdNameListListMap.get(currNameList.Seat_Allocation_and_Ticketing__c));
            }
        }
        for (Case currCase : caseList) {
            if (!currCase.Integration_Link_Status__c) {
                currCase.addError('Please check Integration Link Status.');
                return ResponseUtil.buildStringListResponse('Please check Integration Link Status.');
            }
            if (currCase.Status != 'Ready for Ticketing') {
                currCase.addError('Please check Case Status.');
                return ResponseUtil.buildStringListResponse('Please check Case Status.');
            }
            List<Seat_Allocation_and_Ticketing__c> satToProcess = caseIdSatListMap.get(currCase.Id);
            if (satToProcess != null) {
                for (Seat_Allocation_and_Ticketing__c currSat : satToProcess) {
                    if (currSat.Departing_Flight_Number__c != 'none' && currSat.Departing_PNR_Status__c	!= 'KK' && currSat.Departing_PNR_Status__c != 'HK' && currSat.Departing_PNR_Status__c != 'RR') {
                        currCase.addError('Please check Departing PNR Status in SAT.');
                        return ResponseUtil.buildStringListResponse('Please check Departing PNR Status in SAT.');
                    }
                    if (currSat.Returning_Flight_Number__c != 'none' && currSat.Returning_PNR_Status__c	!= 'KK' && currSat.Returning_PNR_Status__c != 'HK' && currSat.Returning_PNR_Status__c != 'RR') {
                        currCase.addError('Please check Returning PNR Status in SAT.');
                        return ResponseUtil.buildStringListResponse('Please check Returning PNR Status in SAT.');
                    }
                    Contact currContact = ContactMap.get(currCase.ContactId);
                    List<Name_List__c> currNameListList = satIdNameListListMap.get(currSat.Id);
                    MwAddPaxWrapper wrapper = new MwAddPaxWrapper(currCase, currSat, currContact.Amadeus_Post__c, currNameListList);
                    MiddlewareUtil.addPax(currSat.Name, JSON.serialize(wrapper));
                }
            }
        }
        
        return ResponseUtil.buildStringListResponse('Processing is complete, please confirm Add Name List Status.');
    }

    public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
    
}