force-app/main/default/objects/Name_List__c/Name_List__c.object-meta.xml
<CustomObject>
    <label>Name List</label>
    <nameField>
        <displayFormat>NL{YYYY}{MM}{0000000000}</displayFormat>
        <label>Name List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Name_List__c/fields/INF_Meal_Selection_Status_Departing__c.field-meta.xml
<CustomField>
    <fullName>INF_Meal_Selection_Status_Departing__c</fullName>
    <label>INF_Meal Selection Status(Departing)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Meal_Selection_Status_Returning__c.field-meta.xml
<CustomField>
    <fullName>INF_Meal_Selection_Status_Returning__c</fullName>
    <label>INF_Meal Selection Status(Returning)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_PNR_Status_Departing__c.field-meta.xml
<CustomField>
    <fullName>INF_PNR_Status_Departing__c</fullName>
    <label>INF_PNR Status(Departing)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_PNR_Status_Returning__c.field-meta.xml
<CustomField>
    <fullName>INF_PNR_Status_Returning__c</fullName>
    <label>INF_PNR Status(Returning)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Meal_Selection_Status_Departing__c.field-meta.xml
<CustomField>
    <fullName>Meal_Selection_Status_Departing__c</fullName>
    <label>Meal Selection Status(Departing)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Meal_Selection_Status_Returning__c.field-meta.xml
<CustomField>
    <fullName>Meal_Selection_Status_Returning__c</fullName>
    <label>Meal Selection Status(Returning)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Seat_Allocation_and_Ticketing__c.field-meta.xml
<CustomField>
    <fullName>Seat_Allocation_and_Ticketing__c</fullName>
    <label>Seat Allocation and Ticketing</label>
    <referenceTo>Seat_Allocation_and_Ticketing__c</referenceTo>
    <relationshipLabel>Name Lists</relationshipLabel>
    <relationshipName>Name_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Special_Service_Status_Departing__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Status_Departing__c</fullName>
    <label>Special Service Status(Departing)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Special_Service_Status_Returning__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Status_Returning__c</fullName>
    <label>Special Service Status(Returning)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Add_Name_List_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Add_Name_List_Error_Message__c</fullName>
    <label>Add Name List Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Add_Name_List_Status__c.field-meta.xml
<CustomField>
    <fullName>Add_Name_List_Status__c</fullName>
    <label>Add Name List Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Booking_Reference_PNR__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference_PNR__c</fullName>
    <description>Temp PNR by B2B</description>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Departing_PNR_Status__c.field-meta.xml
<CustomField>
    <fullName>Departing_PNR_Status__c</fullName>
    <label>Departing PNR Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Adult__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Adult__c</fullName>
    <label>Final Unit Price(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Child__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Child__c</fullName>
    <label>Final Unit Price(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Infant__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Infant__c</fullName>
    <label>Final Unit Price (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Issue_Ticket_Status__c.field-meta.xml
<CustomField>
    <fullName>Issue_Ticket_Status__c</fullName>
    <label>Issue Ticket Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Returning_PNR_Status__c.field-meta.xml
<CustomField>
    <fullName>Returning_PNR_Status__c</fullName>
    <label>Returning PNR Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Tax_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date__c</fullName>
    <label>Tax Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Ticket_Currency__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Currency__c</fullName>
    <defaultValue>&quot;TWD&quot;</defaultValue>
    <label>Ticket Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Tour_Code__c.field-meta.xml
<CustomField>
    <fullName>Tour_Code__c</fullName>
    <label>Tour Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReceiveResponseAddNamelistApi.cls
@RestResource(urlMapping = '/receive-response/add-pax')
global class ReceiveResponseAddNamelistApi {
    
    @HttpPost
    global static void addNamelist() {
        RestRequest request = RestContext.request;
        RestResponse response = Restcontext.response;
        System.debug('[4i] Receive request addNamelist:' + request.requestBody.toString());
        
        ReceiveResponseAddNamelistWrapper requestBodyWrapper = ReceiveResponseAddNamelistWrapper.deserializeJson(request.requestBody.toString());
        
        if (requestBodyWrapper.isMissingRequiredFields()) {
            response = ResponseUtil.buildErrorRestResponse(response, Constants.MISSING_REQUIRED_FIELD);
            ApiLogger.log(request, response);
            return;
        }
        
        Seat_Allocation_and_Ticketing__c sat = [SELECT Id, Name, Departing_Flight_Number__c, Returning_Flight_Number__c, Add_Name_List_Status__c, Add_Name_List_Error_Message__c, Issue_Ticket_Status__c, Departing_PNR_Status__c, Returning_PNR_Status__c, Booking_Reference_PNR__c, Tour_Code__c, Ticket_Currency__c, Final_Unit_Price_Adult__c, Final_Unit_Price_Child__c, Final_Unit_Price_Infant__c, Tax_Date__c FROM Seat_Allocation_and_Ticketing__c WHERE Name =: requestBodyWrapper.sat_no];
        List<Name_List__c> nameListList = [SELECT Id, Name, Meal_Selection_Status_Departing__c, Meal_Selection_Status_Returning__c, Special_Service_Status_Departing__c, Special_Service_Status_Returning__c, INF_PNR_Status_Departing__c, INF_PNR_Status_Returning__c, INF_Meal_Selection_Status_Departing__c, INF_Meal_Selection_Status_Returning__c FROM Name_List__c WHERE Seat_Allocation_and_Ticketing__c = :sat.Id];
        Map<String, Name_List__c> nameListMap = new Map<String, Name_List__c>();
        for(Name_List__c currNameList : nameListList) {
            nameListMap.put(currNameList.Name, currNameList);
        }
        sat.Add_Name_List_Status__c = requestBodyWrapper.status;
        sat.Add_Name_List_Error_Message__c = '';
        if (requestBodyWrapper.status == Constants.PICKLIST_STATUS_FAIL) {
            sat.Add_Name_List_Error_Message__c = requestBodyWrapper.error_message;
        } else if (requestBodyWrapper.status == Constants.PICKLIST_STATUS_SUCCEEDED) {
            for (ReceiveResponseAddNamelistWrapper.Legs currLeg : requestBodyWrapper.legs) {
                if (currLeg.sorting == 1) {
                    if (sat.Departing_Flight_Number__c == 'none') {
                        sat.Returning_PNR_Status__c = currLeg.pnr_status;
                    } else {
                        sat.Departing_PNR_Status__c = currLeg.pnr_status;
                    }
                }
                if (currLeg.sorting == 2) {
                    sat.Returning_PNR_Status__c = currLeg.pnr_status;
                }
            }
            
            for (ReceiveResponseAddNamelistWrapper.Name_list currNameListWrapper : requestBodyWrapper.name_list) {  
                Name_List__c nameList = nameListMap.get(currNameListWrapper.nl_no);
                for (ReceiveResponseAddNamelistWrapper.Legs currLeg : currNameListWrapper.legs) {
                    if (currLeg.sorting == 1) {
                        if (sat.Departing_Flight_Number__c == 'none') {
                            nameList.Meal_Selection_Status_Returning__c = currLeg.meal_selection_status;
                            nameList.Special_Service_Status_Returning__c = currLeg.special_service_status;
                            nameList.INF_PNR_Status_Returning__c = currLeg.inf_pnr_status;
                            nameList.INF_Meal_Selection_Status_Returning__c = currLeg.inf_meal_selection_status;
                        } else {
                            nameList.Meal_Selection_Status_Departing__c = currLeg.meal_selection_status;
                            nameList.Special_Service_Status_Departing__c = currLeg.special_service_status;
                            nameList.INF_PNR_Status_Departing__c = currLeg.inf_pnr_status;
                            nameList.INF_Meal_Selection_Status_Departing__c = currLeg.inf_meal_selection_status;
                        }
                    }
                    if (currLeg.sorting == 2) {
                        nameList.Meal_Selection_Status_Returning__c = currLeg.meal_selection_status;
                        nameList.Special_Service_Status_Returning__c = currLeg.special_service_status;
                        nameList.INF_PNR_Status_Returning__c = currLeg.inf_pnr_status;
                        nameList.INF_Meal_Selection_Status_Returning__c = currLeg.inf_meal_selection_status;
                    }
                }
            }
        }
        
        Database.update(sat);
        Database.update(nameListList);
        response = ResponseUtil.buildSuccessRestResponse(response);
        
        ApiLogger.log(request, response);
        
        if (requestBodyWrapper.status == Constants.PICKLIST_STATUS_SUCCEEDED) {
            IssueTicketScheduler m = new IssueTicketScheduler(sat);
            Datetime now = Datetime.now().addSeconds(10);
            String sch = now.second()+' '+now.minute()+' '+now.hour()+' '+now.day()+' '+now.month()+' ? '+now.year();
            system.schedule('IssueTicket Job - ' + sat.Name, sch, m);
        }
    }

    public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}