force-app/main/default/objects/Name_List__c/Name_List__c.object-meta.xml
<CustomObject>
    <label>Name List</label>
    <nameField>
        <displayFormat>NL{YYYY}{MM}{0000000000}</displayFormat>
        <label>Name List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Name_List__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_340, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_340)) &amp;  Seat_Allocation_and_Ticketing__r.Case_ID__c,  Seat_Allocation_and_Ticketing__r.Case_ID__r.CaseNumber, &quot;_self&quot; )</formula>
    <label>Case ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Issue_Ticket_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>INF_Issue_Ticket_Error_Message__c</fullName>
    <label>INF_Issue Ticket Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>INF_Ticket_Number__c</fullName>
    <label>INF_Ticket Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Seat_Allocation_and_Ticketing__c.field-meta.xml
<CustomField>
    <fullName>Seat_Allocation_and_Ticketing__c</fullName>
    <label>Seat Allocation and Ticketing</label>
    <referenceTo>Seat_Allocation_and_Ticketing__c</referenceTo>
    <relationshipLabel>Name Lists</relationshipLabel>
    <relationshipName>Name_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Allocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Type__c</fullName>
    <label>Allocation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SRS</fullName>
            </value>
            <value>
                <fullName>ADC</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Seat Allocations and Ticketings</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Allocated_Seats__c</fullName>
    <label>Final Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Issue_Ticket_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Issue_Ticket_Error_Message__c</fullName>
    <label>Issue Ticket Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Issue_Ticket_Status__c.field-meta.xml
<CustomField>
    <fullName>Issue_Ticket_Status__c</fullName>
    <label>Issue Ticket Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Issue_Ticket_Time__c.field-meta.xml
<CustomField>
    <fullName>Issue_Ticket_Time__c</fullName>
    <label>Issue Ticket Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Sync_SAT_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_SAT_Status__c</fullName>
    <label>Sync SAT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/recordTypes/Planned_Allocation.recordType-meta.xml
<RecordType>
    <fullName>Planned_Allocation</fullName>
    <active>true</active>
    <description>For STARLUX to create Seat Allocation for Travel Agency</description>
    <label>Planned Allocation</label>
</RecordType>

force-app/main/default/classes/ReceiveResponseIssueTicketApi.cls
@RestResource(urlMapping = '/receive-response/issue-ticket')
global class ReceiveResponseIssueTicketApi {

    @HttpPost
    global static void issueTicket() {
        RestRequest request = RestContext.request;
        RestResponse response = Restcontext.response;
        System.debug('[4i] Receive request issueTicket:' + request.requestBody.toString());
        
        ReceiveResponseIssueTicketWrapper requestBodyWrapper = ReceiveResponseIssueTicketWrapper.deserializeJson(request.requestBody.toString());
        
        if (requestBodyWrapper.isMissingRequiredFields()) {
            response = ResponseUtil.buildErrorRestResponse(response, Constants.MISSING_REQUIRED_FIELD);
            ApiLogger.log(request, response);
            return;
        }
        
        Seat_Allocation_and_Ticketing__c sat = [SELECT Id, Name, Case_ID__c, Issue_Ticket_Status__c, Issue_Ticket_Error_Message__c, Issue_Ticket_Time__c FROM Seat_Allocation_and_Ticketing__c WHERE Name =: requestBodyWrapper.sat_no];
        List<Name_List__c> nameListList = [SELECT Id, Name, Issue_Ticket_Error_Message__c, INF_Issue_Ticket_Error_Message__c, Ticket_Number__c, INF_Ticket_Number__c FROM Name_List__c WHERE Seat_Allocation_and_Ticketing__c = :sat.Id];
        Map<String, Name_List__c> nameListMap = new Map<String, Name_List__c>();
        for(Name_List__c currNameList : nameListList) {
            nameListMap.put(currNameList.Name, currNameList);
        }
        Id plannedAllocationRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Planned_Allocation' and SObjectType = 'Seat_Allocation_and_Ticketing__c'].Id;
        List<Seat_Allocation_and_Ticketing__c> allSatInSameCase = [SELECT Id, Issue_Ticket_Status__c FROM Seat_Allocation_and_Ticketing__c WHERE (Allocation_Type__c = :Constants.PICKLIST_SAT_ALLOCATION_TYPE_SRS OR Allocation_Type__c = :Constants.PICKLIST_SAT_ALLOCATION_TYPE_ADC) AND Final_Allocated_Seats__c > 0 AND Sync_SAT_Status__c = :Constants.PICKLIST_STATUS_SUCCEEDED AND recordTypeId = :plannedAllocationRecordTypeId AND Case_ID__c =: sat.Case_ID__c];
        Case caseToChangeStatus = [SELECT Id, status FROM Case WHERE Id =: sat.Case_ID__c];
        
        sat.Issue_Ticket_Status__c = requestBodyWrapper.status;
        sat.Issue_Ticket_Error_Message__c = '';
        if (requestBodyWrapper.status == Constants.PICKLIST_STATUS_FAIL) {
            sat.Issue_Ticket_Error_Message__c = 'Partial failed, please confirm Issue Ticket Error Message on Name List.';
            for (ReceiveResponseIssueTicketWrapper.Name_list currNameListWrapper : requestBodyWrapper.name_list) {  
                Name_List__c nameList = nameListMap.get(currNameListWrapper.nl_no);
                nameList.Ticket_Number__c = currNameListWrapper.ticket_no;
                nameList.INF_Ticket_Number__c = currNameListWrapper.inf_ticket_no;
                nameList.Issue_Ticket_Error_Message__c = currNameListWrapper.error_message;
                nameList.INF_Issue_Ticket_Error_Message__c = currNameListWrapper.inf_error_message;
            }
        } else if (requestBodyWrapper.status == Constants.PICKLIST_STATUS_SUCCEEDED) {
            for (ReceiveResponseIssueTicketWrapper.Name_list currNameListWrapper : requestBodyWrapper.name_list) {  
                Name_List__c nameList = nameListMap.get(currNameListWrapper.nl_no);
                nameList.Ticket_Number__c = currNameListWrapper.ticket_no;
                nameList.INF_Ticket_Number__c = currNameListWrapper.inf_ticket_no;
                nameList.Issue_Ticket_Error_Message__c = '';
                nameList.INF_Issue_Ticket_Error_Message__c = '';
            }
            sat.Issue_Ticket_Time__c = Datetime.now();
            Boolean isAllSatPass = true;
            for (Seat_Allocation_and_Ticketing__c currSat : allSatInSameCase) {
                if (currSat.Issue_Ticket_Status__c != Constants.PICKLIST_STATUS_SUCCEEDED && currSat.Id != sat.Id) {
                    isAllSatPass = false;
                }
            }
            if (isAllSatPass) {
                caseToChangeStatus.status = 'Ticket Issued';
                Database.update(caseToChangeStatus);
            }
        }

        String jobName = 'IssueTicket Job - ' + sat.Name;
        for(CronTrigger aJob : [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :jobName AND State = 'DELETED']) {
            System.AbortJob(aJob.Id);
        }
        
        Database.update(sat);
        Database.update(nameListList);
        response = ResponseUtil.buildSuccessRestResponse(response);
        
        ApiLogger.log(request, response);
    }

    public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}