force-app/main/default/objects/Name_List__c/Name_List__c.object-meta.xml
<CustomObject>
    <label>Name List</label>
    <nameField>
        <displayFormat>NL{YYYY}{MM}{0000000000}</displayFormat>
        <label>Name List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Name Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Name_List__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <formula>HYPERLINK(LEFT($Api.Partner_Server_URL_340, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_340)) &amp;  Seat_Allocation_and_Ticketing__r.Case_ID__c,  Seat_Allocation_and_Ticketing__r.Case_ID__r.CaseNumber, &quot;_self&quot; )</formula>
    <label>Case ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>Given Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
                <isActive>false</isActive>
                <label>Female</label>
            </value>
            <value>
                <fullName>Male</fullName>
                <isActive>false</isActive>
                <label>Male</label>
            </value>
            <value>
                <fullName>Undisclosed Gender</fullName>
                <isActive>false</isActive>
                <label>Undisclosed Gender</label>
            </value>
            <value>
                <fullName>Unspecified Gender</fullName>
                <isActive>false</isActive>
                <label>Unspecified Gender</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>INF_Date_of_Birth__c</fullName>
    <label>INF_Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_First_Name__c.field-meta.xml
<CustomField>
    <fullName>INF_First_Name__c</fullName>
    <label>INF_First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>INF_Last_Name__c</fullName>
    <label>INF_Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Meal_Selection_All_Sector__c.field-meta.xml
<CustomField>
    <fullName>INF_Meal_Selection_All_Sector__c</fullName>
    <label>INF_Meal Selection(All Sector)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BBML</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Meal_Selection_Departing_Only__c.field-meta.xml
<CustomField>
    <fullName>INF_Meal_Selection_Departing_Only__c</fullName>
    <label>INF_Meal Selection(Departing Only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BBML</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Passenger_Type__c.field-meta.xml
<CustomField>
    <fullName>INF_Passenger_Type__c</fullName>
    <label>INF_Passenger Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Passenger_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>infant</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/INF_Title__c.field-meta.xml
<CustomField>
    <fullName>INF_Title__c</fullName>
    <label>INF_Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MSTR</fullName>
            </value>
            <value>
                <fullName>MISS</fullName>
            </value>
            <value>
                <fullName>Mister</fullName>
                <isActive>false</isActive>
                <label>Mister</label>
            </value>
            <value>
                <fullName>Testing</fullName>
                <isActive>false</isActive>
                <label>Testing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/InfantGender__c.field-meta.xml
<CustomField>
    <fullName>InfantGender__c</fullName>
    <label>INF_Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
                <isActive>false</isActive>
                <label>Female</label>
            </value>
            <value>
                <fullName>Female Infant</fullName>
                <isActive>false</isActive>
                <label>Female Infant</label>
            </value>
            <value>
                <fullName>Male</fullName>
                <isActive>false</isActive>
                <label>Male</label>
            </value>
            <value>
                <fullName>Male Infant</fullName>
                <isActive>false</isActive>
                <label>Male Infant</label>
            </value>
            <value>
                <fullName>Undisclosed Gender</fullName>
                <isActive>false</isActive>
                <label>Undisclosed Gender</label>
            </value>
            <value>
                <fullName>Unspecified Gender</fullName>
                <isActive>false</isActive>
                <label>Unspecified Gender</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Surname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Meal_Selection_All_Sector__c.field-meta.xml
<CustomField>
    <fullName>Meal_Selection_All_Sector__c</fullName>
    <label>Meal Selection(All Sector)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meal_Selection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Meal_Selection_Departing_Only__c.field-meta.xml
<CustomField>
    <fullName>Meal_Selection_Departing_Only__c</fullName>
    <label>Meal Selection(Departing Only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meal_Selection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Meal_Selection_Returning_Only__c.field-meta.xml
<CustomField>
    <fullName>Meal_Selection_Returning_Only__c</fullName>
    <label>Meal Selection(Returning Only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Meal_Selection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Passenger_Type__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Type__c</fullName>
    <label>Passenger Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>adult</fullName>
            </value>
            <value>
                <fullName>child</fullName>
            </value>
            <value>
                <fullName>false</fullName>
                <isActive>false</isActive>
                <label>false</label>
            </value>
            <value>
                <fullName>null</fullName>
                <isActive>false</isActive>
                <label>null</label>
            </value>
            <value>
                <fullName>r</fullName>
                <isActive>false</isActive>
                <label>r</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Seat_Allocation_and_Ticketing__c.field-meta.xml
<CustomField>
    <fullName>Seat_Allocation_and_Ticketing__c</fullName>
    <label>Seat Allocation and Ticketing</label>
    <referenceTo>Seat_Allocation_and_Ticketing__c</referenceTo>
    <relationshipLabel>Name Lists</relationshipLabel>
    <relationshipName>Name_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Special_Service_Departing__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Departing__c</fullName>
    <label>Special Service(Departing)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Special_Service</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Special_Service_Returning__c.field-meta.xml
<CustomField>
    <fullName>Special_Service_Returning__c</fullName>
    <label>Special Service(Returning)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Special_Service</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Name_List__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MR</fullName>
            </value>
            <value>
                <fullName>MRS</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MSTR</fullName>
            </value>
            <value>
                <fullName>MISS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Add_Name_List_Status__c.field-meta.xml
<CustomField>
    <fullName>Add_Name_List_Status__c</fullName>
    <label>Add Name List Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Allocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Type__c</fullName>
    <label>Allocation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SRS</fullName>
            </value>
            <value>
                <fullName>ADC</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Seat Allocations and Ticketings</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Departing_PNR_Status__c.field-meta.xml
<CustomField>
    <fullName>Departing_PNR_Status__c</fullName>
    <label>Departing PNR Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Allocated_Seats__c</fullName>
    <label>Final Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Returning_PNR_Status__c.field-meta.xml
<CustomField>
    <fullName>Returning_PNR_Status__c</fullName>
    <label>Returning PNR Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Sync_SAT_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_SAT_Status__c</fullName>
    <label>Sync SAT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/recordTypes/Planned_Allocation.recordType-meta.xml
<RecordType>
    <fullName>Planned_Allocation</fullName>
    <active>true</active>
    <description>For STARLUX to create Seat Allocation for Travel Agency</description>
    <label>Planned Allocation</label>
</RecordType>

force-app/main/default/classes/AddPaxInvocableMethod.cls
public class AddPaxInvocableMethod {
    @InvocableMethod(label='Add Pax')
    public static List<String> addPaxInvocableMethod(List<Seat_Allocation_and_Ticketing__c> satList) {
        Seat_Allocation_and_Ticketing__c currSat = satList.get(0);
        Case currCase = [SELECT Id, Integration_Link_Status__c, Status, Route__c, ContactId FROM Case WHERE Id = :currSat.Case_Id__c];
        Id plannedAllocationRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Planned_Allocation' and SObjectType = 'Seat_Allocation_and_Ticketing__c'].Id;
        if (!currCase.Integration_Link_Status__c) {
            return ResponseUtil.buildStringListResponse('Please check Integration Link Status.');
        }
        if (currCase.Status != 'Ready for Ticketing') {
            return ResponseUtil.buildStringListResponse('Please check Case Status.');
        }
        
        if (currSat.recordTypeId != plannedAllocationRecordTypeId) {
            return ResponseUtil.buildStringListResponse('Please check record type.');
        }
        
        if (currSat.Allocation_Type__c != Constants.PICKLIST_SAT_ALLOCATION_TYPE_SRS && currSat.Allocation_Type__c != Constants.PICKLIST_SAT_ALLOCATION_TYPE_ADC) {
            return ResponseUtil.buildStringListResponse('Please check Allocation Type.');
        }
        
        if (currSat.Final_Allocated_Seats__c == 0) {
            return ResponseUtil.buildStringListResponse('Please check Final Allocated Seats.');
        }
        
        if (currSat.Sync_SAT_Status__c != Constants.PICKLIST_STATUS_SUCCEEDED) {
            return ResponseUtil.buildStringListResponse('Please check Sync SAT Status.');
        }
        
        if (currSat.Add_Name_List_Status__c == Constants.PICKLIST_STATUS_SUCCEEDED) {
            return ResponseUtil.buildStringListResponse('Please check Add Name List Status.');
        }
        
        if (currSat.Departing_Flight_Number__c != 'none' && currSat.Departing_PNR_Status__c != 'KK' && currSat.Departing_PNR_Status__c != 'HK' && currSat.Departing_PNR_Status__c != 'RR') {
            return ResponseUtil.buildStringListResponse('Please check Departing PNR Status.');
        }
        
        if (currSat.Returning_Flight_Number__c != 'none' && currSat.Returning_PNR_Status__c	!= 'KK' && currSat.Returning_PNR_Status__c != 'HK' && currSat.Returning_PNR_Status__c != 'RR') {
            return ResponseUtil.buildStringListResponse('Please check Returning PNR Status.');
        }
        
        Contact currContact = [SELECT Id, Amadeus_Post__c FROM Contact WHERE Id = :currCase.ContactId];
        List<Name_List__c> nameListList = [SELECT Id, Name, Date_Of_Birth__c, Title__c, First_Name__c, Last_Name__c, Passenger_Type__c, 
                                           Meal_Selection_All_Sector__c, Meal_Selection_Departing_Only__c, Meal_Selection_Returning_Only__c, 
                                           Special_Service_Departing__c, Special_Service_Returning__c, INF_Date_Of_Birth__c, INF_First_Name__c, 
                                           INF_Last_name__c, INF_Passenger_Type__c, INF_Title__c, INF_Meal_Selection_All_Sector__c, InfantGender__c,
                                           INF_Meal_Selection_Departing_Only__c, INF_Meal_Selection_Returning_Only__c ,Gender__c, 
                                           Passport_Issue_Country__c, INF_Passport_Issue_Country__c, Passport_No__c, INF_Passport_No__c, 
                                           Passport_Country__c, INF_Passport_Country__c, Passport_Expiry_Date__c, INF_Passport_Expiry_Date__c, 
                                           VISA_No__c, INF_VISA_No__c, VISA_Country__c, INF_VISA_Country__c, VISA_Expiry_Date__c, INF_VISA_Expiry_Date__c
                                           FROM Name_List__c 
                                           WHERE Seat_Allocation_and_Ticketing__c = :currSat.Id];
        MwAddPaxWrapper wrapper = new MwAddPaxWrapper(currCase, currSat, currContact.Amadeus_Post__c, nameListList);
        MiddlewareUtil.addPax(currSat.Name, JSON.serialize(wrapper, false));
        
        return ResponseUtil.buildStringListResponse('Processing is complete, please confirm Add Name List Status.');
    }

    public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}