force-app/main/default/objects/Ticket_Encoding_Rule__c/Ticket_Encoding_Rule__c.object-meta.xml
<CustomObject>
    <description>編碼原則</description>
    <label>Ticket Encoding Rule</label>
    <nameField>
        <displayFormat>TER-{00000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Encoding Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Encoding_Rule__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <defaultValue>&apos;JX&apos;</defaultValue>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule__c/fields/End_Check_Code__c.field-meta.xml
<CustomField>
    <fullName>End_Check_Code__c</fullName>
    <label>End Check Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule__c/fields/End_No__c.field-meta.xml
<CustomField>
    <fullName>End_No__c</fullName>
    <label>End No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule__c/fields/Start_Check_Code__c.field-meta.xml
<CustomField>
    <fullName>Start_Check_Code__c</fullName>
    <label>Start Check Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule__c/fields/Start_No__c.field-meta.xml
<CustomField>
    <fullName>Start_No__c</fullName>
    <label>Start No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/trTicket_Encoding_Rule_TEST.cls
@isTest 
public without sharing class trTicket_Encoding_Rule_TEST {
    static testmethod void trTicket_Encoding_Rule_TEST1(){
        Ticket_Encoding_Rule__c TER = new Ticket_Encoding_Rule__c();
        TER.Type__c = 'CPN';
        TER.Country__c = 'TW';
        TER.Year__c = 23;
        TER.Batch__c = 'A';
        TER.Start_No__c = '001';
        TER.End_No__c = '003';
        TER.Start_Check_Code__c = '01';
        TER.End_Check_Code__c = '02';
        TER.RecordTypeId = Schema.getGlobalDescribe().get('Ticket_Encoding_Rule__c').getDescribe().getRecordTypeInfosByName().get('Certificate No').getRecordTypeId();
        Insert TER;
    }
    static testmethod void trTicket_Encoding_Rule_TEST2(){
        Ticket_Encoding_Rule__c TER2 = new Ticket_Encoding_Rule__c();
        TER2.Code__c = 'CPN';
        TER2.Department__c = 'TW';
        TER2.Year__c = 23;
        TER2.Start_No__c = '996';
        TER2.RecordTypeId = Schema.getGlobalDescribe().get('Ticket_Encoding_Rule__c').getDescribe().getRecordTypeInfosByName().get('Item No').getRecordTypeId();
        Insert TER2;
    }
    static testmethod void trTicket_Encoding_Rule_TEST3(){
        Ticket_Encoding_Rule__c TER3 = new Ticket_Encoding_Rule__c();
        TER3.Code__c = 'CPN';
        TER3.Year__c = 23;
        TER3.Start_No__c = '9996';
        TER3.RecordTypeId = Schema.getGlobalDescribe().get('Ticket_Encoding_Rule__c').getDescribe().getRecordTypeInfosByName().get('Coupon No').getRecordTypeId();
        Insert TER3;
    }
}