force-app/main/default/objects/Case_Coupon__c/Case_Coupon__c.object-meta.xml
<CustomObject>
    <label>Case Voucher</label>
    <nameField>
        <displayFormat>CCID-{00000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Vouchers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Coupon__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <label>Voucher Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coupon__c.Coupon_Status__c</field>
            <operation>equals</operation>
            <value>Distributed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Case Vouchers</relationshipLabel>
    <relationshipName>Case_Coupons</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Case_Coupon__c/fields/Coupon_Number__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Number__c</fullName>
    <description>corresponding Coupon ID</description>
    <label>Voucher Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>Custom object to store pre-generated and post-generated coupon records.</description>
    <label>Voucher</label>
    <nameField>
        <label>Voucher Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseCouponTriggerHandler.cls
/********************************************************************************************************
NAME:           CaseCouponTriggerHandler
AUTHOR:         Chris (chrishsu@starlux-airlines.com)
PURPOSE:        Convert coupon number to corresponding coupon id

UPDATE HISTORY:
DATE            AUTHOR          COMMENTS
-------------------------------------------------------------
2021-05-03      Chris Hsu       First version
********************************************************************************************************/

public class CaseCouponTriggerHandler extends TriggerHandler{
    public CaseCouponTriggerHandler() {
    }
    
    /*** Context Overrides ***/
    public override void beforeInsert() {
        processUpdateRecords();
    }
    
    public override void beforeUpdate() {
        processUpdateRecords();
    }
   
    private static void processUpdateRecords() {		
        for(Case_Coupon__c newCaseCoupon : (List<Case_Coupon__c>)Trigger.new){
            if (newCaseCoupon.Coupon_Number__c==null || newCaseCoupon.Coupon_Number__c=='')
                continue;            
            List<Coupon__c> queryCoupon = [select Id from Coupon__c where Name = :newCaseCoupon.Coupon_Number__c Limit 1];
            newCaseCoupon.Coupon_ID__c = queryCoupon.get(0).Id;
        }
    }
    
    public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}