force-app/main/default/objects/Case_Coupon__c/Case_Coupon__c.object-meta.xml
<CustomObject>
    <label>Case Voucher</label>
    <nameField>
        <displayFormat>CCID-{00000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Vouchers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Coupon__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Coupons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Case_Coupon__c/fields/Coupon_ID__c.field-meta.xml
<CustomField>
    <fullName>Coupon_ID__c</fullName>
    <label>Voucher Number</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Coupon__c.Coupon_Status__c</field>
            <operation>equals</operation>
            <value>Distributed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Coupon__c</referenceTo>
    <relationshipLabel>Case Vouchers</relationshipLabel>
    <relationshipName>Case_Coupons</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Case_Coupon__c/fields/Coupon_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Issue_Date__c</fullName>
    <label>Voucher Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case_Coupon__c/fields/Coupon_Number__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Number__c</fullName>
    <description>corresponding Coupon ID</description>
    <label>Voucher Number</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Coupon__c/fields/Coupon_Status__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Status__c</fullName>
    <formula>TEXT(Coupon_ID__r.Coupon_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Voucher Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Coupon__c/fields/Frontline_Authorization_Code__c.field-meta.xml
<CustomField>
    <fullName>Frontline_Authorization_Code__c</fullName>
    <label>Frontline Authorization Code (ex:A01B1S)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Coupon__c/fields/Issue_Reason__c.field-meta.xml
<CustomField>
    <fullName>Issue_Reason__c</fullName>
    <label>Issue Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meal Quality</fullName>
                <default>true</default>
                <label>Meal Quality</label>
            </value>
            <value>
                <fullName>Irregular Meal Handling</fullName>
            </value>
            <value>
                <fullName>Cabin Facilities/Equipment Issues</fullName>
            </value>
            <value>
                <fullName>Flight Irregularities</fullName>
            </value>
            <value>
                <fullName>INVL Downgrade/Overbooking</fullName>
            </value>
            <value>
                <fullName>Passenger Injury</fullName>
            </value>
            <value>
                <fullName>Spilling Issues</fullName>
            </value>
            <value>
                <fullName>Mishandled Baggage</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coupon__c/Coupon__c.object-meta.xml
<CustomObject>
    <description>Custom object to store pre-generated and post-generated coupon records.</description>
    <label>Voucher</label>
    <nameField>
        <label>Voucher Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vouchers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Coupon__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Coupon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Coupon_Distributed_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Distributed_Date__c</fullName>
    <label>Voucher Distributed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Coupon_Distributed_to_Agent_Date__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Distributed_to_Agent_Date__c</fullName>
    <label>Voucher Distributed to Agent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Coupon_Status__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Status__c</fullName>
    <label>Voucher Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Coupon_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Coupon__c/fields/Distributed_Agent__c.field-meta.xml
<CustomField>
    <fullName>Distributed_Agent__c</fullName>
    <label>Voucher Distribute to Agent(Employee ID)</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Flow_CouponUsed.cls
public with sharing class Flow_CouponUsed {
    public class Input {
        @InvocableVariable(label='Start Name' required=true)
        public String startName; //其實Flow傳來的是ID
        @InvocableVariable(label='End Name' required=true)
        public String endName;   //其實Flow傳來的是ID
        @InvocableVariable(label='Case Id' required=true)
        public String CaseId;
        @InvocableVariable(label='Issue Date' required=true)
        public Date issueDate;
        @InvocableVariable(label='Issue Reason' required=true)
        public String issueReason;
        //@InvocableVariable(label='Frontline Authorization Code' required=true) 23-11-23 Aaron
        @InvocableVariable(label='Frontline Authorization Code')
        public String frontlineAuthorizationCode;
    }
    
    public class Output {
        @InvocableVariable(label='Error Message')
        public String errMsg;
    }

    @InvocableMethod
    public static Void fetchCoupons(List<Input> inputList) {
        try {
            List<Coupon__c> couponsToUpdate = new List<Coupon__c>();
            List<Case_Coupon__c> Create_Case_Coupon = new List<Case_Coupon__c>();
            String UserId = UserInfo.getUserId();
            User CurrentUser = [SELECT Id, Department, Name, LastName, FirstName FROM User where Id = :UserId];
            for (Input input : inputList) {
                /*
                Coupon__c C1 = [SELECT Id, Name FROM Coupon__c WHERE Id = :input.startName];
                Coupon__c C2 = [SELECT Id, Name FROM Coupon__c WHERE Id = :input.endName];
                */
                String CurrentCaseId = input.CaseId;
                // 查詢符合條件的所有Coupon__c记录
                //List<Coupon__c> AllC = [SELECT Id, Name, Coupon_Status__c, Case_ID__c FROM Coupon__c WHERE Name >= :C1.Name AND Name <= :C2.Name AND Coupon_Status__c = 'Distributed']; 
                List<Coupon__c> AllC = [SELECT Id, Name, Coupon_Status__c, Case_ID__c FROM Coupon__c WHERE Name >= :input.startName AND Name <= :input.endName AND Coupon_Status__c = 'Distributed']; 
                
                //System.debug(C1);
                //System.debug(C2);
                System.debug(AllC);
                System.debug(CurrentCaseId);
                
                for (Coupon__c coupon : AllC) {
                    // 修改 Coupon__c狀態
                    coupon.Coupon_Status__c = 'Used';
                    coupon.Case_ID__c = CurrentCaseId;
                    //coupon.Coupon_Distributed_Date__c = system.today();
                    //coupon.Coupon_Distributed_to_Agent_Date__c = system.today();
                    //coupon.Distributed_Agent__c = CurrentUser.Id;
                    //coupon.Distributed_Department__c= 'AOD-TAP';
                    //couponsToUpdate.add(coupon);
                    //建一筆 Case_Coupon__c
                    Case_Coupon__c temp_Case_Coupon = new Case_Coupon__c();
                    temp_Case_Coupon.Case_ID__c = CurrentCaseId;
                    temp_Case_Coupon.Coupon_ID__c = coupon.Id;
                    temp_Case_Coupon.Coupon_Issue_Date__c = input.issueDate;
                    temp_Case_Coupon.Coupon_Number__c = coupon.Name;
                    temp_Case_Coupon.Issue_Reason__c = input.issueReason;
                    temp_Case_Coupon.Frontline_Authorization_Code__c = input.frontlineAuthorizationCode;
                    System.debug(temp_Case_Coupon);
                    Create_Case_Coupon.add(temp_Case_Coupon);
                }
            }
            
            // 更新所有已修改的Coupon__c記錄
            /*
            if (!couponsToUpdate.isEmpty()) {
                update couponsToUpdate;
                System.debug(couponsToUpdate);
            }*/
            if (!Create_Case_Coupon.isEmpty()) {
                Insert Create_Case_Coupon;
                System.debug(Create_Case_Coupon);
            }
            System.debug(Create_Case_Coupon);
        } catch(exception e) {
            Output output = new Output();
            output.errMsg = 'failed, error: ' + e + 'at line: ' + e.getLineNumber();
            System.debug(output);
        }

    }
}