force-app/main/default/objects/Customer_Satisfaction_Surveys__c/Customer_Satisfaction_Surveys__c.object-meta.xml
<CustomObject>
    <label>Customer Satisfaction Surveys</label>
    <nameField>
        <displayFormat>CSS{YYYY}{MM}{00000000}</displayFormat>
        <label>Customer Satisfaction Surveys No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Satisfaction Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Departing_Date__c.field-meta.xml
<CustomField>
    <fullName>Departing_Date__c</fullName>
    <label>Departing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DupeDeleterTest.cls
@IsTest class DupeDeleterTest {

    @IsTest static void test1(){
		Date systemToday = System.today()-2;
        Customer_Satisfaction_Surveys__c a = new Customer_Satisfaction_Surveys__c(Departing_Date__c = systemToday,Email_Address__c = 'test@test.com');
        Customer_Satisfaction_Surveys__c b = new Customer_Satisfaction_Surveys__c(Departing_Date__c = systemToday,Email_Address__c = 'test@test.com');
        Customer_Satisfaction_Surveys__c c = new Customer_Satisfaction_Surveys__c(Departing_Date__c = systemToday,Email_Address__c = 'test2@test.com');
        Customer_Satisfaction_Surveys__c d = new Customer_Satisfaction_Surveys__c(Departing_Date__c = systemToday,Email_Address__c = 'test2@test.com');
        Customer_Satisfaction_Surveys__c e = new Customer_Satisfaction_Surveys__c(Departing_Date__c = systemToday,Email_Address__c = 'test3@test.com');        
        insert a;
        insert b;
        insert c;
        insert d;
        insert e;

        Test.startTest();        DupeDeleter.deleteDupes();        Test.stopTest();

    }

}