force-app/main/default/objects/Customer_Satisfaction_Surveys__c/Customer_Satisfaction_Surveys__c.object-meta.xml
<CustomObject>
    <label>Customer Satisfaction Surveys</label>
    <nameField>
        <displayFormat>CSS{YYYY}{MM}{00000000}</displayFormat>
        <label>Customer Satisfaction Surveys No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Satisfaction Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Booking_class__c.field-meta.xml
<CustomField>
    <fullName>Booking_class__c</fullName>
    <label>Booking class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Departing_Date__c.field-meta.xml
<CustomField>
    <fullName>Departing_Date__c</fullName>
    <label>Departing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Departing_Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Departing_Flight_Number__c</fullName>
    <label>Departing Flight Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Survey_Type__c.field-meta.xml
<CustomField>
    <fullName>Survey_Type__c</fullName>
    <label>Survey Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ticket buying experience</fullName>
            </value>
            <value>
                <fullName>Flight experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Survey_URL__c.field-meta.xml
<CustomField>
    <fullName>Survey_URL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey URL</label>
    <referenceTo>Survey_URL__c</referenceTo>
    <relationshipLabel>Customer Satisfaction Surveys</relationshipLabel>
    <relationshipName>SurveyURL_Customer_Satisfaction_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Ticket_buying_date__c.field-meta.xml
<CustomField>
    <fullName>Ticket_buying_date__c</fullName>
    <label>Ticket buying date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Flight_Survey_Setting__c/Flight_Survey_Setting__c.object-meta.xml
<CustomObject>
    <label>Flight Survey Setting</label>
    <nameField>
        <label>Departing Filght Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Survey Setting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight_Survey_Setting__c/fields/Departing_Filght_Number_Rate__c.field-meta.xml
<CustomField>
    <fullName>Departing_Filght_Number_Rate__c</fullName>
    <label>Departing Filght Number Rate</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Flight_Survey_Setting__c/fields/LuckyDrawSettingID__c.field-meta.xml
<CustomField>
    <fullName>LuckyDrawSettingID__c</fullName>
    <label>Drawing No.</label>
    <referenceTo>Lucky_Draw_Setting__c</referenceTo>
    <relationshipName>CSS_Flight_Survey_Setting</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lucky_Draw_Setting__c/Lucky_Draw_Setting__c.object-meta.xml
<CustomObject>
    <label>Lucky Draw Setting</label>
    <nameField>
        <label>Lucky Draw Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lucky Draw Setting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lucky_Draw_Setting__c/fields/Drawing_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Drawing_End_Date__c</fullName>
    <description>活動結束日期</description>
    <inlineHelpText>活動結束日期</inlineHelpText>
    <label>Drawing End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lucky_Draw_Setting__c/fields/Drawing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Drawing_Start_Date__c</fullName>
    <description>活動開始日期</description>
    <inlineHelpText>活動開始日期</inlineHelpText>
    <label>Drawing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lucky_Draw_Setting__c/fields/First_Class_Delivery_Rate__c.field-meta.xml
<CustomField>
    <fullName>First_Class_Delivery_Rate__c</fullName>
    <label>First Class Delivery Rate</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lucky_Draw_Setting__c/fields/Other_Delivery_Rate__c.field-meta.xml
<CustomField>
    <fullName>Other_Delivery_Rate__c</fullName>
    <label>Other Delivery Rate</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Survey_URL__c/Survey_URL__c.object-meta.xml
<CustomObject>
    <label>Survey URL</label>
    <nameField>
        <label>Survey URL</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey URL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_URL__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Survey_URL__c/fields/Survey_Type__c.field-meta.xml
<CustomField>
    <fullName>Survey_Type__c</fullName>
    <label>Survey Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ticket buying experience</fullName>
            </value>
            <value>
                <fullName>Flight experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_URL__c/fields/Unique_Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Unique_Expired_Date__c</fullName>
    <label>Unique Expired Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Survey_URL__c/fields/Used__c.field-meta.xml
<CustomField>
    <fullName>Used__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Used</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchSendEDM_Test.cls
@isTest
public class BatchSendEDM_Test {
    @testSetup
    static void initTestData() 
    {
        Date today = Date.today();

        Customer_Satisfaction_Surveys__c C1 = new Customer_Satisfaction_Surveys__c();
        C1.Survey_Type__c = 'Ticket buying experience';
        C1.Date_of_Birth__c = Date.newInstance(2000, 10, 18);
        C1.Booking_class__c = 'J';
        C1.Ticket_buying_date__c = today.addDays(-5);
        C1.Departing_Date__c = today.addDays(-5);
        C1.Departing_Flight_Number__c = 'aa';
        C1.Email_Address__c = 'ethan1688.lin@gmail.com';
        insert C1;

        Customer_Satisfaction_Surveys__c C2 = new Customer_Satisfaction_Surveys__c();
        C2.Survey_Type__c = 'Ticket buying experience';
        C2.Date_of_Birth__c = Date.newInstance(2000, 10, 18);
        C2.Booking_class__c = 'Y';
        C2.Ticket_buying_date__c = today.addDays(-5);
        C2.Departing_Date__c = today.addDays(-5);
        C2.Departing_Flight_Number__c = 'aa';
        C2.Email_Address__c = 'ethan1688.lin@gmail.com';
        insert C2;

        Customer_Satisfaction_Surveys__c C3 = new Customer_Satisfaction_Surveys__c();
        C3.Survey_Type__c = 'Flight experience';
        C3.Date_of_Birth__c = Date.newInstance(2000, 10, 18);
        C3.Booking_class__c = 'J';
        C3.Ticket_buying_date__c = today.addDays(-5);
        C3.Departing_Date__c = today.addDays(-5);
        C3.Departing_Flight_Number__c = 'aa';
        C3.Email_Address__c = 'ethan1688.lin@gmail.com';
        insert C3;

        Customer_Satisfaction_Surveys__c C4 = new Customer_Satisfaction_Surveys__c();
        C4.Survey_Type__c = 'Flight experience';
        C4.Date_of_Birth__c = Date.newInstance(2000, 10, 18);
        C4.Booking_class__c = 'Y';
        C4.Ticket_buying_date__c = today.addDays(-5);
        C4.Departing_Date__c = today.addDays(-5);
        C4.Departing_Flight_Number__c = 'aa';
        C4.Email_Address__c = 'ethan1688.lin@gmail.com';
        insert C4;

        Survey_URL__c S1 = new Survey_URL__c();
        S1.Name = 'Hello';
        S1.Used__c = false;
        S1.Survey_Type__c = 'Ticket buying experience';
        S1.Link__c = 'Hello';
        S1.Unique_Expired_Date__c = today.addDays(100);
        insert S1;

        Survey_URL__c S2 = new Survey_URL__c();
        S2.Name = 'Hello2';
        S2.Used__c = false;
        S2.Survey_Type__c = 'Flight experience';
        S2.Link__c = 'Hello2';
        S2.Unique_Expired_Date__c = today.addDays(100);
        insert S2;

        Survey_URL__c S3 = new Survey_URL__c();
        S3.Name = 'Hello3';
        S3.Used__c = false;
        S3.Survey_Type__c = 'Flight experience';
        S3.Link__c = 'Hello3';
        S3.Unique_Expired_Date__c = today.addDays(100);
        insert S3;

        Survey_URL__c S4 = new Survey_URL__c();
        S4.Name = 'Hello4';
        S4.Used__c = false;
        S4.Survey_Type__c = 'Ticket buying experience';
        S4.Link__c = 'Hello4';
        S4.Unique_Expired_Date__c = today.addDays(100);
        insert S4;

        Survey_URL__c S5 = new Survey_URL__c();
        S5.Name = 'Hello5';
        S5.Used__c = false;
        S5.Survey_Type__c = 'Ticket buying experience';
        S5.Link__c = 'Hello5';
        S5.Unique_Expired_Date__c = today.addDays(100);
        insert S5;

        Survey_URL__c S6 = new Survey_URL__c();
        S6.Name = 'Hello6';
        S6.Used__c = false;
        S6.Survey_Type__c = 'Ticket buying experience';
        S6.Link__c = 'Hello6';
        S6.Unique_Expired_Date__c = today.addDays(100);
        insert S6;

        Survey_URL__c S7 = new Survey_URL__c();
        S7.Name = 'Hello7';
        S7.Used__c = false;
        S7.Survey_Type__c = 'Ticket buying experience';
        S7.Link__c = 'Hello7';
        S7.Unique_Expired_Date__c = today.addDays(100);
        insert S7;

        Lucky_Draw_Setting__c L = new Lucky_Draw_Setting__c();
        L.Drawing_Start_Date__c = today.addDays(-10);
        L.Drawing_End_Date__c = today.addDays(10);
        L.First_Class_Delivery_Rate__c = 100;
        L.Other_Delivery_Rate__c = 100;
        insert L;

        Flight_Survey_Setting__c F = new Flight_Survey_Setting__c();
        F.LuckyDrawSettingID__c = L.Id;
        F.Name = 'aa';
        F.Departing_Filght_Number_Rate__c = 100;
        insert F;
    }
    
    static testMethod void test1() 
    {
        Test.StartTest();
        
        SchedulableContext sc = null;
        ScheduleSendSurveyEDM sss = new ScheduleSendSurveyEDM();
        sss.execute(sc);
        
        BatchSendEDM batch = new BatchSendEDM();
        Database.executeBatch(batch);
        
        Test.StopTest();
    }
}