force-app/main/default/objects/Customer_Satisfaction_Surveys__c/Customer_Satisfaction_Surveys__c.object-meta.xml
<CustomObject>
    <label>Customer Satisfaction Surveys</label>
    <nameField>
        <displayFormat>CSS{YYYY}{MM}{00000000}</displayFormat>
        <label>Customer Satisfaction Surveys No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Satisfaction Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Draw__c.field-meta.xml
<CustomField>
    <fullName>Draw__c</fullName>
    <defaultValue>false</defaultValue>
    <description>中獎</description>
    <label>Draw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Drawing_No__c.field-meta.xml
<CustomField>
    <fullName>Drawing_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawing No.</label>
    <referenceTo>Lucky_Draw_Setting__c</referenceTo>
    <relationshipLabel>Customer Satisfaction Surveys</relationshipLabel>
    <relationshipName>Customer_Satisfaction_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Lucky_No__c.field-meta.xml
<CustomField>
    <fullName>Lucky_No__c</fullName>
    <label>Lucky No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Lucky_No_Flight__c.field-meta.xml
<CustomField>
    <fullName>Lucky_No_Flight__c</fullName>
    <label>Lucky No (Flight)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Lucky_No_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Lucky_No_Ticket__c</fullName>
    <label>Lucky No (Ticket)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Survey_Completed__c.field-meta.xml
<CustomField>
    <fullName>Survey_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Survey_Type__c.field-meta.xml
<CustomField>
    <fullName>Survey_Type__c</fullName>
    <label>Survey Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ticket buying experience</fullName>
            </value>
            <value>
                <fullName>Flight experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lucky_Draw_Setting__c/Lucky_Draw_Setting__c.object-meta.xml
<CustomObject>
    <label>Lucky Draw Setting</label>
    <nameField>
        <label>Lucky Draw Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lucky Draw Setting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lucky_Draw_Setting__c/fields/Draw__c.field-meta.xml
<CustomField>
    <fullName>Draw__c</fullName>
    <defaultValue>false</defaultValue>
    <description>已開獎</description>
    <inlineHelpText>已開獎</inlineHelpText>
    <label>Draw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lucky_Draw_Setting__c/fields/Draw_Date__c.field-meta.xml
<CustomField>
    <fullName>Draw_Date__c</fullName>
    <description>開獎日期</description>
    <inlineHelpText>開獎日期</inlineHelpText>
    <label>Draw Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Batch_LuckyDraw.cls
public class Batch_LuckyDraw implements Database.Batchable<sObject>, Database.Stateful{
    public Id recordId {set;get;}
    public final String mode {set;get;}
    public Integer luckyNumber = 0;
    public Integer luckyNumber_TICKET = 0;
    public Integer luckyNumber_FLIGHT = 0;

    public Batch_LuckyDraw(Id recordId, String mode)
    {
        this.recordId = recordId;
        this.mode = mode;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) { 
        Lucky_Draw_Setting__c record = [SELECT Id, Draw_Date__c FROM Lucky_Draw_Setting__c WHERE Id =: recordId LIMIT 1];
        if(record.Draw_Date__c < Date.today()) {
            return NULL;
        }
        return Database.getQueryLocator([SELECT Id, Lucky_No__c, Lucky_No_Ticket__c, Lucky_No_Flight__c, Draw__c, Survey_Type__c FROM Customer_Satisfaction_Surveys__c WHERE Drawing_No__c =: recordId AND Survey_Completed__c = true]);
    }

    public void execute(Database.BatchableContext bc, List<Customer_Satisfaction_Surveys__c> participants) {
        if(mode == 'assign') {
            for(Customer_Satisfaction_Surveys__c participant : participants) {
                if(participant.Survey_Type__c == 'Ticket buying experience') {
                    participant.Lucky_No_Ticket__c = luckyNumber_TICKET;
                    luckyNumber_TICKET++;
                } else if(participant.Survey_Type__c == 'Flight experience') {
                    participant.Lucky_No_Flight__c = luckyNumber_FLIGHT;
                    luckyNumber_FLIGHT++;
                }
                participant.Lucky_No__c = luckyNumber;
                luckyNumber++;
            }
        } else if(mode == 'save') {
            for(Customer_Satisfaction_Surveys__c participant : participants) {
                participant.Draw__c = true;
            }
        } else if(mode == 'unsave') {
            for(Customer_Satisfaction_Surveys__c participant : participants) {
                participant.Draw__c = false;
            }
        }
        UPDATE participants;
    }

    public void finish(Database.BatchableContext bc) { 
		System.debug(luckyNumber);
    }
}