force-app/main/default/objects/Customer_Satisfaction_Surveys__c/Customer_Satisfaction_Surveys__c.object-meta.xml
<CustomObject>
    <label>Customer Satisfaction Surveys</label>
    <nameField>
        <displayFormat>CSS{YYYY}{MM}{00000000}</displayFormat>
        <label>Customer Satisfaction Surveys No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Satisfaction Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Booking_class__c.field-meta.xml
<CustomField>
    <fullName>Booking_class__c</fullName>
    <label>Booking class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Draw__c.field-meta.xml
<CustomField>
    <fullName>Draw__c</fullName>
    <defaultValue>false</defaultValue>
    <description>中獎</description>
    <label>Draw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Drawing_No__c.field-meta.xml
<CustomField>
    <fullName>Drawing_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawing No.</label>
    <referenceTo>Lucky_Draw_Setting__c</referenceTo>
    <relationshipLabel>Customer Satisfaction Surveys</relationshipLabel>
    <relationshipName>Customer_Satisfaction_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Lucky_No__c.field-meta.xml
<CustomField>
    <fullName>Lucky_No__c</fullName>
    <label>Lucky No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Lucky_No_Flight__c.field-meta.xml
<CustomField>
    <fullName>Lucky_No_Flight__c</fullName>
    <label>Lucky No (Flight)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Lucky_No_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Lucky_No_Ticket__c</fullName>
    <label>Lucky No (Ticket)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Survey_Completed__c.field-meta.xml
<CustomField>
    <fullName>Survey_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Satisfaction_Surveys__c/fields/Survey_Type__c.field-meta.xml
<CustomField>
    <fullName>Survey_Type__c</fullName>
    <label>Survey Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ticket buying experience</fullName>
            </value>
            <value>
                <fullName>Flight experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lucky_Draw_Setting__c/Lucky_Draw_Setting__c.object-meta.xml
<CustomObject>
    <label>Lucky Draw Setting</label>
    <nameField>
        <label>Lucky Draw Setting</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lucky Draw Setting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lucky_Draw_Setting__c/fields/Draw__c.field-meta.xml
<CustomField>
    <fullName>Draw__c</fullName>
    <defaultValue>false</defaultValue>
    <description>已開獎</description>
    <inlineHelpText>已開獎</inlineHelpText>
    <label>Draw</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lucky_Draw_Setting__c/fields/Draw_Date__c.field-meta.xml
<CustomField>
    <fullName>Draw_Date__c</fullName>
    <description>開獎日期</description>
    <inlineHelpText>開獎日期</inlineHelpText>
    <label>Draw Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prize__c/Prize__c.object-meta.xml
<CustomObject>
    <description>活動獎項設定</description>
    <label>Prize</label>
    <nameField>
        <label>No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prizes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Prize__c/fields/Drawing_No__c.field-meta.xml
<CustomField>
    <fullName>Drawing_No__c</fullName>
    <label>Drawing No.</label>
    <referenceTo>Lucky_Draw_Setting__c</referenceTo>
    <relationshipLabel>Prizes</relationshipLabel>
    <relationshipName>Prize</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Prize__c/fields/Prize_Amount__c.field-meta.xml
<CustomField>
    <fullName>Prize_Amount__c</fullName>
    <label>Prize Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prize__c/fields/Prize_Name__c.field-meta.xml
<CustomField>
    <fullName>Prize_Name__c</fullName>
    <label>Prize Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prize__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Flight experience</fullName>
            </value>
            <value>
                <fullName>Ticket buying experience</fullName>
            </value>
            <value>
                <fullName>Ticket buying experience &amp; Flight experience</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LuckyDraw_Test.cls
@isTest
public class LuckyDraw_Test {
    @testSetup 
    static void setup() {
        Lucky_Draw_Setting__c luckyDraw = new Lucky_Draw_Setting__c();
        INSERT luckyDraw;
        Customer_Satisfaction_Surveys__c survey1 = new Customer_Satisfaction_Surveys__c();
        survey1.Drawing_No__c = luckyDraw.Id;
        survey1.Survey_Type__c = 'Ticket buying experience';
        survey1.Booking_class__c = 'Aaron';
        survey1.Survey_Completed__c = true;
        INSERT survey1;
        
        Customer_Satisfaction_Surveys__c survey2 = new Customer_Satisfaction_Surveys__c();
        survey2.Drawing_No__c = luckyDraw.Id;
        survey2.Survey_Type__c = 'Flight experience';
        survey2.Booking_class__c = 'Aaron';
        survey2.Survey_Completed__c = true;
        INSERT survey2;
        
        Prize__c prize1 = new Prize__c();
        prize1.Type__c = 'Ticket buying experience';
        prize1.Prize_Amount__c = 1;
        prize1.Name = 'Aaron';
        prize1.Prize_Name__c = 'Aaron';
        prize1.Unit__c = 'cm';
        prize1.Drawing_No__c = luckyDraw.Id;
        INSERT prize1;
        
        Prize__c prize2 = new Prize__c();
        prize2.Type__c = 'Flight experience';
        prize2.Prize_Amount__c = 1;
        prize2.Name = 'Aaron';
        prize2.Prize_Name__c = 'Aaron';
        prize2.Unit__c = 'cm';
        prize2.Drawing_No__c = luckyDraw.Id;
        INSERT prize2;
    }
    
    public static testMethod void luckyDraw_test() {
        Test.startTest();
		Lucky_Draw_Setting__c luckyDraw = [SELECT Id, Draw_Date__c FROM Lucky_Draw_Setting__c LIMIT 1];
        luckyDraw.Draw_Date__c = Date.today();
        UPDATE luckyDraw;
        Test.stopTest();
    }
    
    public static testMethod void luckyDrawController_test() {
        Lucky_Draw_Setting__c luckyDraw = [SELECT Id, Draw_Date__c FROM Lucky_Draw_Setting__c LIMIT 1];
        luckyDraw.Draw_Date__c = Date.today();
        UPDATE luckyDraw;
        List<Customer_Satisfaction_Surveys__c> participants = [SELECT Id, Lucky_No__c, Lucky_No_Ticket__c, Lucky_No_Flight__c, Draw__c, Survey_Type__c FROM Customer_Satisfaction_Surveys__c WHERE Drawing_No__c =: luckyDraw.Id AND Survey_Completed__c = true];
        Integer luckyNumber = 0;
        Integer luckyNumber_TICKET = 0;
        Integer luckyNumber_FLIGHT = 0;
        for(Customer_Satisfaction_Surveys__c participant : participants) {
            if(participant.Survey_Type__c == 'Ticket buying experience') {
                participant.Lucky_No_Ticket__c = luckyNumber_TICKET;
                luckyNumber_TICKET++;
            } else if(participant.Survey_Type__c == 'Flight experience') {
                participant.Lucky_No_Flight__c = luckyNumber_FLIGHT;
                luckyNumber_FLIGHT++;
            }
            participant.Lucky_No__c = luckyNumber;
            luckyNumber++;
        }
        UPDATE participants;
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(luckyDraw);
        LuckyDrawController  obj = new LuckyDrawController(sc);
		obj.draw();
        obj.save();
        obj.cancel();
        Test.stopTest();
    }
}