force-app/main/default/objects/TravellerInfo__c/TravellerInfo__c.object-meta.xml
<CustomObject>
    <description>B2B平台 C5作業PDF輸出數據、C1~C4資料暫存(Search PNR)</description>
    <label>TravellerInfo</label>
    <nameField>
        <label>travellerInfo名稱</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TravellerInfos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TravellerInfo__c/fields/BookingClass__c.field-meta.xml
<CustomField>
    <fullName>BookingClass__c</fullName>
    <label>BookingClass</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <label>國籍</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <label>出生日期</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/DepartureDate__c.field-meta.xml
<CustomField>
    <fullName>DepartureDate__c</fullName>
    <description>WBS為起飛地當地時區</description>
    <inlineHelpText>WBS為起飛地當地時區</inlineHelpText>
    <label>起飛日期</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/DepartureLocation__c.field-meta.xml
<CustomField>
    <fullName>DepartureLocation__c</fullName>
    <label>起飛地</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/DepartureLocationGMTLocal__c.field-meta.xml
<CustomField>
    <fullName>DepartureLocationGMTLocal__c</fullName>
    <description>僅DB存取用</description>
    <formula>DATETIMEVALUE(
    TEXT(
        2000 + VALUE(MID(DepartureDate__c, 5, 2))
    ) &amp; &quot;-&quot; &amp;
    RIGHT(&quot;0&quot; &amp; TEXT(VALUE(MID(DepartureDate__c, 3, 2))), 2) &amp; &quot;-&quot; &amp;
    RIGHT(&quot;0&quot; &amp; TEXT(VALUE(MID(DepartureDate__c, 1, 2))), 2) &amp; &quot; &quot; &amp;
    LEFT(DepartureTime__c, 2) &amp; &quot;:&quot; &amp;
    RIGHT(DepartureTime__c, 2) &amp; &quot;:00&quot;
)</formula>
    <inlineHelpText>僅DB存取用</inlineHelpText>
    <label>起飛日期(當地時間)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>目的地</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/firstName__c.field-meta.xml
<CustomField>
    <fullName>firstName__c</fullName>
    <label>名</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <label>航班號碼</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/gender__c.field-meta.xml
<CustomField>
    <fullName>gender__c</fullName>
    <description>M=male
F= female
MI=male infant
FI=female infant</description>
    <label>性別</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>姓</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/PassengerType__c.field-meta.xml
<CustomField>
    <fullName>PassengerType__c</fullName>
    <description>ADT(成人:12歲以上)、CHD(小孩:12至2歲)、INF(嬰兒:2歲以下)</description>
    <label>旅客類型</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/PassengerTypeOrderBy__c.field-meta.xml
<CustomField>
    <fullName>PassengerTypeOrderBy__c</fullName>
    <description>CASE(PassengerType__c,
  &quot;ADT&quot;, 1,
  &quot;CHD&quot;, 2,
  &quot;INF&quot;, 3,
  4
)</description>
    <formula>CASE(PassengerType__c,
  &quot;ADT&quot;, 1,
  &quot;CHD&quot;, 2,
  &quot;INF&quot;, 3,
  4
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>旅客類型(排序用)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/PassportExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>PassportExpiryDate__c</fullName>
    <label>護照到期日</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/PassportIssuingCountry__c.field-meta.xml
<CustomField>
    <fullName>PassportIssuingCountry__c</fullName>
    <label>護照發照國家</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/PassportNumber__c.field-meta.xml
<CustomField>
    <fullName>PassportNumber__c</fullName>
    <label>護照號碼</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <label>訂位代號</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/PTOrderBy__c.field-meta.xml
<CustomField>
    <fullName>PTOrderBy__c</fullName>
    <formula>IF(
  ISBLANK(PT__c) || NOT(ISNUMBER(PT__c)),
  NULL,
  VALUE(PT__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>訂位代號編號(排序用)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/Seat__c.field-meta.xml
<CustomField>
    <fullName>Seat__c</fullName>
    <label>座位位置</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/title__c.field-meta.xml
<CustomField>
    <fullName>title__c</fullName>
    <label>稱謂</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/US_Bound__c.field-meta.xml
<CustomField>
    <fullName>US_Bound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>美國線</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/USACity__c.field-meta.xml
<CustomField>
    <fullName>USACity__c</fullName>
    <label>美國城市</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/USAEmergencyContactName__c.field-meta.xml
<CustomField>
    <fullName>USAEmergencyContactName__c</fullName>
    <label>美國緊急聯絡人姓名</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/USAEmergencyContactNationality__c.field-meta.xml
<CustomField>
    <fullName>USAEmergencyContactNationality__c</fullName>
    <label>美國緊急聯絡人國籍</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/USAEmergencyContactPhone__c.field-meta.xml
<CustomField>
    <fullName>USAEmergencyContactPhone__c</fullName>
    <label>美國緊急連絡人電話</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/USAState__c.field-meta.xml
<CustomField>
    <fullName>USAState__c</fullName>
    <label>美國州別</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/USAStreet__c.field-meta.xml
<CustomField>
    <fullName>USAStreet__c</fullName>
    <description>美國線專用</description>
    <label>美國街道</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/USAZipCode__c.field-meta.xml
<CustomField>
    <fullName>USAZipCode__c</fullName>
    <label>美國郵遞區號</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/VisaExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>VisaExpiryDate__c</fullName>
    <label>簽證到期日</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/VisaIssuingCountry__c.field-meta.xml
<CustomField>
    <fullName>VisaIssuingCountry__c</fullName>
    <label>簽證適用國家</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TravellerInfo__c/fields/VisaNumber__c.field-meta.xml
<CustomField>
    <fullName>VisaNumber__c</fullName>
    <label>簽證號碼</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TravellerRepository.cls
/**
 * @description Traveller Repository Implementation
 * @author STARLUX Development Team
 * @date 2024
 */
public class TravellerRepository implements ITravellerRepository {
    
    /**
     * @description Find travellers based on query criteria
     * @param query Repository query parameters
     * @return List of traveller records
     */
    public List<TravellerInfo__c> findTravellers(RepositoryQuery query) {
        try {
            if (query == null || !query.isValid()) {
                return new List<TravellerInfo__c>();
            }
            
            // Build dynamic SOQL query
            String soqlQuery = buildSOQLQuery(query);
            System.debug('Executing SOQL: ' + soqlQuery);
            
            return Database.query(soqlQuery);
            
        } catch (Exception e) {
            System.debug('Error in findTravellers: ' + e.getMessage());
            return new List<TravellerInfo__c>();
        }
    }
    
    /**
     * @description Find travellers by seat assignment
     * @param seatCode Seat code
     * @return List of travellers assigned to seat
     */
    public List<TravellerInfo__c> findTravellersBySeat(String seatCode) {
        try {
            if (String.isBlank(seatCode)) {
                return new List<TravellerInfo__c>();
            }
            
            return [
                SELECT Id, PNR__c, 
                       LastName__c, FirstName__c, Title__c, Gender__c,
                       Country__c, DateOfBirth__c, PassengerType__c,
                       PassportNumber__c, PassportExpiryDate__c, PassportIssuingCountry__c,
                       DepartureLocation__c, US_Bound__c, Seat__c,
                       VisaNumber__c, VisaExpiryDate__c, VisaIssuingCountry__c,
                       USAStreet__c, USACity__c, USAState__c, USAZipCode__c,
                       USAEmergencyContactName__c, USAEmergencyContactNationality__c, USAEmergencyContactPhone__c
                FROM TravellerInfo__c 
                WHERE Seat__c = :seatCode
                ORDER BY PTOrderBy__c ASC, PassengerTypeOrderBy__c ASC
            ];
            
        } catch (Exception e) {
            System.debug('Error in findTravellersBySeat: ' + e.getMessage());
            return new List<TravellerInfo__c>();
        }
    }
    
    /**
     * @description Update traveller records
     * @param travellers List of travellers to update
     * @return Success status
     */
    public Boolean updateTravellers(List<TravellerInfo__c> travellers) {
        try {
            if (travellers == null || travellers.isEmpty()) {
                return false;
            }
            
            update travellers;
            return true;
            
        } catch (Exception e) {
            System.debug('Error in updateTravellers: ' + e.getMessage());
            return false;
        }
    }
    
    /**
     * @description Create new traveller records
     * @param travellers List of travellers to create
     * @return Success status
     */
    public Boolean createTravellers(List<TravellerInfo__c> travellers) {
        try {
            if (travellers == null || travellers.isEmpty()) {
                return false;
            }
            
            insert travellers;
            return true;
            
        } catch (Exception e) {
            System.debug('Error in createTravellers: ' + e.getMessage());
            return false;
        }
    }
    
    /**
     * @description Delete traveller records
     * @param travellers List of travellers to delete
     * @return Success status
     */
    public Boolean deleteTravellers(List<TravellerInfo__c> travellers) {
        try {
            if (travellers == null || travellers.isEmpty()) {
                return false;
            }
            
            delete travellers;
            return true;
            
        } catch (Exception e) {
            System.debug('Error in deleteTravellers: ' + e.getMessage());
            return false;
        }
    }
    
    /**
     * @description Build SOQL query from repository query parameters
     * @param query Repository query
     * @return SOQL query string
     */
    private String buildSOQLQuery(RepositoryQuery query) {
        // Base SELECT clause - using correct field names from SeatSelectionController
        String selectClause = 'SELECT Id, PNR__c, FlightNumber__c, ' +
                             'LastName__c, FirstName__c, Title__c, Gender__c, ' +
                             'Country__c, DateOfBirth__c, PassengerType__c, ' +
                             'PassportNumber__c, PassportExpiryDate__c, PassportIssuingCountry__c, ' +
                             'DepartureLocation__c, Destination__c, US_Bound__c, Seat__c, ' +
                             'VisaNumber__c, VisaExpiryDate__c, VisaIssuingCountry__c, ' +
                             'USAStreet__c, USACity__c, USAState__c, USAZipCode__c, ' +
                             'USAEmergencyContactName__c, USAEmergencyContactNationality__c, USAEmergencyContactPhone__c, ' +
                             'DepartureDate__c, DepartureLocationGMTLocal__c, BookingClass__c, External_ID__c';
        
        String fromClause = 'FROM TravellerInfo__c';
        
        // Build WHERE clause
        List<String> whereConditions = new List<String>();
        
        // Note: Active__c field is not used in SeatSelectionController, removing this condition
        
        // PNR codes condition
        if (query.hasPNRCriteria()) {
            List<String> quotedPNRs = new List<String>();
            for (String pnr : query.pnrCodes) {
                quotedPNRs.add('\'' + String.escapeSingleQuotes(pnr) + '\'');
            }
            whereConditions.add('PNR__c IN (' + String.join(quotedPNRs, ',') + ')');
        }
        
        // External IDs condition
        if (query.hasExternalIdCriteria()) {
            List<String> quotedIds = new List<String>();
            for (String extId : query.externalIds) {
                quotedIds.add('\'' + String.escapeSingleQuotes(extId) + '\'');
            }
            whereConditions.add('External_ID__c IN (' + String.join(quotedIds, ',') + ')');
        }
        
        // Flight criteria - Note: FlightNumber__c is not directly queried in controller's main query
        // Removing this condition as it's not used in the controller pattern
        
        // Date range condition using DepartureLocationGMTLocal__c (matches controller pattern)
        if (query.departureDate != null) {
            DateTime startOfDay = DateTime.newInstance(
                query.departureDate.year(),
                query.departureDate.month(),
                query.departureDate.day(),
                0, 0, 0
            );
            DateTime endOfDay = startOfDay.addDays(1).addSeconds(-1);
            
            whereConditions.add('DepartureLocationGMTLocal__c >= ' + startOfDay.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
            whereConditions.add('DepartureLocationGMTLocal__c <= ' + endOfDay.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
        }
        
        if (String.isNotBlank(query.departureLocation)) {
            whereConditions.add('DepartureLocation__c = \'' + String.escapeSingleQuotes(query.departureLocation) + '\'');
        }
        
        String whereClause = '';
        if (!whereConditions.isEmpty()) {
            whereClause = 'WHERE ' + String.join(whereConditions, ' AND ');
        }
        
        // Build ORDER BY clause - matching controller's ordering
        String orderByClause = '';
        if (String.isNotBlank(query.orderBy)) {
            orderByClause = 'ORDER BY ' + query.orderBy;
        } else {
            orderByClause = 'ORDER BY PTOrderBy__c ASC, PassengerTypeOrderBy__c ASC'; // Matches controller pattern
        }
        
        // Build LIMIT clause
        String limitClause = '';
        if (query.limitSize != null && query.limitSize > 0) {
            limitClause = 'LIMIT ' + query.limitSize;
        }
        
        // Combine all clauses
        List<String> queryParts = new List<String>{selectClause, fromClause};
        
        if (String.isNotBlank(whereClause)) {
            queryParts.add(whereClause);
        }
        
        if (String.isNotBlank(orderByClause)) {
            queryParts.add(orderByClause);
        }
        
        if (String.isNotBlank(limitClause)) {
            queryParts.add(limitClause);
        }
        
        return String.join(queryParts, ' ');
    }
    
    /**
     * @description Get traveller count for query (without LIMIT)
     * @param query Repository query parameters
     * @return Count of matching records
     */
    public Integer getTravellerCount(RepositoryQuery query) {
        try {
            if (query == null) {
                return 0;
            }
            
            // Build count query (similar to main query but with COUNT())
            String countQuery = buildCountQuery(query);
            System.debug('Executing count SOQL: ' + countQuery);
            
            return Database.countQuery(countQuery);
            
        } catch (Exception e) {
            System.debug('Error in getTravellerCount: ' + e.getMessage());
            return 0;
        }
    }
    
    /**
     * @description Build COUNT SOQL query
     * @param query Repository query
     * @return COUNT SOQL query string
     */
    private String buildCountQuery(RepositoryQuery query) {
        String selectClause = 'SELECT COUNT()';
        String fromClause = 'FROM TravellerInfo__c';
        
        // Build WHERE clause (same as main query)
        List<String> whereConditions = new List<String>();
        
        // Note: Active__c field is not used in SeatSelectionController, removing this condition
        
        if (query.hasPNRCriteria()) {
            List<String> quotedPNRs = new List<String>();
            for (String pnr : query.pnrCodes) {
                quotedPNRs.add('\'' + String.escapeSingleQuotes(pnr) + '\'');
            }
            whereConditions.add('PNR__c IN (' + String.join(quotedPNRs, ',') + ')');
        }
        
        if (query.hasExternalIdCriteria()) {
            List<String> quotedIds = new List<String>();
            for (String extId : query.externalIds) {
                quotedIds.add('\'' + String.escapeSingleQuotes(extId) + '\'');
            }
            whereConditions.add('External_ID__c IN (' + String.join(quotedIds, ',') + ')');
        }
        
        // Date range condition using DepartureLocationGMTLocal__c
        if (query.departureDate != null) {
            DateTime startOfDay = DateTime.newInstance(
                query.departureDate.year(),
                query.departureDate.month(),
                query.departureDate.day(),
                0, 0, 0
            );
            DateTime endOfDay = startOfDay.addDays(1).addSeconds(-1);
            
            whereConditions.add('DepartureLocationGMTLocal__c >= ' + startOfDay.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
            whereConditions.add('DepartureLocationGMTLocal__c <= ' + endOfDay.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
        }
        
        if (String.isNotBlank(query.departureLocation)) {
            whereConditions.add('DepartureLocation__c = \'' + String.escapeSingleQuotes(query.departureLocation) + '\'');
        }
        
        String whereClause = '';
        if (!whereConditions.isEmpty()) {
            whereClause = 'WHERE ' + String.join(whereConditions, ' AND ');
        }
        
        List<String> queryParts = new List<String>{selectClause, fromClause};
        if (String.isNotBlank(whereClause)) {
            queryParts.add(whereClause);
        }
        
        return String.join(queryParts, ' ');
    }
}