force-app/main/default/objects/Quota_Manage__c/Quota_Manage__c.object-meta.xml
<CustomObject>
    <description>額度管理主檔(初始額度)</description>
    <label>Quota Manage</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota Manage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota_Manage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quota Manage</relationshipLabel>
    <relationshipName>Account_Quota_Manage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>AND(
TODAY() &gt; Valid_Date__c,
TODAY() &lt; Expiry_Date__c 
)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Discount_Code__c.field-meta.xml
<CustomField>
    <fullName>Discount_Code__c</fullName>
    <label>Discount Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>RG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Quota_Remain__c.field-meta.xml
<CustomField>
    <fullName>Quota_Remain__c</fullName>
    <description>額度(剩餘)</description>
    <formula>Quota_Total__c-Quota_Used__c-Quota_Transit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>額度(剩餘)</inlineHelpText>
    <label>Quota(Remain)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Quota_Total__c.field-meta.xml
<CustomField>
    <fullName>Quota_Total__c</fullName>
    <description>額度(總額度)</description>
    <formula>Quota_Initial__c+Quota_Append__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>額度(總額度)</inlineHelpText>
    <label>Quota(Total)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Quota_Transit__c.field-meta.xml
<CustomField>
    <fullName>Quota_Transit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>在途額度</description>
    <label>Quota(Transit)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Quota_Used__c.field-meta.xml
<CustomField>
    <fullName>Quota_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quota(Used)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExternalTicketQuotaStatisticsController.cls
public without sharing class ExternalTicketQuotaStatisticsController {
    public String companyType { get; set; }
    public String departmentCode { get; set; }
    public String loginCode { get; set; }

    public List<String> discountCodes { get; set; }
    public List<String> discountRows { get; set; }
    public Map<String, Map<String, QuotaData>> quotaMap { get; set; }

    public ExternalTicketQuotaStatisticsController() {
        // 讀取 Cookie
        Map<String, Cookie> ck = ApexPages.currentPage().getCookies();
        if (ck.containsKey('Company_type__c'))
            companyType = EncodingUtil.urlDecode(ck.get('Company_type__c').getValue(), 'UTF-8');
        if (ck.containsKey('Department_Code__c'))
            departmentCode = EncodingUtil.urlDecode(ck.get('Department_Code__c').getValue(), 'UTF-8');
        if (ck.containsKey('Login_Code__c'))
            loginCode = EncodingUtil.urlDecode(ck.get('Login_Code__c').getValue(), 'UTF-8');

        // 設定橫向欄位（X 軸）與縱向欄位（Y 軸）
        discountCodes = new List<String>{ 'AD', 'DM', 'RG' ,'GE' ,'ID','DG'};
        discountRows = new List<String>{ '00', '50', '75', '90' };

        quotaMap = new Map<String, Map<String, QuotaData>>();

        // 初始化所有 row × code，預設為 '-'
        for (String row : discountRows) {
            Map<String, QuotaData> rowMap = new Map<String, QuotaData>();
            for (String code : discountCodes) {
                rowMap.put(code, new QuotaData('-', '-', '-', '-'));
            }
            quotaMap.put(row, rowMap);
        }

        try {
            // 查詢 Account
            Account acc = [
                SELECT Id ,ParentId
                FROM Account
                WHERE Company_type__c = :companyType
                  AND Department_Code__c = :departmentCode
                LIMIT 1
            ];
            // 查詢 子Account 若無則搜尋自己
            String targetIds;
            if(acc.ParentId!=null)
            {
            	targetIds = acc.ParentId;
            }else{
                targetIds = acc.Id;
            }
			
            System.debug(targetIds);
            // 查詢 Quota_Manage__c 並覆蓋初始化資料
            for (Quota_Manage__c qm : [
                SELECT Discount_Code__c, Quota_Total__c, Quota_Used__c, Quota_Remain__c, Discount__c, Quota_Transit__c
                FROM Quota_Manage__c
                WHERE Account__c = :targetIds
                  AND Active__c = TRUE
            ]) {
                if (quotaMap.containsKey(qm.Discount__c) &&
                    quotaMap.get(qm.Discount__c).containsKey(qm.Discount_Code__c)) {
                    quotaMap.get(qm.Discount__c).put(
                        qm.Discount_Code__c,
                        new QuotaData(
                            String.valueOf(qm.Quota_Total__c),
                            String.valueOf(qm.Quota_Transit__c),
                            String.valueOf(qm.Quota_Used__c),
                            String.valueOf(qm.Quota_Remain__c)
                        )
                    );
                }
            }
        } catch (Exception e) {
            System.debug('查詢 Quota 資料時發生錯誤: ' + e.getMessage());
        }
    }
    
	//沒有Cookie則導回首頁
    public PageReference ensureAuth() {
        if (String.isBlank(companyType) || String.isBlank(departmentCode) || String.isBlank(loginCode)) {
            PageReference p = Page.ExternalTicketLogin;
            p.setRedirect(true);
            return p; // 直接中止本頁渲染並跳轉
        }
        return null; // 繼續渲染本頁
    }
    
    // 登出
    public PageReference logout() {
        ExternalTicketLoginUtility.clearAccountLoginCookie();
        PageReference p = Page.ExternalTicketLogin;
        p.getParameters().put('toast', 'logout');
        p.setRedirect(true);
        return p;
    }

    // QuotaData 結構
    public class QuotaData {
        public String total { get; set; }
        public String transit { get; set; }
        public String used { get; set; }
        public String remain { get; set; }
        public QuotaData(String t, String tr, String u, String r) {
            total = t; 
            transit = tr;
            used = u; 
            remain = r;
        }
    }
    public static void fakeMethod() {
        Integer i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
    }
 
}