force-app/main/default/objects/Interface_Configuration__mdt/Interface_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Interface Configuration</label>
    <pluralLabel>Interface Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Interface_Configuration__mdt/fields/Object_to_Display__c.field-meta.xml
<CustomField>
    <fullName>Object_to_Display__c</fullName>
    <label>Object to Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Kaltura</fullName>
            </value>
            <value>
                <fullName>DIH</fullName>
                <default>true</default>
                <label>DIH</label>
            </value>
            <value>
                <fullName>CRANE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/APIEndPointDesignAttributes.cls
global class APIEndPointDesignAttributes extends VisualEditor.DynamicPickList {
    global override VisualEditor.DataRow getDefaultValue() {
        VisualEditor.DataRow defaultValue = new VisualEditor.DataRow('None', 'None');
        return defaultValue;
    }

    global override VisualEditor.DynamicPickListRows getValues() {
        return getIntegrationComponentPickList();
    }

    private VisualEditor.DynamicPickListRows getIntegrationComponentPickList() {
        VisualEditor.DynamicPickListRows listForSelection = new VisualEditor.DynamicPickListRows();
        String queryCondition = 'Object_to_Display__c  =' + '\'' + 'CRANE' + '\'';
        List<Interface_Configuration__mdt> customMetadataList = lib_UtilityHelper.getSObjectRecords('Interface_Configuration__mdt', queryCondition, false);
        for (Interface_Configuration__mdt pickVal : customMetadataList) {
            listForSelection.addRow(new VisualEditor.DataRow((String)pickVal.Label, (String) pickVal.DeveloperName));
        }
        return listForSelection;
    }
}