force-app/main/default/objects/Work_Hour__c/Work_Hour__c.object-meta.xml
<CustomObject>
    <label>Work Hour</label>
    <nameField>
        <label>Work_Hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Hour__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Work_Hour__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/Chatbot_Test.cls
@isTest(SeeAllData=false)
public class Chatbot_Test {
    public static testMethod Void testAll() {
        Chatbot_CalloutClass.fakeMethod();
        APT_RestAPI.fakeMethod();
        CaseTriggerHandler.fakeMethod();
        Chatbot_Chat.fakeMethod();
        Schedule_EndCalls.fakeMethod();
        ResponseResultModel.fakeMethod();
        ApexSpecial_Case.fakeMethod();
        Chatbot_Chat_For_S.fakeMethod();
        ApexCase.fakeMethod();
        Chatbot_Home.fakeMethod();
        Chatbot_Individual.fakeMethod();
        Chatbot_KM.fakeMethod();
        Chatbot_Message.fakeMethod();
    }
    
    public static testMethod Void testTrigger() {
        Case c = new Case();
        insert c;
        Work_Hour__c w = new Work_Hour__c();
        w.Start_Time__c = System.now().time();
        w.End_Time__c = System.now().time();
        insert w;
    }
}