force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Booking_Reference_PNR__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference_PNR__c</fullName>
    <description>Temp PNR by B2B</description>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Allocated_Seats__c</fullName>
    <label>Final Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Original_Sat__c.field-meta.xml
<CustomField>
    <fullName>Original_Sat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Sat</label>
    <referenceTo>Seat_Allocation_and_Ticketing__c</referenceTo>
    <relationshipLabel>Seat Allocations and Ticketings</relationshipLabel>
    <relationshipName>Seat_Allocations_and_Ticketings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Sync_SAT_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Sync_SAT_Error_Message__c</fullName>
    <label>Sync SAT Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Sync_SAT_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_SAT_Status__c</fullName>
    <label>Sync SAT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Total_Seat_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Seat_Sales__c</fullName>
    <label>Total Seat Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReceiveResponseResizePnrApi.cls
@RestResource(urlMapping = '/receive-response/resize-pnr')
global class ReceiveResponseResizePnrApi {
    
    @HttpPost
    global static void resizePnr() {
        RestRequest request = RestContext.request;
        RestResponse response = Restcontext.response;

        ReceiveResponseResizePnrWrapper wrapper = ReceiveResponseResizePnrWrapper.deserializeJson(request.requestBody.toString());

        if (wrapper.isMissingRequiredFields()) {
            response = ResponseUtil.buildErrorRestResponse(response, Constants.MISSING_REQUIRED_FIELD);
            ApiLogger.log(request, response);
            return;
        }
        
        Seat_Allocation_and_Ticketing__c sat = [SELECT Id, Sync_SAT_Status__c, Sync_SAT_Error_Message__c, Booking_Reference_PNR__c, Original_Sat__r.Id, Original_Sat__r.Final_Allocated_Seats__c, Original_Sat__r.Total_Seat_Sales__c FROM Seat_Allocation_and_Ticketing__c WHERE Name =: wrapper.sat_no];
        sat.Sync_SAT_Status__c = wrapper.status;
        sat.Sync_SAT_Error_Message__c = '';
        if (wrapper.pnr != null) sat.Booking_Reference_PNR__c = wrapper.pnr;
        if (wrapper.status == Constants.PICKLIST_STATUS_FAIL) {
            sat.Sync_SAT_Error_Message__c = wrapper.error_message;
        }
        
        if (sat.Original_Sat__c != null) {
            Seat_Allocation_and_Ticketing__c originalSat = new Seat_Allocation_and_Ticketing__c(Id = sat.Original_Sat__r.Id, 
                                                                                                Final_Allocated_Seats__c = sat.Original_Sat__r.Final_Allocated_Seats__c,
                                                                                                Total_Seat_Sales__c = sat.Original_Sat__r.Total_Seat_Sales__c);
            sat.Total_Seat_Sales__c = 0;
            if (originalSat.Final_Allocated_Seats__c < originalSat.Total_Seat_Sales__c) {
                sat.Total_Seat_Sales__c = originalSat.Total_Seat_Sales__c - originalSat.Final_Allocated_Seats__c;
                originalSat.Total_Seat_Sales__c = originalSat.Final_Allocated_Seats__c;
            }

            Database.update(originalSat);  
        }
        
        Database.update(sat);

        response = ResponseUtil.buildSuccessRestResponse(response);
        ApiLogger.log(request, response);
    }

    public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}