force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Allocated_Seats__c</fullName>
    <label>Final Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Total_Seat_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Seat_Sales__c</fullName>
    <label>Total Seat Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QueueableResizePnr.cls
public class QueueableResizePnr implements Queueable, Database.AllowsCallouts {
    private String newSatName;
    private String masterSatName;
    private String pnr;
    private Integer seats;
    private String caseNo;
    //private List<Seat_Allocation_and_Ticketing__c> updateList;

    public QueueableResizePnr(String newSatName, String masterSatName, String pnr, Integer seats, String caseNo) {
        this.newSatName = newSatName;
        this.masterSatName = masterSatName;
        this.pnr = pnr;
        this.seats = seats;
        this.caseNo = caseNo;
        
        /*newSat.Total_Seat_Sales__c = 0;
        
        if (originalSat.Final_Allocated_Seats__c < originalSat.Total_Seat_Sales__c) {
            newSat.Total_Seat_Sales__c = originalSat.Total_Seat_Sales__c - originalSat.Final_Allocated_Seats__c;
            originalSat.Total_Seat_Sales__c = originalSat.Final_Allocated_Seats__c;
        }
        
        this.updateList = new Seat_Allocation_and_Ticketing__c[]{newSat, originalSat};*/
    }

    public void execute(QueueableContext context) {
        MiddlewareUtil.resizePnr(newSatName, masterSatName, pnr, seats, caseNo);

        //update updateList;
    }
}