force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Seat Allocations and Ticketings</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Sales_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Sales_Seats__c</fullName>
    <label>Final Sales Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Tax_Adult__c.field-meta.xml
<CustomField>
    <fullName>Final_Tax_Adult__c</fullName>
    <label>Final Tax (Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Tax_Child__c.field-meta.xml
<CustomField>
    <fullName>Final_Tax_Child__c</fullName>
    <label>Final Tax (Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Tax_Infant__c.field-meta.xml
<CustomField>
    <fullName>Final_Tax_Infant__c</fullName>
    <label>Final Tax (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Adult__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Adult__c</fullName>
    <label>Final Unit Price(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Child__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Child__c</fullName>
    <label>Final Unit Price(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Infant__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Infant__c</fullName>
    <label>Final Unit Price (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Group_Booking_Route__c.field-meta.xml
<CustomField>
    <fullName>Group_Booking_Route__c</fullName>
    <formula>Text(Case_ID__r.Route__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Booking Route</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Tax_Adult__c.field-meta.xml
<CustomField>
    <fullName>Initial_Tax_Adult__c</fullName>
    <label>Initial Tax(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Tax_Child__c.field-meta.xml
<CustomField>
    <fullName>Initial_Tax_Child__c</fullName>
    <label>Initial Tax(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Tax_Infant__c.field-meta.xml
<CustomField>
    <fullName>Initial_Tax_Infant__c</fullName>
    <label>Initial Tax(Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Unit_Price_Adult__c.field-meta.xml
<CustomField>
    <fullName>Initial_Unit_Price_Adult__c</fullName>
    <label>Initial Unit Price(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Unit_Price_Child__c.field-meta.xml
<CustomField>
    <fullName>Initial_Unit_Price_Child__c</fullName>
    <label>Initial Unit Price(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Unit_Price_Infant__c.field-meta.xml
<CustomField>
    <fullName>Initial_Unit_Price_Infant__c</fullName>
    <label>Initial Unit Price (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Not_in_Fare_Table__c.field-meta.xml
<CustomField>
    <fullName>Not_in_Fare_Table__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not in Fare Table</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Not_in_Tax_Table__c.field-meta.xml
<CustomField>
    <fullName>Not_in_Tax_Table__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not in Tax Table</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Tax_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date__c</fullName>
    <label>Tax Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tax_Details__c/Tax_Details__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <displayFormat>TX{YYYY}{MM}{00000000}</displayFormat>
        <label>Tax Details No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Details__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>Route</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TPE-MFM-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-DAD-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-PEN-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-CEB-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-MFM(one-way)</fullName>
            </value>
            <value>
                <fullName>MFM-TPE(one-way)</fullName>
            </value>
            <value>
                <fullName>TPE-DAD(one-way)</fullName>
            </value>
            <value>
                <fullName>DAD-TPE(one-way)</fullName>
            </value>
            <value>
                <fullName>TPE-PEN(one-way)</fullName>
            </value>
            <value>
                <fullName>PEN-TPE(one-way)</fullName>
            </value>
            <value>
                <fullName>TPE-CEB(one-way)</fullName>
            </value>
            <value>
                <fullName>CEB-TPE(one-way)</fullName>
            </value>
            <value>
                <fullName>TPE-BKK-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-OKA-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-FUK-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-KIX-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-SDJ-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-CTS-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-PUS-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-CNX-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-KLO-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-CJU-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-KUL-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-HKD-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-MNL-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-NRT-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-LAX-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-HAN-TPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Details__c/fields/Tax_Amount_Adult__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Adult__c</fullName>
    <label>Tax Amount(Adult)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Details__c/fields/Tax_Amount_Child__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Child__c</fullName>
    <label>Tax Amount(Child)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Details__c/fields/Tax_Amount_Infant__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Infant__c</fullName>
    <label>Tax Amount(Infant)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Details__c/fields/Tax_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date__c</fullName>
    <label>Tax Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ticket_Fare_Rule__c/Ticket_Fare_Rule__c.object-meta.xml
<CustomObject>
    <label>Ticket Fare Rule</label>
    <nameField>
        <displayFormat>TF{YYYY}{MM}{00000000}</displayFormat>
        <label>Ticket Fare Rule No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Fare Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Fare_Rule__c/fields/Departing_Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Departing_Flight_Number__c</fullName>
    <label>Departing Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Fare_Rule__c/fields/Returning_Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Returning_Flight_Number__c</fullName>
    <label>Returning Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateTaxAmount.cls
public class UpdateTaxAmount {
    private static Date currentDate = Date.today();
    
	@InvocableMethod(label='Get Tax Amount')
    public static List<Boolean> getTaxAmount(List<ID> SeatAllocationID) {
        List<Boolean> returnResult = new List<Boolean>();
        
        
        //Query for target Seat Allocation Record 
        List<Seat_Allocation_and_Ticketing__c> newSeatAllocationList = [SELECT Id,Tax_Date__c,Final_Sales_Seats__c,Returning_Flight_Date__c,Departing_Flight_Date__c,CreatedDate,Case_ID__c,Departing_Flight_Number__c,
                                                                        Returning_Flight_Number__c,Group_Booking_Route__c,Initial_Unit_Price_Infant__c,Initial_Unit_Price_Child__c,
                                                                        Initial_Unit_Price_Adult__c,Initial_Tax_Infant__c,Initial_Tax_Child__c,Initial_Tax_Adult__c,
                                                                        Final_Unit_Price_Infant__c,Final_Unit_Price_Child__c,Final_Unit_Price_Adult__c,Final_Tax_Infant__c,
                                                                        Final_Tax_Child__c,Final_Tax_Adult__c,Not_in_Fare_Table__c,Not_in_Tax_Table__c,Case_Id__r.Account.IATA_MSO_Code__c 
                                                                        FROM Seat_Allocation_and_Ticketing__c WHERE Id IN :SeatAllocationID];
        
        Seat_Allocation_and_Ticketing__c newSeatAllocation = newSeatAllocationList[0];
        
       	Date TargetDate = newSeatAllocation.Tax_Date__c;
        String DepartureFlightNo = newSeatAllocation.Departing_Flight_Number__c;
        String ReturningFlightNo = newSeatAllocation.Returning_Flight_Number__c;
        Date DepartingFlightDate = newSeatAllocation.Departing_Flight_Date__c;
        Date ReturningFlightDate = newSeatAllocation.Returning_Flight_Date__c;
        Datetime IssueDateTime = datetime.now();
        Date IssueDate = date.newInstance(IssueDateTime.year(),IssueDateTime.month(),IssueDateTime.day());
        String IATACode = newSeatAllocation.Case_Id__r.Account.IATA_MSO_Code__c;
        Decimal FinalSeats = newSeatAllocation.Final_Sales_Seats__c;
        String Route = newSeatAllocation.Group_Booking_Route__c;
        
        //Query for all applicable Tax Table records
        List<Tax_Details__c> allTaxTables = [SELECT Id,CreatedDate,Tax_Amount_Adult__c,Tax_Amount_Child__c,Tax_Amount_Infant__c,Route__c,Tax_Date__c FROM Tax_Details__c 
                                          WHERE Tax_Date__c >= :currentDate-90];
        
        //Store all Tax Table records in a Map
        Map<String, Tax_Details__c> mapTaxTable = new Map<String, Tax_Details__c>();
        Integer taxCount = 1;
        
        for (Tax_Details__c tax : allTaxTables) {
            String taxKey = 'Tax' + String.valueOf(taxCount);
            mapTaxTable.put(taxKey, tax);
            taxCount += 1;
        }
        
						//Final selected records
                        Ticket_Fare_Rule__c selectedTicketFare = new Ticket_Fare_Rule__c();
                        Tax_Details__c selectedTaxTable = new Tax_Details__c();
                        
                        Decimal extraSurcharge = 0;
                        
                        //All shortlisted records after filtering later on
                        List<Ticket_Fare_Rule__c> allSelectedFares = new List<Ticket_Fare_Rule__c>();
                        List<Tax_Details__c> allSelectedTaxes = new List<Tax_Details__c>();
                        
                        //Check if any record in mapTaxTable matches criteria of newSeatAllocation
                        for (String key : mapTaxTable.keySet()) {
                            Tax_Details__c loopTaxTable = mapTaxTable.get(key);
                            
                            if (loopTaxTable.Route__c == Route && loopTaxTable.Tax_Date__c == TargetDate) { 
                                system.debug('DBG selectedTaxTable: '+loopTaxTable);
                            	allSelectedTaxes.add(loopTaxTable);
                            }
                        }
                        
                        //Sorting allSelectedTaxes based on matching outcomes to determine the right Tax Table record to be used
                        if (allSelectedTaxes.size() > 1) {
                            Datetime latestDate = datetime.newInstance(1990,1,1);
                            Tax_Details__c latestTax = new Tax_Details__c();
                            for (Tax_Details__c loopTax : allSelectedTaxes) {
                                if (loopTax.CreatedDate > latestDate) {
                                    latestDate = loopTax.CreatedDate;
                                    latestTax = loopTax;
                                }
                            }
                            returnResult.add(true);
                            selectedTaxTable = latestTax;
                            newSeatAllocation.Not_in_Tax_Table__c = false;
                             
                        } else {
                            if (allSelectedTaxes.size() == 1) {
                                returnResult.add(true);
                                selectedTaxTable = allSelectedTaxes[0];
                                newSeatAllocation.Not_in_Tax_Table__c = false;
                            } 
                            if (allSelectedTaxes.size() == 0) {
                                returnResult.add(false);
                                newSeatAllocation.Not_in_Tax_Table__c = true;
                                newSeatAllocation.Tax_Date__c = null;
                                newSeatAllocation.Final_Tax_Adult__c = null;
                                newSeatAllocation.Final_Tax_Child__c = null;
                                newSeatAllocation.Final_Tax_Infant__c = null;
                            }
                        }
                        
                        //Update tax fields on Seat Allocation records
                        if (selectedTaxTable.Tax_Amount_Adult__c != null) {
                            newSeatAllocation.Final_Tax_Adult__c = selectedTaxTable.Tax_Amount_Adult__c;
                        }
                        if (selectedTaxTable.Tax_Amount_Child__c != null) {
                            newSeatAllocation.Final_Tax_Child__c = selectedTaxTable.Tax_Amount_Child__c;
                        }
                        if (selectedTaxTable.Tax_Amount_Infant__c != null) {
                            newSeatAllocation.Final_Tax_Infant__c = selectedTaxTable.Tax_Amount_Infant__c;
                        }
       
						Database.SaveResult updateResult = database.update(newSeatAllocation, false); 
    	return returnResult;
    }
}