force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Allocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Type__c</fullName>
    <label>Allocation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SRS</fullName>
            </value>
            <value>
                <fullName>ADC</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Seat Allocations and Ticketings</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Allocated_Seats__c</fullName>
    <label>Final Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchGetItinerary.cls
// Database.executeBatch(new BatchGetItinerary(), 1);
global class BatchGetItinerary implements Database.Batchable<sObject>, Database.AllowsCallouts {
    global List<Id> caseId;

    global BatchGetItinerary(List<Id> caseId) {
        this.caseId = caseId; 
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // ✅ 加入條件：只取 Allocation_Type__c != 'Adjustment' 且 Final_Allocated_Seats__c > 0
        return Database.getQueryLocator([
            SELECT Id 
            FROM Seat_Allocation_and_Ticketing__c 
            WHERE Case_ID__c IN :caseId
              AND Allocation_Type__c != 'Adjustment'
              AND Final_Allocated_Seats__c > 0
        ]);
    }
    
/*    global void execute(Database.BatchableContext bc, List<Seat_Allocation_and_Ticketing__c> records) {
        List<Id> ids = new List<Id>();
        for(Seat_Allocation_and_Ticketing__c sat : records) {
            MiddlewareUtil.getItinerary(sat.Id); 2025-07-23 Herbert 改成Queueable方式*/
            
    global void execute(Database.BatchableContext bc, List<Seat_Allocation_and_Ticketing__c> records) {
        List<Id> satIdList = new List<Id>();
        for (Seat_Allocation_and_Ticketing__c sat : records) {
            satIdList.add(sat.Id);
        }    
        // 在整個 batch 執行中，只 enqueue 一次 job
        if (!satIdList.isEmpty()) {
            System.enqueueJob(new QueueableGetItinerary(satIdList));
        }        
    }
    
    global void finish(Database.BatchableContext bc) {
    }
    
     public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        }
}