force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Seats__c</fullName>
    <label>Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Allocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Type__c</fullName>
    <label>Allocation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SRS</fullName>
            </value>
            <value>
                <fullName>ADC</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Seat Allocations and Ticketings</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Allocated_Seats__c</fullName>
    <label>Final Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Tax_Adult__c.field-meta.xml
<CustomField>
    <fullName>Final_Tax_Adult__c</fullName>
    <label>Final Tax (Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Tax_Child__c.field-meta.xml
<CustomField>
    <fullName>Final_Tax_Child__c</fullName>
    <label>Final Tax (Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Tax_Infant__c.field-meta.xml
<CustomField>
    <fullName>Final_Tax_Infant__c</fullName>
    <label>Final Tax (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Adult__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Adult__c</fullName>
    <label>Final Unit Price(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Child__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Child__c</fullName>
    <label>Final Unit Price(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Infant__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Infant__c</fullName>
    <label>Final Unit Price (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Group_Booking_Route__c.field-meta.xml
<CustomField>
    <fullName>Group_Booking_Route__c</fullName>
    <formula>Text(Case_ID__r.Route__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Booking Route</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Tax_Adult__c.field-meta.xml
<CustomField>
    <fullName>Initial_Tax_Adult__c</fullName>
    <label>Initial Tax(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Tax_Child__c.field-meta.xml
<CustomField>
    <fullName>Initial_Tax_Child__c</fullName>
    <label>Initial Tax(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Tax_Infant__c.field-meta.xml
<CustomField>
    <fullName>Initial_Tax_Infant__c</fullName>
    <label>Initial Tax(Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Unit_Price_Adult__c.field-meta.xml
<CustomField>
    <fullName>Initial_Unit_Price_Adult__c</fullName>
    <label>Initial Unit Price(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Unit_Price_Child__c.field-meta.xml
<CustomField>
    <fullName>Initial_Unit_Price_Child__c</fullName>
    <label>Initial Unit Price(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Unit_Price_Infant__c.field-meta.xml
<CustomField>
    <fullName>Initial_Unit_Price_Infant__c</fullName>
    <label>Initial Unit Price (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Tax_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date__c</fullName>
    <label>Tax Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/recordTypes/Planned_Allocation.recordType-meta.xml
<RecordType>
    <fullName>Planned_Allocation</fullName>
    <active>true</active>
    <description>For STARLUX to create Seat Allocation for Travel Agency</description>
    <label>Planned Allocation</label>
</RecordType>

force-app/main/default/objects/Tax_Details__c/Tax_Details__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <displayFormat>TX{YYYY}{MM}{00000000}</displayFormat>
        <label>Tax Details No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Details__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>Route</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TPE-MFM-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-DAD-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-PEN-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-CEB-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-MFM(one-way)</fullName>
            </value>
            <value>
                <fullName>MFM-TPE(one-way)</fullName>
            </value>
            <value>
                <fullName>TPE-DAD(one-way)</fullName>
            </value>
            <value>
                <fullName>DAD-TPE(one-way)</fullName>
            </value>
            <value>
                <fullName>TPE-PEN(one-way)</fullName>
            </value>
            <value>
                <fullName>PEN-TPE(one-way)</fullName>
            </value>
            <value>
                <fullName>TPE-CEB(one-way)</fullName>
            </value>
            <value>
                <fullName>CEB-TPE(one-way)</fullName>
            </value>
            <value>
                <fullName>TPE-BKK-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-OKA-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-FUK-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-KIX-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-SDJ-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-CTS-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-PUS-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-CNX-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-KLO-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-CJU-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-KUL-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-HKD-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-MNL-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-NRT-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-LAX-TPE</fullName>
            </value>
            <value>
                <fullName>TPE-HAN-TPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Details__c/fields/Tax_Amount_Adult__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Adult__c</fullName>
    <label>Tax Amount(Adult)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Details__c/fields/Tax_Amount_Child__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Child__c</fullName>
    <label>Tax Amount(Child)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Details__c/fields/Tax_Amount_Infant__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Infant__c</fullName>
    <label>Tax Amount(Infant)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Details__c/fields/Tax_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date__c</fullName>
    <label>Tax Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateTaxAmount_Test.cls
/********************************************************************************************************
NAME:			UpdateTaxAmount_Test
AUTHOR:			Edmond To (eto@salesforce.com)
PURPOSE:		This is the test class for UpdateTaxAmount class

UPDATE HISTORY:
DATE            AUTHOR			COMMENTS
-------------------------------------------------------------
25/08/2019      Edmond To		First version
********************************************************************************************************/
@isTest
public class UpdateTaxAmount_Test {
    public static testMethod void testUpdateTaxAmountWith5ValidTaxes() {
        //Create Account Record
        ID accountTravelRecordID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Travel_Agency').getRecordTypeId();
        Account travelAgency = new Account(RecordTypeId = accountTravelRecordID, Name = 'Test Agency', IATA_MSO_Code__c = '123456', Cash_Payment_Only__c = true);
        insert travelAgency;
        
        Account testAccount = [SELECT Id,IATA_MSO_Code__c FROM Account LIMIT 1];
        system.debug('DBG testAccount:' + testAccount);
        
        //Create Contact Record
        Contact con = new Contact(AccountId = testAccount.Id, LastName = 'Contact', FirstName= 'Test', Email='test@email.com');
        insert con;
        
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        system.debug('DBG testContact:' + testContact);
        
        //Create Case Record
		ID caseRecordID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Group_Booking').getRecordTypeId();
        Date departingDate = Date.today();
        Date departingDate2 = Date.newInstance(2040,4,5);
        Date returningDate = Date.newInstance(2040,4,10);
        String departingFlight = 'JX110';
        String returningFlight = 'JX101';
        String route = 'TPE-MFM-TPE';
        String IATACode = '123456';
        
        Map<String, Object> caseFieldValueMap = new Map<String, Object>();
        caseFieldValueMap.put('RecordTypeId', caseRecordID);
        caseFieldValueMap.put('AccountId', testAccount.Id); 
        caseFieldValueMap.put('Departing_Flight_Date__c', departingDate);
        caseFieldValueMap.put('Returning_Flight_Date__c', returningDate); 
        caseFieldValueMap.put('Departing_Flight_Number__c', departingFlight);
        caseFieldValueMap.put('Returning_Flight_Number__c', returningFlight);
        caseFieldValueMap.put('Route__c', route);
        caseFieldValueMap.put('Status', 'New');
        caseFieldValueMap.put('ContactId', testContact.Id);
        
        TestUtility.createCase(caseFieldValueMap);
        List<String> caseFields = new List<String>();
        caseFields.add('Departing_Flight_Number__c');
        caseFields.add('Returning_Flight_Number__c');
        caseFields.add('Departing_Flight_Date__c');
        caseFields.add('Returning_Flight_Date__c');
        caseFields.add('Route__c');
        
		Case testCase = (Case) TestUtility.getCase(caseFields);       
        system.debug('DBG testCase: '+testCase);
        
        //Create Tax Amount Records
        Map<String, Object> taxFieldValueMap = new Map<String, Object>();
        taxFieldValueMap.put('Route__c', route);
        taxFieldValueMap.put('Tax_Date__c', departingDate);
        taxFieldValueMap.put('Tax_Amount_Adult__c', 20000.00);
        taxFieldValueMap.put('Tax_Amount_Child__c', 10000.00);
        taxFieldValueMap.put('Tax_Amount_Infant__c', 5000.00);
        
        Map<String, Object> taxFieldValueMap2 = new Map<String, Object>();
        taxFieldValueMap2.put('Route__c', route);
        taxFieldValueMap2.put('Tax_Date__c', departingDate2);
        taxFieldValueMap2.put('Tax_Amount_Adult__c', 40000.00);
        taxFieldValueMap2.put('Tax_Amount_Child__c', 20000.00);
        taxFieldValueMap2.put('Tax_Amount_Infant__c', 10000.00);
        
        TestUtility.createTax(taxFieldValueMap);
        TestUtility.createTax(taxFieldValueMap2);
        //Tax_Details__c testTaxList = (Tax_Details__c) TestUtility.getTax();
        
        //Create Seat Allocation Record
        ID seatAllocationID = Schema.SObjectType.Seat_Allocation_and_Ticketing__c.getRecordTypeInfosByDeveloperName().get('Planned_Allocation').getRecordTypeId();
        Decimal finalSeats = 10;
        String allocationType = 'SRS';
        
        Map<String,Object> seatAllocationValueMap = new Map<String, Object>();
        seatAllocationValueMap.put('RecordTypeId',seatAllocationID);
        seatAllocationValueMap.put('Final_Allocated_Seats__c',finalSeats);
        seatAllocationValueMap.put('Allocated_Seats__c',finalSeats);
        seatAllocationValueMap.put('Case_ID__c',testCase.Id);
        seatAllocationValueMap.put('Allocation_Type__c',allocationType);
        
        TestUtility.createSeatAllocation(seatAllocationValueMap);
        
        List<String> seatAllocationFields = new List<String>();
        seatAllocationFields.add('Departing_Flight_Number__c');
        seatAllocationFields.add('Returning_Flight_Number__c');
        seatAllocationFields.add('Departing_Flight_Date__c');
        seatAllocationFields.add('Returning_Flight_Date__c');
        seatAllocationFields.add('CreatedDate');
        seatAllocationFields.add('Case_Id__r.Account.IATA_MSO_Code__c');
        seatAllocationFields.add('Group_Booking_Route__c');
        seatAllocationFields.add('Initial_Unit_Price_Adult__c');
        seatAllocationFields.add('Initial_Unit_Price_Child__c');
        seatAllocationFields.add('Initial_Unit_Price_Infant__c');
        seatAllocationFields.add('Final_Unit_Price_Adult__c');
        seatAllocationFields.add('Final_Unit_Price_Child__c');
        seatAllocationFields.add('Final_Unit_Price_Infant__c');
        seatAllocationFields.add('Initial_Tax_Adult__c');
        seatAllocationFields.add('Initial_Tax_Child__c');
        seatAllocationFields.add('Initial_Tax_Infant__c');
        seatAllocationFields.add('Final_Tax_Adult__c');
        seatAllocationFields.add('Final_Tax_Child__c');
        seatAllocationFields.add('Final_Tax_Infant__c');
        
        Seat_Allocation_and_Ticketing__c testSeatAllocation = (Seat_Allocation_and_Ticketing__c) TestUtility.getSeatAllocation(seatAllocationFields);
		List<Id> targetId = new List<Id>();
        targetId.add(testSeatAllocation.Id);
        
        testSeatAllocation.Tax_Date__c = departingDate2;
        
        //Assert tax values
        system.assertEquals(testSeatAllocation.Initial_Tax_Adult__c, 20000);
        system.assertEquals(testSeatAllocation.Initial_Tax_Child__c, 10000);
        system.assertEquals(testSeatAllocation.Initial_Tax_Infant__c, 5000);
        
        //Commence test
        Test.startTest();
        Database.SaveResult UpdateResult = database.update(testSeatAllocation);
        UpdateTaxAmount.getTaxAmount(targetId);
        Seat_Allocation_and_Ticketing__c newtestSeatAllocation = (Seat_Allocation_and_Ticketing__c) TestUtility.getSeatAllocation(seatAllocationFields);
        Test.stopTest();
        
        //Assert update succeeded and ticket fare record updated
        system.assertEquals(UpdateResult.isSuccess(), true);
        system.assertEquals(newtestSeatAllocation.Id, testSeatAllocation.Id);
        
        //Assert new tax values
        system.assertEquals(newtestSeatAllocation.Initial_Tax_Adult__c, 20000);
        system.assertEquals(newtestSeatAllocation.Initial_Tax_Child__c, 10000);
        system.assertEquals(newtestSeatAllocation.Initial_Tax_Infant__c, 5000);
        system.assertEquals(newtestSeatAllocation.Final_Tax_Adult__c, 40000);
        system.assertEquals(newtestSeatAllocation.Final_Tax_Child__c, 20000);
        system.assertEquals(newtestSeatAllocation.Final_Tax_Infant__c, 10000);
       
    }
    
    public static testMethod void testUpdateTaxAmountWithInvalidDateTax() {
        //Create Account Record
        ID accountTravelRecordID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Travel_Agency').getRecordTypeId();
        Account travelAgency = new Account(RecordTypeId = accountTravelRecordID, Name = 'Test Agency', IATA_MSO_Code__c = '123456', Cash_Payment_Only__c = true);
        insert travelAgency;
        
        Account testAccount = [SELECT Id,IATA_MSO_Code__c FROM Account LIMIT 1];
        system.debug('DBG testAccount:' + testAccount);
        
        //Create Contact Record
        Contact con = new Contact(AccountId = testAccount.Id, LastName = 'Contact', FirstName= 'Test', Email='test@email.com');
        insert con;
        
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        system.debug('DBG testContact:' + testContact);
        
        //Create Case Record
		ID caseRecordID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Group_Booking').getRecordTypeId();
        Date departingDate = Date.today();
        Date departingDate2 = Date.newInstance(2040,4,5);
        Date departingDate3 = Date.newInstance(2040,4,6);
        Date returningDate = Date.newInstance(2040,4,10);
        String departingFlight = 'JX110';
        String returningFlight = 'JX101';
        String route = 'TPE-MFM-TPE';
        String IATACode = '123456';
        
        Map<String, Object> caseFieldValueMap = new Map<String, Object>();
        caseFieldValueMap.put('RecordTypeId', caseRecordID);
        caseFieldValueMap.put('AccountId', testAccount.Id); 
        caseFieldValueMap.put('Departing_Flight_Date__c', departingDate);
        caseFieldValueMap.put('Returning_Flight_Date__c', returningDate); 
        caseFieldValueMap.put('Departing_Flight_Number__c', departingFlight);
        caseFieldValueMap.put('Returning_Flight_Number__c', returningFlight);
        caseFieldValueMap.put('Route__c', route);
        caseFieldValueMap.put('Status', 'New');
        caseFieldValueMap.put('ContactId', testContact.Id);
        
        TestUtility.createCase(caseFieldValueMap);
        List<String> caseFields = new List<String>();
        caseFields.add('Departing_Flight_Number__c');
        caseFields.add('Returning_Flight_Number__c');
        caseFields.add('Departing_Flight_Date__c');
        caseFields.add('Returning_Flight_Date__c');
        caseFields.add('Route__c');
        
		Case testCase = (Case) TestUtility.getCase(caseFields);       
        system.debug('DBG testCase: '+testCase);
        
        //Create Tax Amount Records
        Map<String, Object> taxFieldValueMap = new Map<String, Object>();
        taxFieldValueMap.put('Route__c', route);
        taxFieldValueMap.put('Tax_Date__c', departingDate);
        taxFieldValueMap.put('Tax_Amount_Adult__c', 20000.00);
        taxFieldValueMap.put('Tax_Amount_Child__c', 10000.00);
        taxFieldValueMap.put('Tax_Amount_Infant__c', 5000.00);
        
        Map<String, Object> taxFieldValueMap2 = new Map<String, Object>();
        taxFieldValueMap2.put('Route__c', route);
        taxFieldValueMap2.put('Tax_Date__c', departingDate3);
        taxFieldValueMap2.put('Tax_Amount_Adult__c', 40000.00);
        taxFieldValueMap2.put('Tax_Amount_Child__c', 20000.00);
        taxFieldValueMap2.put('Tax_Amount_Infant__c', 10000.00);
        
        TestUtility.createTaxes(taxFieldValueMap,5);
        TestUtility.createTax(taxFieldValueMap2);
        //Tax_Details__c testTaxList = (Tax_Details__c) TestUtility.getTax();
        
        //Create Seat Allocation Record
        ID seatAllocationID = Schema.SObjectType.Seat_Allocation_and_Ticketing__c.getRecordTypeInfosByDeveloperName().get('Planned_Allocation').getRecordTypeId();
        Decimal finalSeats = 10;
        String allocationType = 'SRS';
        
        Map<String,Object> seatAllocationValueMap = new Map<String, Object>();
        seatAllocationValueMap.put('RecordTypeId',seatAllocationID);
        seatAllocationValueMap.put('Final_Allocated_Seats__c',finalSeats);
        seatAllocationValueMap.put('Allocated_Seats__c',finalSeats);
        seatAllocationValueMap.put('Case_ID__c',testCase.Id);
        seatAllocationValueMap.put('Allocation_Type__c',allocationType);

        
        TestUtility.createSeatAllocation(seatAllocationValueMap);
        
        List<String> seatAllocationFields = new List<String>();
        seatAllocationFields.add('Departing_Flight_Number__c');
        seatAllocationFields.add('Returning_Flight_Number__c');
        seatAllocationFields.add('Departing_Flight_Date__c');
        seatAllocationFields.add('Returning_Flight_Date__c');
        seatAllocationFields.add('CreatedDate');
        seatAllocationFields.add('Case_Id__r.Account.IATA_MSO_Code__c');
        seatAllocationFields.add('Group_Booking_Route__c');
        seatAllocationFields.add('Initial_Unit_Price_Adult__c');
        seatAllocationFields.add('Initial_Unit_Price_Child__c');
        seatAllocationFields.add('Initial_Unit_Price_Infant__c');
        seatAllocationFields.add('Final_Unit_Price_Adult__c');
        seatAllocationFields.add('Final_Unit_Price_Child__c');
        seatAllocationFields.add('Final_Unit_Price_Infant__c');
        seatAllocationFields.add('Initial_Tax_Adult__c');
        seatAllocationFields.add('Initial_Tax_Child__c');
        seatAllocationFields.add('Initial_Tax_Infant__c');
        seatAllocationFields.add('Final_Tax_Adult__c');
        seatAllocationFields.add('Final_Tax_Child__c');
        seatAllocationFields.add('Final_Tax_Infant__c');
        
        Seat_Allocation_and_Ticketing__c testSeatAllocation = (Seat_Allocation_and_Ticketing__c) TestUtility.getSeatAllocation(seatAllocationFields);
		List<Id> targetId = new List<Id>();
        targetId.add(testSeatAllocation.Id);
        
        testSeatAllocation.Tax_Date__c = departingDate2;
        
        //Assert tax values
        system.assertEquals(testSeatAllocation.Initial_Tax_Adult__c, 20000);
        system.assertEquals(testSeatAllocation.Initial_Tax_Child__c, 10000);
        system.assertEquals(testSeatAllocation.Initial_Tax_Infant__c, 5000);
        
        //Commence test
        Test.startTest();
        Database.SaveResult UpdateResult = database.update(testSeatAllocation);
        UpdateTaxAmount.getTaxAmount(targetId);
        Seat_Allocation_and_Ticketing__c newtestSeatAllocation = (Seat_Allocation_and_Ticketing__c) TestUtility.getSeatAllocation(seatAllocationFields);
        Test.stopTest();
        
        //Assert update succeeded and ticket fare record updated
        system.assertEquals(UpdateResult.isSuccess(), true);
        system.assertEquals(newtestSeatAllocation.Id, testSeatAllocation.Id);
        
        //Assert new tax values
        system.assertEquals(newtestSeatAllocation.Initial_Tax_Adult__c, 20000);
        system.assertEquals(newtestSeatAllocation.Initial_Tax_Child__c, 10000);
        system.assertEquals(newtestSeatAllocation.Initial_Tax_Infant__c, 5000);
        system.assertEquals(newtestSeatAllocation.Final_Tax_Adult__c, null);
        system.assertEquals(newtestSeatAllocation.Final_Tax_Child__c, null);
        system.assertEquals(newtestSeatAllocation.Final_Tax_Infant__c, null);
        
    }
    
    public static testMethod void testUpdateTaxAmountWithMultipleValidTaxes() {
        //Create Account Record
        ID accountTravelRecordID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Travel_Agency').getRecordTypeId();
        Account travelAgency = new Account(RecordTypeId = accountTravelRecordID, Name = 'Test Agency', IATA_MSO_Code__c = '123456', Cash_Payment_Only__c = true);
        insert travelAgency;
        
        Account testAccount = [SELECT Id,IATA_MSO_Code__c FROM Account LIMIT 1];
        system.debug('DBG testAccount:' + testAccount);
        
        //Create Contact Record
        Contact con = new Contact(AccountId = testAccount.Id, LastName = 'Contact', FirstName= 'Test', Email='test@email.com');
        insert con;
        
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        system.debug('DBG testContact:' + testContact);
        
        //Create Case Record
		ID caseRecordID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Group_Booking').getRecordTypeId();
        Date departingDate = Date.today();
        Date departingDate2 = Date.newInstance(2040,4,5);
        Date returningDate = Date.newInstance(2040,4,10);
        String departingFlight = 'JX110';
        String returningFlight = 'JX101';
        String route = 'TPE-MFM-TPE';
        String IATACode = '123456';
        
        Map<String, Object> caseFieldValueMap = new Map<String, Object>();
        caseFieldValueMap.put('RecordTypeId', caseRecordID);
        caseFieldValueMap.put('AccountId', testAccount.Id); 
        caseFieldValueMap.put('Departing_Flight_Date__c', departingDate);
        caseFieldValueMap.put('Returning_Flight_Date__c', returningDate); 
        caseFieldValueMap.put('Departing_Flight_Number__c', departingFlight);
        caseFieldValueMap.put('Returning_Flight_Number__c', returningFlight);
        caseFieldValueMap.put('Route__c', route);
        caseFieldValueMap.put('Status', 'New');
        caseFieldValueMap.put('ContactId', testContact.Id);
        
        TestUtility.createCase(caseFieldValueMap);
        List<String> caseFields = new List<String>();
        caseFields.add('Departing_Flight_Number__c');
        caseFields.add('Returning_Flight_Number__c');
        caseFields.add('Departing_Flight_Date__c');
        caseFields.add('Returning_Flight_Date__c');
        caseFields.add('Route__c');
        
		Case testCase = (Case) TestUtility.getCase(caseFields);       
        system.debug('DBG testCase: '+testCase);
        
        //Create Tax Amount Records
        Map<String, Object> taxFieldValueMap = new Map<String, Object>();
        taxFieldValueMap.put('Route__c', route);
        taxFieldValueMap.put('Tax_Date__c', departingDate);
        taxFieldValueMap.put('Tax_Amount_Adult__c', 20000.00);
        taxFieldValueMap.put('Tax_Amount_Child__c', 10000.00);
        taxFieldValueMap.put('Tax_Amount_Infant__c', 5000.00);
        
        Map<String, Object> taxFieldValueMap2 = new Map<String, Object>();
        taxFieldValueMap2.put('Route__c', route);
        taxFieldValueMap2.put('Tax_Date__c', departingDate2);
        taxFieldValueMap2.put('Tax_Amount_Adult__c', 40000.00);
        taxFieldValueMap2.put('Tax_Amount_Child__c', 20000.00);
        taxFieldValueMap2.put('Tax_Amount_Infant__c', 10000.00);
        
        TestUtility.createTax(taxFieldValueMap);
        TestUtility.createTaxes(taxFieldValueMap2, 5);
        //Tax_Details__c testTaxList = (Tax_Details__c) TestUtility.getTax();
        
        //Create Seat Allocation Record
        ID seatAllocationID = Schema.SObjectType.Seat_Allocation_and_Ticketing__c.getRecordTypeInfosByDeveloperName().get('Planned_Allocation').getRecordTypeId();
        Decimal finalSeats = 10;
        String allocationType = 'SRS';
        
        Map<String,Object> seatAllocationValueMap = new Map<String, Object>();
        seatAllocationValueMap.put('RecordTypeId',seatAllocationID);
        seatAllocationValueMap.put('Final_Allocated_Seats__c',finalSeats);
        seatAllocationValueMap.put('Allocated_Seats__c',finalSeats);
        seatAllocationValueMap.put('Case_ID__c',testCase.Id);
        seatAllocationValueMap.put('Allocation_Type__c',allocationType);
        
        TestUtility.createSeatAllocation(seatAllocationValueMap);
        
        List<String> seatAllocationFields = new List<String>();
        seatAllocationFields.add('Departing_Flight_Number__c');
        seatAllocationFields.add('Returning_Flight_Number__c');
        seatAllocationFields.add('Departing_Flight_Date__c');
        seatAllocationFields.add('Returning_Flight_Date__c');
        seatAllocationFields.add('CreatedDate');
        seatAllocationFields.add('Case_Id__r.Account.IATA_MSO_Code__c');
        seatAllocationFields.add('Group_Booking_Route__c');
        seatAllocationFields.add('Initial_Unit_Price_Adult__c');
        seatAllocationFields.add('Initial_Unit_Price_Child__c');
        seatAllocationFields.add('Initial_Unit_Price_Infant__c');
        seatAllocationFields.add('Final_Unit_Price_Adult__c');
        seatAllocationFields.add('Final_Unit_Price_Child__c');
        seatAllocationFields.add('Final_Unit_Price_Infant__c');
        seatAllocationFields.add('Initial_Tax_Adult__c');
        seatAllocationFields.add('Initial_Tax_Child__c');
        seatAllocationFields.add('Initial_Tax_Infant__c');
        seatAllocationFields.add('Final_Tax_Adult__c');
        seatAllocationFields.add('Final_Tax_Child__c');
        seatAllocationFields.add('Final_Tax_Infant__c');
        
        Seat_Allocation_and_Ticketing__c testSeatAllocation = (Seat_Allocation_and_Ticketing__c) TestUtility.getSeatAllocation(seatAllocationFields);
		List<Id> targetId = new List<Id>();
        targetId.add(testSeatAllocation.Id);
        
        testSeatAllocation.Tax_Date__c = departingDate2;
        
        //Assert tax values
        system.assertEquals(testSeatAllocation.Initial_Tax_Adult__c, 20000);
        system.assertEquals(testSeatAllocation.Initial_Tax_Child__c, 10000);
        system.assertEquals(testSeatAllocation.Initial_Tax_Infant__c, 5000);
        
        //Commence test
        Test.startTest();
        Database.SaveResult UpdateResult = database.update(testSeatAllocation);
        UpdateTaxAmount.getTaxAmount(targetId);
        Seat_Allocation_and_Ticketing__c newtestSeatAllocation = (Seat_Allocation_and_Ticketing__c) TestUtility.getSeatAllocation(seatAllocationFields);
        Test.stopTest();
        
        //Assert update succeeded and ticket fare record updated
        system.assertEquals(UpdateResult.isSuccess(), true);
        system.assertEquals(newtestSeatAllocation.Id, testSeatAllocation.Id);
        
        //Assert new tax values
        system.assertEquals(newtestSeatAllocation.Initial_Tax_Adult__c, 20000);
        system.assertEquals(newtestSeatAllocation.Initial_Tax_Child__c, 10000);
        system.assertEquals(newtestSeatAllocation.Initial_Tax_Infant__c, 5000);
        system.assertEquals(newtestSeatAllocation.Final_Tax_Adult__c, 40000);
        system.assertEquals(newtestSeatAllocation.Final_Tax_Child__c, 20000);
        system.assertEquals(newtestSeatAllocation.Final_Tax_Infant__c, 10000);
       
    }
}