force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/Seat_Allocation_and_Ticketing__c.object-meta.xml
<CustomObject>
    <label>Seat Allocation and Ticketing</label>
    <nameField>
        <displayFormat>SAT{YYYY}{MM}{00000000}</displayFormat>
        <label>Seat Allocation and Ticketing No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Allocations and Ticketings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Seats__c</fullName>
    <label>Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Allocation_Type__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Type__c</fullName>
    <label>Allocation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SRS</fullName>
            </value>
            <value>
                <fullName>ADC</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Booking_Reference_PNR__c.field-meta.xml
<CustomField>
    <fullName>Booking_Reference_PNR__c</fullName>
    <description>Temp PNR by B2B</description>
    <label>Booking Reference</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Seat Allocations and Ticketings</relationshipLabel>
    <relationshipName>Group_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Departing_Flight_Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Departing_Flight_Arrival_Date__c</fullName>
    <formula>Case_ID__r.Departing_Flight_Arrival_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departing Flight Arrival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Allocated_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Allocated_Seats__c</fullName>
    <label>Final Allocated Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Allocated_Seats_Amadeus__c.field-meta.xml
<CustomField>
    <fullName>Final_Allocated_Seats_Amadeus__c</fullName>
    <label>Final Allocated Seats (Amadeus)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_BSC_Adult__c.field-meta.xml
<CustomField>
    <fullName>Final_BSC_Adult__c</fullName>
    <label>Final BSC (Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_BSC_Child__c.field-meta.xml
<CustomField>
    <fullName>Final_BSC_Child__c</fullName>
    <label>Final BSC (Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_BSC_Infant__c.field-meta.xml
<CustomField>
    <fullName>Final_BSC_Infant__c</fullName>
    <label>Final BSC (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Sales_Seats__c.field-meta.xml
<CustomField>
    <fullName>Final_Sales_Seats__c</fullName>
    <label>Final Sales Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Tax_Adult__c.field-meta.xml
<CustomField>
    <fullName>Final_Tax_Adult__c</fullName>
    <label>Final Tax (Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Tax_Child__c.field-meta.xml
<CustomField>
    <fullName>Final_Tax_Child__c</fullName>
    <label>Final Tax (Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Tax_Infant__c.field-meta.xml
<CustomField>
    <fullName>Final_Tax_Infant__c</fullName>
    <label>Final Tax (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Adult__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Adult__c</fullName>
    <label>Final Unit Price(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Child__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Child__c</fullName>
    <label>Final Unit Price(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Final_Unit_Price_Infant__c.field-meta.xml
<CustomField>
    <fullName>Final_Unit_Price_Infant__c</fullName>
    <label>Final Unit Price (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Get_Itinerary_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Get_Itinerary_Error_Message__c</fullName>
    <label>Get Itinerary Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Get_Itinerary_Status__c.field-meta.xml
<CustomField>
    <fullName>Get_Itinerary_Status__c</fullName>
    <label>Get Itinerary Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_BSC_Adult__c.field-meta.xml
<CustomField>
    <fullName>Initial_BSC_Adult__c</fullName>
    <label>Initial BSC(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_BSC_Child__c.field-meta.xml
<CustomField>
    <fullName>Initial_BSC_Child__c</fullName>
    <label>Initial BSC(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_BSC_Infant__c.field-meta.xml
<CustomField>
    <fullName>Initial_BSC_Infant__c</fullName>
    <label>Initial BSC(Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Tax_Adult__c.field-meta.xml
<CustomField>
    <fullName>Initial_Tax_Adult__c</fullName>
    <label>Initial Tax(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Tax_Child__c.field-meta.xml
<CustomField>
    <fullName>Initial_Tax_Child__c</fullName>
    <label>Initial Tax(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Tax_Infant__c.field-meta.xml
<CustomField>
    <fullName>Initial_Tax_Infant__c</fullName>
    <label>Initial Tax(Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Unit_Price_Adult__c.field-meta.xml
<CustomField>
    <fullName>Initial_Unit_Price_Adult__c</fullName>
    <label>Initial Unit Price(Adult)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Unit_Price_Child__c.field-meta.xml
<CustomField>
    <fullName>Initial_Unit_Price_Child__c</fullName>
    <label>Initial Unit Price(Child)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Initial_Unit_Price_Infant__c.field-meta.xml
<CustomField>
    <fullName>Initial_Unit_Price_Infant__c</fullName>
    <label>Initial Unit Price (Infant)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Itinerary__c.field-meta.xml
<CustomField>
    <fullName>Itinerary__c</fullName>
    <label>Itinerary</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Itinerary_Success_Time__c.field-meta.xml
<CustomField>
    <fullName>Itinerary_Success_Time__c</fullName>
    <description>Get Itinerary Success Time, excluding Failed Time</description>
    <inlineHelpText>此欄位僅記錄【成功取得行程單】的時間，失敗則不紀錄</inlineHelpText>
    <label>Itinerary Success Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Last_Get_Itinerary_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Get_Itinerary_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Get Itinerary By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Seat_Allocations_and_Ticketings3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/No_of_Adult__c.field-meta.xml
<CustomField>
    <fullName>No_of_Adult__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of Adult</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/No_of_Child__c.field-meta.xml
<CustomField>
    <fullName>No_of_Child__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of Child</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/No_of_Infant__c.field-meta.xml
<CustomField>
    <fullName>No_of_Infant__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of Infant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Not_in_Fare_Table__c.field-meta.xml
<CustomField>
    <fullName>Not_in_Fare_Table__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not in Fare Table</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Not_in_Tax_Table__c.field-meta.xml
<CustomField>
    <fullName>Not_in_Tax_Table__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not in Tax Table</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Original_Sat__c.field-meta.xml
<CustomField>
    <fullName>Original_Sat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Sat</label>
    <referenceTo>Seat_Allocation_and_Ticketing__c</referenceTo>
    <relationshipLabel>Seat Allocations and Ticketings</relationshipLabel>
    <relationshipName>Seat_Allocations_and_Ticketings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Returning_Flight_Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Returning_Flight_Arrival_Date__c</fullName>
    <formula>Case_ID__r.Returning_Flight_Arrival_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Returning Flight Arrival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Sync_SAT_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_SAT_Status__c</fullName>
    <label>Sync SAT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>X1A_Intergration_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Tax_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date__c</fullName>
    <label>Tax Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Total_Seat_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Seat_Sales__c</fullName>
    <label>Total Seat Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/Tour_Code__c.field-meta.xml
<CustomField>
    <fullName>Tour_Code__c</fullName>
    <label>Tour Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/tour_Guide_email__c.field-meta.xml
<CustomField>
    <fullName>tour_Guide_email__c</fullName>
    <label>tour Guide email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Seat_Allocation_and_Ticketing__c/fields/tour_Guide_phone__c.field-meta.xml
<CustomField>
    <fullName>tour_Guide_phone__c</fullName>
    <label>tour Guide phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ResizePnr.cls
public class ResizePnr {

    // Input Wrapper
    public class InputWrapper {
        @InvocableVariable(required=true)
        public String satId;

        @InvocableVariable(required=true)
        public Integer seatResizing;
        
        /*@InvocableVariable(required=true)
        public String satNoResizing;

        @InvocableVariable(required=true)
        public String satNoMaster;

        @InvocableVariable(required=true)
        public String bookingReference;

        @InvocableVariable(required=true)
        public Integer seatResizing;*/
    }

    // Output Wrapper (Optional)
    public class OutputWrapper {
        @InvocableVariable
        public String resultMessage;
    }

    @InvocableMethod(label='Resize PNR')
    public static void resizePnr(List<InputWrapper> inputs) {
        //List<OutputWrapper> results = new List<OutputWrapper>();
        for (InputWrapper input : inputs) {
            Seat_Allocation_and_Ticketing__c originalSat = 
                [SELECT Id, Name, Allocated_Seats__c,
                 Booking_Reference_PNR__c, Total_Seat_Sales__c,
                 Final_Allocated_Seats__c, Final_Allocated_Seats_Amadeus__c, 
                 Final_Sales_Seats__c, Case_ID__c,
                 Allocation_Type__c,
                 tour_Guide_email__c,
                 tour_Guide_phone__c,
                 Initial_Unit_Price_Adult__c,
                 Final_Unit_Price_Adult__c,
                 Initial_Unit_Price_Child__c,
                 Final_Unit_Price_Child__c,
                 Initial_Unit_Price_Infant__c,
                 Final_Unit_Price_Infant__c,
                 Initial_Tax_Adult__c,
                 Final_Tax_Adult__c,
                 Initial_BSC_Adult__c,
                 Final_BSC_Adult__c,
                 Initial_Tax_Child__c,
                 Final_Tax_Child__c,
                 Initial_BSC_Child__c,
                 Final_BSC_Child__c,
                 Initial_Tax_Infant__c,
                 Final_Tax_Infant__c,
                 Initial_BSC_Infant__c,
                 Final_BSC_Infant__c,
                 Not_in_Fare_Table__c,
                 Tour_Code__c,
                 Not_in_Tax_Table__c,
                 Tax_Date__c
                 FROM Seat_Allocation_and_Ticketing__c
                 WHERE Id = :input.satId];
            
            Case originalCase = [SELECT Id, Status, ParentId, Total_Seat_Sales__c, Total_Seat_Sales_By_Date__c,
                                 SST_Mark__c, Sync_SST_Status__c, RecordTypeId, ContactId, AccountId, Route__c,
                                 Departing_Flight_Number__c, Returning_Flight_Number__c, Departing_Flight_Date__c, 
                                 Departing_Flight_Arrival_Date__c, Returning_Flight_Date__c, 
                                 Returning_Flight_Arrival_Date__c FROM Case WHERE Id = :originalSat.Case_ID__c];
            
            // ---- Clone Case ----
            Case newCase = originalCase.clone(false, true, false, false);
            newCase.ParentId = originalCase.Id;
            newCase.Status = 'Ticket Sales In Progress';
            insert newCase;
            newCase = [SELECT CaseNumber FROM Case WHERE Id = :newCase.Id];
            
            // ---- Clone SAT ----
            Seat_Allocation_and_Ticketing__c newSat = originalSat.clone(false, true, false, false);
            newSat.Case_ID__c = newCase.Id;
            newSat.Allocated_Seats__c = input.seatResizing;
            newSat.Total_Seat_Sales__c = null;
            newSat.Final_Allocated_Seats__c = input.seatResizing;
            newSat.Final_Allocated_Seats_Amadeus__c = input.seatResizing;
            newSat.Final_Sales_Seats__c = null;

            
            // Additional fields initialized as null
            newSat.Itinerary__c = null;
            newSat.Get_Itinerary_Status__c = null;
            newSat.Get_Itinerary_Error_Message__c = null;
            newSat.Itinerary_Success_Time__c = null;
            newSat.Last_Get_Itinerary_By__c = null;
            newSat.No_of_Adult__c = null;
            newSat.No_of_Infant__c = null;
            newSat.No_of_Child__c = null;
            newSat.Original_Sat__c = originalSat.Id;     
            
            originalSat.Allocated_Seats__c -= input.seatResizing;
            originalSat.Final_Allocated_Seats__c -= input.seatResizing;
            if (originalSat.Final_Sales_Seats__c != null) originalSat.Final_Sales_Seats__c -= input.seatResizing;
            if (originalSat.Total_Seat_Sales__c == null) originalSat.Total_Seat_Sales__c = 0;
            originalSat.Final_Allocated_Seats_Amadeus__c -= input.seatResizing;
            
            /*Decimal temp = 0;
            
            if (originalSat.Final_Allocated_Seats__c < originalSat.Total_Seat_Sales__c) {
                temp = originalSat.Total_Seat_Sales__c - originalSat.Final_Allocated_Seats__c;
                originalSat.Total_Seat_Sales__c = originalSat.Final_Allocated_Seats__c;
            }*/

            insert newSat;
            update originalSat;

            newSat = [SELECT Id,Name,Case_ID__c,RecordTypeId,Allocation_Type__c,Final_Allocated_Seats__c,Sync_SAT_Status__c FROM Seat_Allocation_and_Ticketing__c WHERE Id = :newSat.Id];
            /*newSat.Total_Seat_Sales__c = temp;
            update newSat;*/
            Seat_Allocation_and_Ticketing__c masterSat = [SELECT Id, Name 
                                                          FROM Seat_Allocation_and_Ticketing__c 
                                                          WHERE Case_ID__c =: originalSat.Case_ID__c 
                                                          AND Booking_Reference_PNR__c =: originalSat.Booking_Reference_PNR__c 
                                                          AND (Allocation_Type__c =: Constants.PICKLIST_SAT_ALLOCATION_TYPE_ADC 
                                                               OR Allocation_Type__c =: Constants.PICKLIST_SAT_ALLOCATION_TYPE_SRS) LIMIT 1];
                                                               
                                                               
            //MiddlewareUtil.resizePnr(newSat.Name, masterSat.Name, originalSat.Booking_Reference_PNR__c, input.seatResizing, newCase.CaseNumber);
           System.enqueueJob(new QueueableResizePnr(newSat.Name, masterSat.Name, originalSat.Booking_Reference_PNR__c, input.seatResizing, newCase.CaseNumber), 1);
        }
    }
}