force-app/main/default/objects/External_Tickets__c/External_Tickets__c.object-meta.xml
<CustomObject>
    <label>External Tickets</label>
    <nameField>
        <label>External Tickets</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Tickets__c/fields/Generated__c.field-meta.xml
<CustomField>
    <fullName>Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Itinerary_Departure__c.field-meta.xml
<CustomField>
    <fullName>Itinerary_Departure__c</fullName>
    <label>Itinerary(Departure)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Route</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Itinerary_Departure_CH__c.field-meta.xml
<CustomField>
    <fullName>Itinerary_Departure_CH__c</fullName>
    <label>出發地</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Office__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Itinerary_Departure_External_CN</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Itinerary_Return__c.field-meta.xml
<CustomField>
    <fullName>Itinerary_Return__c</fullName>
    <label>Itinerary(Return)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Route</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Itinerary_Return_CH__c.field-meta.xml
<CustomField>
    <fullName>Itinerary_Return_CH__c</fullName>
    <label>目的地</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Office__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Itinerary_Return_External_CH</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Apply Dept</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>External_Tickets</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule__c/Ticket_Encoding_Rule__c.object-meta.xml
<CustomObject>
    <description>編碼原則</description>
    <label>Ticket Encoding Rule</label>
    <nameField>
        <displayFormat>TER-{00000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Encoding Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Encoding_Rule__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <defaultValue>&apos;JX&apos;</defaultValue>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule__c/fields/Start_No__c.field-meta.xml
<CustomField>
    <fullName>Start_No__c</fullName>
    <label>Start No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule_Detail__c/Ticket_Encoding_Rule_Detail__c.object-meta.xml
<CustomObject>
    <label>Ticket Encoding Rule Detail</label>
    <nameField>
        <displayFormat>TERD-{00000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ticket Encoding Rule Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Encoding_Rule_Detail__c/fields/Invalid__c.field-meta.xml
<CustomField>
    <fullName>Invalid__c</fullName>
    <formula>IF(Expiring_Date__c&lt;Today(),True,false)</formula>
    <label>Invalid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule_Detail__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <description>編碼產生序號</description>
    <inlineHelpText>編碼產生序號</inlineHelpText>
    <label>Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ticket_Encoding_Rule_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TypeTicket_Encoding_Rule_No__r.RecordType.Name</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AaronTest.cls
@isTest
private class AaronTest {
    @isTest
    private static void testAll() {
        
        Ticket_Encoding_Rule__c ter1 = new Ticket_Encoding_Rule__c();
        ter1.Code__c = 'JX';
        ter1.Department__c = 'CRD';
        ter1.Year__c = 23;
        ter1.Start_No__c = '996';
        ter1.RecordTypeId = Schema.getGlobalDescribe().get('Ticket_Encoding_Rule__c').getDescribe().getRecordTypeInfosByName().get('Item No').getRecordTypeId();
        Insert ter1;
        
        Ticket_Encoding_Rule__c ter2 = new Ticket_Encoding_Rule__c();
        ter2.Code__c = 'JX';
        ter2.Department__c = 'CRD';
        ter2.Year__c = 23;
        ter2.Start_No__c = '1111';
        ter2.RecordTypeId = Schema.getGlobalDescribe().get('Ticket_Encoding_Rule__c').getDescribe().getRecordTypeInfosByName().get('Coupon No').getRecordTypeId();
        Insert ter2;
        
        Ticket_Encoding_Rule__c ter3 = new Ticket_Encoding_Rule__c();
        ter3.Code__c = 'JX';
        ter3.Department__c = 'CRD';
        ter3.Year__c = 23;
        ter3.Start_No__c = '1111';
        ter3.RecordTypeId = Schema.getGlobalDescribe().get('Ticket_Encoding_Rule__c').getDescribe().getRecordTypeInfosByName().get('Certificate No').getRecordTypeId();
        Insert ter3;
        
        System.debug([SELECT Id, Number__c, Type__c, Used__c, Invalid__c FROM Ticket_Encoding_Rule_Detail__c]);
        
        External_Tickets__c ex = new External_Tickets__c();
        ex.Office__c = 'PMDPSP';
        /*SObjectField picklistUsingGlobal = SObjectType.External_Tickets__c.fields.Itinerary_Return_CH__c.getSObjectField();
        List<PicklistEntry> entries = picklistUsingGlobal.getDescribe().getPicklistValues();*/
        ex.Itinerary_Departure_CH__c  = '台北，台灣';
        ex.Itinerary_Return_CH__c = '舊金山，美國';
        ex.Itinerary_Departure__c  = 'TPE';
        //ex.Itinerary_Return__c = '';
        insert ex;
        
        ex.Generated__c = true;
        update ex;
        
        TicketCertificateController.fakeMethod();
        Batch_trTicket_RandomString.fakeMethod();
        SingleCertCNController.fakeMethod();
        ExternalTicketTrigger_Handler.fakeMethod();
        SingleCertENController.fakeMethod();
        QRcodeScanController.fakeMethod();
        QRCodeController.fakeMethod();
        ExternalTicketsController.fakeMethod();
    }
}