force-app/main/default/objects/External_Tickets__c/External_Tickets__c.object-meta.xml
<CustomObject>
    <label>External Tickets</label>
    <nameField>
        <label>External Tickets</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Tickets__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountExternalTickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Applicant_Dept__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Dept__c</fullName>
    <description>申請人部門代碼</description>
    <inlineHelpText>申請人部門代碼</inlineHelpText>
    <label>Applicant Dept</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <description>員工姓名</description>
    <inlineHelpText>員工姓名</inlineHelpText>
    <label>Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Apply_For__c.field-meta.xml
<CustomField>
    <fullName>Apply_For__c</fullName>
    <description>申請對象</description>
    <inlineHelpText>申請對象</inlineHelpText>
    <label>Apply For</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Arrival__c.field-meta.xml
<CustomField>
    <fullName>Arrival__c</fullName>
    <description>目的地英文</description>
    <inlineHelpText>目的地英文</inlineHelpText>
    <label>Arrival</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/ArrivalID__c.field-meta.xml
<CustomField>
    <fullName>ArrivalID__c</fullName>
    <description>目的地代碼</description>
    <inlineHelpText>目的地代碼</inlineHelpText>
    <label>ArrivalID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Booking_Class__c.field-meta.xml
<CustomField>
    <fullName>Booking_Class__c</fullName>
    <label>Booking Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Budget_Type__c.field-meta.xml
<CustomField>
    <fullName>Budget_Type__c</fullName>
    <description>額度使用</description>
    <inlineHelpText>預算額度內申請 : In /  預算額度外申請 : Out</inlineHelpText>
    <label>Budget Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Account__r.Name</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Depature__c.field-meta.xml
<CustomField>
    <fullName>Depature__c</fullName>
    <description>出發地英文</description>
    <inlineHelpText>出發地英文</inlineHelpText>
    <label>Depature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/DepatureID__c.field-meta.xml
<CustomField>
    <fullName>DepatureID__c</fullName>
    <description>出發地代碼</description>
    <inlineHelpText>出發地代碼</inlineHelpText>
    <label>DepatureID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount Percentage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Embargo__c.field-meta.xml
<CustomField>
    <fullName>Embargo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Embargo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Exemption_Tax__c.field-meta.xml
<CustomField>
    <fullName>Exemption_Tax__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Exemption_YQ__c.field-meta.xml
<CustomField>
    <fullName>Exemption_YQ__c</fullName>
    <defaultValue>false</defaultValue>
    <label>YQ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Exemption_YR__c.field-meta.xml
<CustomField>
    <fullName>Exemption_YR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>YR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>憑證兌換效期</description>
    <inlineHelpText>憑證兌換效期</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Fare_Basis__c.field-meta.xml
<CustomField>
    <fullName>Fare_Basis__c</fullName>
    <label>Discount Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PFA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
            </value>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>RG</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>中英版本</description>
    <inlineHelpText>中英版本</inlineHelpText>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>EN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/PFA_No__c.field-meta.xml
<CustomField>
    <fullName>PFA_No__c</fullName>
    <label>PFA No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Prizes_and_Awards_won_by_chance__c.field-meta.xml
<CustomField>
    <fullName>Prizes_and_Awards_won_by_chance__c</fullName>
    <label>Prizes and Awards won by chance</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Reason_for_Application__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Application__c</fullName>
    <label>Reason for Application</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/SerialID__c.field-meta.xml
<CustomField>
    <fullName>SerialID__c</fullName>
    <description>表單編號</description>
    <inlineHelpText>表單編號</inlineHelpText>
    <label>BPM No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Ticket_Count__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Count__c</fullName>
    <description>產生明細張數</description>
    <label>Ticket Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/Ticket_Certificate__c.object-meta.xml
<CustomObject>
    <label>Ticket Certificate</label>
    <nameField>
        <label>Ticket No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Certificates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Certificate__c/fields/Arrival__c.field-meta.xml
<CustomField>
    <fullName>Arrival__c</fullName>
    <formula>External_Tickets__r.Arrival__c</formula>
    <label>Arrival</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/ArrivalID__c.field-meta.xml
<CustomField>
    <fullName>ArrivalID__c</fullName>
    <formula>External_Tickets__r.ArrivalID__c</formula>
    <label>ArrivalID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Booking_Class__c.field-meta.xml
<CustomField>
    <fullName>Booking_Class__c</fullName>
    <formula>External_Tickets__r.Booking_Class__c</formula>
    <label>Booking Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>External_Tickets__r.Company__c</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Depature__c.field-meta.xml
<CustomField>
    <fullName>Depature__c</fullName>
    <formula>External_Tickets__r.Depature__c</formula>
    <label>Depature</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/DepatureID__c.field-meta.xml
<CustomField>
    <fullName>DepatureID__c</fullName>
    <formula>External_Tickets__r.DepatureID__c</formula>
    <label>DepatureID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <formula>TEXT(External_Tickets__r.Discount__c)</formula>
    <label>Discount Percentage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Embargo__c.field-meta.xml
<CustomField>
    <fullName>Embargo__c</fullName>
    <formula>External_Tickets__r.Embargo__c</formula>
    <label>Embargo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Exemption_Tax__c.field-meta.xml
<CustomField>
    <fullName>Exemption_Tax__c</fullName>
    <formula>External_Tickets__r.Exemption_Tax__c</formula>
    <label>Tax</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Exemption_YQ__c.field-meta.xml
<CustomField>
    <fullName>Exemption_YQ__c</fullName>
    <formula>External_Tickets__r.Exemption_YQ__c</formula>
    <label>YQ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Exemption_YR__c.field-meta.xml
<CustomField>
    <fullName>Exemption_YR__c</fullName>
    <formula>External_Tickets__r.Exemption_YR__c</formula>
    <label>YR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>External_Tickets__r.Expiration_Date__c</formula>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/External_Tickets__c.field-meta.xml
<CustomField>
    <fullName>External_Tickets__c</fullName>
    <label>External Tickets</label>
    <referenceTo>External_Tickets__c</referenceTo>
    <relationshipName>Ticket_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Fare_Basis__c.field-meta.xml
<CustomField>
    <fullName>Fare_Basis__c</fullName>
    <label>Discount Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
            </value>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>RG</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>PFA</fullName>
                <isActive>false</isActive>
                <label>PFA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/PFA_No__c.field-meta.xml
<CustomField>
    <fullName>PFA_No__c</fullName>
    <formula>External_Tickets__r.PFA_No__c</formula>
    <label>PFA No.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Prizes_and_Awards_won_by_chance__c.field-meta.xml
<CustomField>
    <fullName>Prizes_and_Awards_won_by_chance__c</fullName>
    <formula>TEXT(External_Tickets__r.Prizes_and_Awards_won_by_chance__c)</formula>
    <label>Prizes and Awards won by chance</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Reason_for_Application__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Application__c</fullName>
    <formula>&quot;1&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reason for Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/SerialID__c.field-meta.xml
<CustomField>
    <fullName>SerialID__c</fullName>
    <formula>External_Tickets__r.SerialID__c</formula>
    <label>BPM No.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExternalTicketFRFTResultController.cls
public without sharing class ExternalTicketFRFTResultController {
    public String companyType { get; set; }
    public String departmentCode { get; set; }
    public String loginCode { get; set; }
    public Id accountId { get; set; }

    public External_Tickets__c ticket { get; set; }
    public String bpmAppNo { get; set; }
    public List<Ticket_Certificate__c> certs { get; private set; }
	// 建構元
    public ExternalTicketFRFTResultController() {}

    public PageReference ensureAuth() {
        // 讀 cookie（集中在這裡）
        Map<String, Cookie> ck = ApexPages.currentPage().getCookies();
        if (ck.containsKey('Company_type__c'))
            companyType = EncodingUtil.urlDecode(ck.get('Company_type__c').getValue(), 'UTF-8');
        if (ck.containsKey('Department_Code__c'))
            departmentCode = EncodingUtil.urlDecode(ck.get('Department_Code__c').getValue(), 'UTF-8');
        if (ck.containsKey('Login_Code__c'))
            loginCode = EncodingUtil.urlDecode(ck.get('Login_Code__c').getValue(), 'UTF-8');
        
        // 1) 沒 cookie -> 回登入
        if (String.isBlank(companyType) || String.isBlank(departmentCode) || String.isBlank(loginCode)) {
            PageReference lp = Page.ExternalTicketLogin;
            lp.setRedirect(true);
            return lp;
        }

        // 2) 要有 bpmAppNo 參數，否則回 Search 並提示 again
        bpmAppNo = ApexPages.currentPage().getParameters().get('bpmAppNo');
        if (String.isBlank(bpmAppNo)) {
            PageReference sp = Page.ExternalTicketFRFTSearch;
            sp.getParameters().put('toast', 'again');
            sp.setRedirect(true);
            return sp;
        }else{
            certs = String.isBlank(bpmAppNo) ? new List<Ticket_Certificate__c>() : [
                SELECT Id, Name
                FROM Ticket_Certificate__c
                WHERE External_Tickets__r.SerialID__c = :bpmAppNo
                ORDER BY CreatedDate ASC
                LIMIT 1000
        	];
        }

        // 3) 找登入者 Account（用 cookie 條件）
        List<Account> accList = [
            SELECT Id
            FROM Account
            WHERE Company_type__c = :companyType
              AND Department_Code__c = :departmentCode
            LIMIT 1
        ];
        if (accList.isEmpty()) {
            PageReference lp = Page.ExternalTicketLogin;
            lp.setRedirect(true);
            return lp;
        }
        accountId = accList[0].Id;

        // 4) 查 External_Tickets__c（含 bpmAppNo + Account 限制）
        List<External_Tickets__c> ets = [
            SELECT Id, SerialID__c, Applicant__c, Applicant_Dept__c, Applicant_Name__c,
                   Budget_Type__c, Company__c, Reason_for_Application__c, Fare_Basis__c,
                   Apply_For__c, Discount__c, Exemption_YQ__c, Exemption_Tax__c,
                   Exemption_YR__c, Embargo__c, Ticket_Count__c, PFA_No__c,
                   Prizes_and_Awards_won_by_chance__c, Expiration_Date__c,
                   DepatureID__c, ArrivalID__c, Depature__c, Arrival__c,
                   Booking_Class__c, Language__c, Account__c,Two_People__c
            FROM External_Tickets__c
            WHERE SerialID__c = :bpmAppNo
              AND Account__c = :accountId
            LIMIT 1
        ];

        // 5) 查不到 -> 回 Search 並提示 again
        if (ets.isEmpty()) {
            PageReference sp = Page.ExternalTicketFRFTSearch;
            sp.getParameters().put('toast', 'again');
            sp.setRedirect(true);
            return sp;
        }

        // 6) OK：設資料，讓頁面正常 render
        ticket = ets[0];
        return null;
    }

    public String CN_PDF_URL {
        get {
            PageReference p = Page.SingleCertificateCN_PDF;
            if (!String.isBlank(bpmAppNo)) p.getParameters().put('bpmAppNo', bpmAppNo);
            String url = p.getUrl();                 // "/apex/singlecertificatecn_pdf?..."
            String prefix = Site.getPathPrefix();    // "/ExternalTicket" 或空字串
            if (!String.isBlank(prefix)) url = url.replace('/apex/', prefix + '/');
            return url;
        }
    }
    
    public String EN_PDF_URL {
        get {
            PageReference p = Page.SingleCertificateEN_PDF;
            if (!String.isBlank(bpmAppNo)) p.getParameters().put('bpmAppNo', bpmAppNo);
            String url = p.getUrl();                 // "/apex/singlecertificatecn_pdf?..."
            String prefix = Site.getPathPrefix();    // "/ExternalTicket" 或空字串
            if (!String.isBlank(prefix)) url = url.replace('/apex/', prefix + '/');
            return url;
        }
    }
    
    public Map<String, String> pdfParams {
        get {
            Map<String, String> m = new Map<String, String>();
            if (!String.isBlank(bpmAppNo)) m.put('bpmAppNo', bpmAppNo);
            return m;
        }
    }
        
    public PageReference logout() {
        ExternalTicketLoginUtility.clearAccountLoginCookie();
        PageReference p = Page.ExternalTicketLogin;
        p.getParameters().put('toast', 'logout');
        p.setRedirect(true);
        return p;
    }
    
    public String getItemsJsonCN() {
        List<Map<String,String>> rows = new List<Map<String,String>>();
        for (Ticket_Certificate__c c : certs) {
            rows.add(new Map<String,String>{
                'name' => sanitize(c.Name) + '_CN.pdf',
                'url'  => pdfUrlCN(c.Id)
            });
        }
        return JSON.serialize(rows);
    }

    private String pdfUrlCN(Id certId){
        PageReference p = Page.SingleCertificateCN_PDF; // 你的 PDF VF 頁
        p.getParameters().put('certId', (String)certId);
        String url = p.getUrl();              // /apex/SingleCertificateCN_PDF?certId=...
        String prefix = Site.getPathPrefix(); // /ExternalTicket 或空字串
        if (!String.isBlank(prefix)) url = url.replace('/apex/', prefix + '/');
        return url;
    }

    public String getItemsJsonEN() {
        List<Map<String,String>> rows = new List<Map<String,String>>();
        for (Ticket_Certificate__c c : certs) {
            rows.add(new Map<String,String>{
                'name' => sanitize(c.Name) + '_EN.pdf',
                'url'  => pdfUrlEN(c.Id)
            });
        }
        return JSON.serialize(rows);
    }

    private String pdfUrlEN(Id certId){
        PageReference p = Page.SingleCertificateEN_PDF; // 你的 PDF VF 頁
        p.getParameters().put('certId', (String)certId);
        String url = p.getUrl();              // /apex/SingleCertificateEN_PDF?certId=...
        String prefix = Site.getPathPrefix(); // /ExternalTicket 或空字串
        if (!String.isBlank(prefix)) url = url.replace('/apex/', prefix + '/');
        return url;
    }

    private static String sanitize(String s){
        if (String.isBlank(s)) return 'Certificate';
        s = s.trim().replaceAll('[\\\\/:*?"<>|\\r\\n]+','_');
        if (s.length()>120) s = s.substring(0,120);
        return s;
    }
    public static void fakeMethod() {
        Integer i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
    }
    

}