force-app/main/default/objects/External_Tickets__c/External_Tickets__c.object-meta.xml
<CustomObject>
    <label>External Tickets</label>
    <nameField>
        <label>External Tickets</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Tickets__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountExternalTickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Applicant_Dept__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Dept__c</fullName>
    <description>申請人部門代碼</description>
    <inlineHelpText>申請人部門代碼</inlineHelpText>
    <label>Applicant Dept</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <description>員工姓名</description>
    <inlineHelpText>員工姓名</inlineHelpText>
    <label>Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/ArrivalID__c.field-meta.xml
<CustomField>
    <fullName>ArrivalID__c</fullName>
    <description>目的地代碼</description>
    <inlineHelpText>目的地代碼</inlineHelpText>
    <label>ArrivalID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Booking_Class__c.field-meta.xml
<CustomField>
    <fullName>Booking_Class__c</fullName>
    <label>Booking Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Budget_Type__c.field-meta.xml
<CustomField>
    <fullName>Budget_Type__c</fullName>
    <description>額度使用</description>
    <inlineHelpText>預算額度內申請 : In /  預算額度外申請 : Out</inlineHelpText>
    <label>Budget Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In</fullName>
            </value>
            <value>
                <fullName>Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/DepatureID__c.field-meta.xml
<CustomField>
    <fullName>DepatureID__c</fullName>
    <description>出發地代碼</description>
    <inlineHelpText>出發地代碼</inlineHelpText>
    <label>DepatureID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount Percentage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Embargo__c.field-meta.xml
<CustomField>
    <fullName>Embargo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Embargo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Embargo_Next_Year_Taiwan_to_World__c.field-meta.xml
<CustomField>
    <fullName>Embargo_Next_Year_Taiwan_to_World__c</fullName>
    <label>Embargo：Next Year（Taiwan to World）</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Embargo_This_Year_Taiwan_to_World__c.field-meta.xml
<CustomField>
    <fullName>Embargo_This_Year_Taiwan_to_World__c</fullName>
    <label>Embargo：This Year（Taiwan to World）</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Embargo_This_Year_World_to_Taiwan__c.field-meta.xml
<CustomField>
    <fullName>Embargo_This_Year_World_to_Taiwan__c</fullName>
    <label>Embargo：This Year（World to Taiwan）</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Exemption_Tax__c.field-meta.xml
<CustomField>
    <fullName>Exemption_Tax__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Exemption_YQ__c.field-meta.xml
<CustomField>
    <fullName>Exemption_YQ__c</fullName>
    <defaultValue>false</defaultValue>
    <label>YQ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Exemption_YR__c.field-meta.xml
<CustomField>
    <fullName>Exemption_YR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>YR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Fare_Basis__c.field-meta.xml
<CustomField>
    <fullName>Fare_Basis__c</fullName>
    <label>Discount Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PFA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
            </value>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>RG</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Item_Status__c</fullName>
    <label>Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Send</fullName>
                <default>true</default>
                <label>Send</label>
            </value>
            <value>
                <fullName>Approve (Inner)</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Approve (Final)</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Approve</fullName>
                <isActive>false</isActive>
                <label>Approve</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Last_Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Approver_Name__c</fullName>
    <description>最後簽核人</description>
    <inlineHelpText>最後簽核人</inlineHelpText>
    <label>Last Approver Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Organizer_Event_Title__c.field-meta.xml
<CustomField>
    <fullName>Organizer_Event_Title__c</fullName>
    <inlineHelpText>主辦單位/活動名稱</inlineHelpText>
    <label>Organizer / Event Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/QuotaManageID__c.field-meta.xml
<CustomField>
    <fullName>QuotaManageID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Manage</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>This Quota has been used, please changed another Quota.</errorMessage>
        <filterItems>
            <field>Quota_Manage__c.Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quota_Manage__c</referenceTo>
    <relationshipLabel>External Tickets</relationshipLabel>
    <relationshipName>External_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/SerialID__c.field-meta.xml
<CustomField>
    <fullName>SerialID__c</fullName>
    <description>表單編號</description>
    <inlineHelpText>表單編號</inlineHelpText>
    <label>BPM No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/External_Tickets__c/fields/Ticket_Count__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Count__c</fullName>
    <description>產生明細張數</description>
    <label>Ticket Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/Quota_Manage__c.object-meta.xml
<CustomObject>
    <description>額度管理主檔(初始額度)</description>
    <label>Quota Manage</label>
    <nameField>
        <displayFormat>QT-{00000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota Manage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota_Manage__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quota Manage</relationshipLabel>
    <relationshipName>Account_Quota_Manage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Discount_Code__c.field-meta.xml
<CustomField>
    <fullName>Discount_Code__c</fullName>
    <label>Discount Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>DG</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>RG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Quota_Initial__c.field-meta.xml
<CustomField>
    <fullName>Quota_Initial__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quota(Initial)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Quota_Transit__c.field-meta.xml
<CustomField>
    <fullName>Quota_Transit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>在途額度</description>
    <label>Quota(Transit)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Quota_Used__c.field-meta.xml
<CustomField>
    <fullName>Quota_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quota(Used)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Manage__c/fields/Valid_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_Date__c</fullName>
    <label>Valid Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RestMiddlewarePfaApiTest.cls
@IsTest
private class RestMiddlewarePfaApiTest {

    /*@testSetup
    static void setupApproveData() {
        // ------------------------
        // Department Account
        // ------------------------
        Account dept = createDepartmentAccount();
        
        // ------------------------
        // Quota
        // ------------------------
        Quota_Manage__c quota = createQuota(dept.Id);
        
        // ------------------------
        // External Ticket (Transit state)
        // ------------------------
        External_Tickets__c ticket = new External_Tickets__c(
            Account__c = dept.Id,
            Applicant_Name__c = 'Tester',
            Ticket_Count__c = 1,
            Budget_Type__c = 'In',
            Item_Status__c = 'Approve (Inner)',
            QuotaManageID__c = quota.Id
        );
        insert ticket;
    }

    private static Account createDepartmentAccount() {
        Id rtId = Schema.getGlobalDescribe()
            .get('Account')
            .getDescribe()
            .getRecordTypeInfosByName()
            .get('Department')
            .getRecordTypeId();

        Account acc = new Account(
            Name = 'Test Dept',
            RecordTypeId = rtId,
            Department_Code__c = 'ABCDEF123'
        );
        insert acc;
        return acc;
    }

    private static Quota_Manage__c createQuota(Id accountId) {
        Quota_Manage__c quota = new Quota_Manage__c(
            Account__c = accountId,
            Discount_Code__c = 'AD',
            Discount__c = '90',
            Quota_Initial__c = 10,
            Quota_Used__c = 0,
            Quota_Transit__c = 0,
            Valid_Date__c = Date.today().addDays(-1),   // ✔ yesterday
        	Expiry_Date__c = Date.today().addDays(1)
        );
        insert quota;
        return quota;
    }

    @IsTest
    static void testCreateSuccessAnonymous() {
        PfaRequest req = new PfaRequest();
        req.ActionCode = '0';
        req.applicantDept = 'ABCDEF123';
        req.applicantName = 'Tester';
        req.Qty = 1;
        req.Budget = 'In';
        req.Category = 'AD';
        req.Discount = '90';
        req.ApplicationType = 'Anonymous';
        req.Passenger = new List<PfaRequest.PassengerEntry>();
        req.Route = new List<PfaRequest.RouteEntry>();
        req.EmbargoPeriodTPE = new List<PfaRequest.EmbargoEntry>();
        req.EmbargoPeriodForeign = new List<PfaRequest.EmbargoEntry>();

        Test.startTest();
        ResponseModelPfa res = RestMiddlewarePfaApi.handlePfaRequest(req);
        Test.stopTest();

        System.assertEquals(true, res.success);
    }
    
    @IsTest
    static void testCreateSuccess() {
        Account acc = createDepartmentAccount();
        createQuota(acc.Id);
        
        // ------------------------
        // Passenger
        // ------------------------
        PfaRequest.PassengerEntry passenger = new PfaRequest.PassengerEntry();
        passenger.FirstName = 'John';
        passenger.LastName = 'Doe';
        passenger.Salutation = 'Mr.';
        passenger.PAXEmail = 'john.doe@test.com';
        passenger.Birthday = '1990-01-01';
        
        // ------------------------
        // Route
        // ------------------------
        PfaRequest.RouteEntry route = new PfaRequest.RouteEntry();
        route.BookingClass = 'Y';
        route.DepatureID = 'TPE';
        route.Depature = 'Taipei';
        route.ArrivalID = 'NRT';
        route.Arrival = 'Tokyo';
        route.FlightDate = '1990-01-01';
        route.FlightNo = 'BR198';
        
        // ------------------------
        // Request
        // ------------------------
        PfaRequest req = new PfaRequest();
        req.ActionCode = '0';
        req.applicantDept = 'ABCDEF123';
        req.applicantName = 'Tester';
        req.Qty = 1;
        req.Budget = 'In';
        req.Category = 'AD';
        req.Discount = '90';
        req.ApplicationType = 'Registered';
        
        req.Passenger = new List<PfaRequest.PassengerEntry>{ passenger };
        req.Route = new List<PfaRequest.RouteEntry>{ route };
        req.EmbargoPeriodTPE = new List<PfaRequest.EmbargoEntry>();
        req.EmbargoPeriodForeign = new List<PfaRequest.EmbargoEntry>();
        
        // ------------------------
        // Execute
        // ------------------------
        Test.startTest();
        ResponseModelPfa res = RestMiddlewarePfaApi.handlePfaRequest(req);
        Test.stopTest();
        
        // ------------------------
        // Assert
        // ------------------------
        
    }
    
    @IsTest
    static void testDeleteExternalTicketSuccess() {
        // ------------------------
        // Fetch setup data
        // ------------------------
        External_Tickets__c et = [
            SELECT Id, Ticket_Count__c, QuotaManageID__c, Budget_Type__c
            FROM External_Tickets__c
            LIMIT 1
        ];
        
        Quota_Manage__c quotaBefore = [
            SELECT Id, Quota_Transit__c
            FROM Quota_Manage__c
            WHERE Id = :et.QuotaManageID__c
            LIMIT 1
        ];
        
        // ------------------------
        // Request
        // ------------------------
        PfaRequest req = new PfaRequest();
        req.ActionCode = '2';
        req.sfId = et.Id;
        
        // ------------------------
        // Execute
        // ------------------------
        Test.startTest();
        ResponseModelPfa res = RestMiddlewarePfaApi.handlePfaRequest(req);
        Test.stopTest();
        
        // ------------------------
        // Assertions — response
        // ------------------------
        System.assertEquals(true, res.success);
        
        // ------------------------
        // Assertions — ticket deleted
        // ------------------------
        Integer countEt = [
            SELECT COUNT()
            FROM External_Tickets__c
            WHERE Id = :et.Id
        ];
        System.assertEquals(0, countEt, 'External ticket should be deleted');
        
        // ------------------------
        // Assertions — quota rolled back
        // ------------------------
        Quota_Manage__c quotaAfter = [
            SELECT Quota_Transit__c
            FROM Quota_Manage__c
            WHERE Id = :et.QuotaManageID__c
        ];
        
        System.assertEquals(
            quotaBefore.Quota_Transit__c - et.Ticket_Count__c,
            quotaAfter.Quota_Transit__c,
            'Quota transit should be rolled back'
        );
    }
    
    @IsTest
    static void testApproveFinalSuccess() {
        // ------------------------
        // Get setup data
        // ------------------------
        External_Tickets__c et = [
            SELECT Id, Ticket_Count__c, QuotaManageID__c, Budget_Type__c
            FROM External_Tickets__c
            LIMIT 1
        ];
        
        Quota_Manage__c quotaBefore = [
            SELECT Id, Quota_Used__c, Quota_Transit__c
            FROM Quota_Manage__c
            WHERE Id = :et.QuotaManageID__c
            LIMIT 1
        ];
        
        // ------------------------
        // Request
        // ------------------------
        PfaRequest req = new PfaRequest();
        req.ActionCode = '1';
        req.sfId = et.Id;
        req.serialID = 'SERIAL-001';
        req.LastApproverId = UserInfo.getUserId();
        req.LastApproverName = 'Final Approver';
        
        // ------------------------
        // Execute
        // ------------------------
        Test.startTest();
        ResponseModelPfa res = RestMiddlewarePfaApi.handlePfaRequest(req);
        Test.stopTest();
        
        // ------------------------
        // Assertions
        // ------------------------
        System.assertEquals(true, res.success, 'Approval should succeed');
        System.assertEquals(et.Id, res.data.recordId);
        
        External_Tickets__c etAfter = [
            SELECT Item_Status__c, SerialID__c, Last_Approver_Name__c
            FROM External_Tickets__c
            WHERE Id = :et.Id
        ];
        System.assertEquals('Approve (Final)', etAfter.Item_Status__c);
        System.assertEquals('SERIAL-001', etAfter.SerialID__c);
        
        Quota_Manage__c quotaAfter = [
            SELECT Quota_Used__c, Quota_Transit__c
            FROM Quota_Manage__c
            WHERE Id = :et.QuotaManageID__c
        ];
        
        System.assertEquals(
            quotaBefore.Quota_Used__c + et.Ticket_Count__c,
            quotaAfter.Quota_Used__c,
            'Quota used should increase'
        );
        System.assertEquals(
            quotaBefore.Quota_Transit__c - et.Ticket_Count__c,
            quotaAfter.Quota_Transit__c,
            'Quota transit should decrease'
        );
    }

    @IsTest
    static void testNoAccount() {
        PfaRequest req = new PfaRequest();
        req.ActionCode = '0';
        req.applicantDept = 'NOTEXIST';
        req.Budget = 'In';
        req.Qty = 1;
        req.ApplicationType = 'Anonymous';
        req.Passenger = new List<PfaRequest.PassengerEntry>();
        req.Route = new List<PfaRequest.RouteEntry>();
        req.EmbargoPeriodTPE = new List<PfaRequest.EmbargoEntry>();
        req.EmbargoPeriodForeign = new List<PfaRequest.EmbargoEntry>();

        ResponseModelPfa res = RestMiddlewarePfaApi.handlePfaRequest(req);

        System.assertEquals(false, res.success);
        System.assertEquals(400, res.message.code);
        System.assertEquals(
            'Bad Request, Department is not register in Salesforce.',
            res.message.content
        );
    }

    @IsTest
    static void testInsufficientQuota() {
        Account acc = createDepartmentAccount();
        createQuota(acc.Id);

        PfaRequest req = new PfaRequest();
        req.ActionCode = '0';
        req.applicantDept = acc.Department_Code__c;
        req.Budget = 'In';
        req.Qty = 999; // exceeds quota
        req.ApplicationType = 'Anonymous';
        req.Passenger = new List<PfaRequest.PassengerEntry>();
        req.Route = new List<PfaRequest.RouteEntry>();
        req.EmbargoPeriodTPE = new List<PfaRequest.EmbargoEntry>();
        req.EmbargoPeriodForeign = new List<PfaRequest.EmbargoEntry>();

        ResponseModelPfa res = RestMiddlewarePfaApi.handlePfaRequest(req);

        System.assertEquals(false, res.success);
        System.assertEquals(400, res.message.code);
    }

    @IsTest
    static void testUtilityMethods() {
        Date d = RestMiddlewarePfaApi.parseDate('2025-01-01');
        System.assertEquals(2025, d.year());

        String formatted = RestMiddlewarePfaApi.parseEmbargoDate('2025-01-01');
        System.assert(formatted.contains('JAN'));

        Boolean isThisYear = RestMiddlewarePfaApi.isThisYear('2025-01-01');
        System.assertEquals(true, isThisYear);
    }
    
    @IsTest
    static void testCreateExTicket_fullMapping_correctModel() {
    
        // Existing External Ticket to test sfId overwrite
        External_Tickets__c baseEt = new External_Tickets__c(
            Applicant_Name__c = 'Original'
        );
        insert baseEt;
    
        PfaRequest req = new PfaRequest();
    
        // ---- Identifiers
        req.sfId = baseEt.Id;
        req.identify = 'ID-123';
        req.requisitionID = 'REQ-001';
        req.serialID = 'SER-001';
        req.diagramID = 'DIA-001';
    
        // ---- Applicant
        req.applicantID = UserInfo.getUserId();
        req.applicantName = 'Ethan Lin';
        req.applicantDept = 'ABCDEF123';
        req.applicantDeptName = 'IT Department';
        req.applicantCompanyCode = 'TW01';
        req.applicantDateTime = '2025-01-01 10:30:00';
    
        // ---- Business Info
        req.Budget = 'In';
        req.CompanyName = 'Starlux Airlines';
        req.Reason = 'Business Travel';
        req.Category = 'AD';
        req.ApplyFor = 'Self';
        req.Discount = '90';
        req.Qty = 2;
        req.ApplicationType = 'Anonymous';
    
        // ---- Waiver Flags
        req.Waiver = 'YQ,Tax,YR,EP';
    
        // ---- Misc
        req.twoPeople = 'N';
        req.Winning = 'N';
        req.Language = 'EN';
        req.ExpirationDate = '2025-01-01';
        req.PhoneNo = '0912345678';
        req.Email = 'ethan@test.com';
        req.TicketReceiver = 'Ethan Lin';
    
        // ---- Approval
        req.LastApproverId = UserInfo.getUserId();
        req.LastApproverName = 'Manager A';
        req.OrganizerEventTitle = 'Annual Conference';

        PfaRequest.RouteEntry route = new PfaRequest.RouteEntry();
        route.BookingClass = 'Y';
        route.DepatureID = 'TPE';
        route.Depature = 'Taipei';
        route.ArrivalID = 'NRT';
        route.Arrival = 'Tokyo';
    
        req.Route = new List<PfaRequest.RouteEntry>{ route };

        PfaRequest.PassengerEntry pax = new PfaRequest.PassengerEntry();
        pax.Salutation = 'MR';
        pax.FirstName = 'Ethan';
        pax.LastName = 'Lin';
        pax.Birthday = '1990-01-01';
        pax.PAXEmail = 'ethan.pax@test.com';
    
        req.Passenger = new List<PfaRequest.PassengerEntry>{ pax };

        // ---- EmbargoPeriodTPE
        PfaRequest.EmbargoEntry tpeThisYear = new PfaRequest.EmbargoEntry();
        tpeThisYear.StartDate = '2025-10-11';
        tpeThisYear.EndDate   = '2025-10-11';
        
        PfaRequest.EmbargoEntry tpeNextYear = new PfaRequest.EmbargoEntry();
        tpeNextYear.StartDate = '2026-10-11';
        tpeNextYear.EndDate   = '2026-10-11';
        
        req.EmbargoPeriodTPE = new List<PfaRequest.EmbargoEntry>{
            tpeThisYear,
            tpeNextYear
        };
        
        // ---- EmbargoPeriodForeign
        PfaRequest.EmbargoEntry foreignThisYear = new PfaRequest.EmbargoEntry();
        foreignThisYear.StartDate = '2025-10-11';
        foreignThisYear.EndDate   = '2025-10-11';
        
        req.EmbargoPeriodForeign = new List<PfaRequest.EmbargoEntry>{
            foreignThisYear
        };

        External_Tickets__c et =
            RestMiddlewarePfaApi.createExTicket(req);
    
        // Identity
        System.assertEquals(baseEt.Id, et.Id);
        System.assertEquals('Ethan Lin', et.Applicant_Name__c);
        System.assertEquals('ABCDEF123', et.Applicant_Dept__c);
    
        // Business
        System.assertEquals('In', et.Budget_Type__c);
        System.assertEquals(2, et.Ticket_Count__c);
        System.assertEquals('AD', et.Fare_Basis__c);
    
        // Waiver flags
        System.assertEquals(true, et.Exemption_YQ__c);
        System.assertEquals(true, et.Exemption_Tax__c);
        System.assertEquals(true, et.Exemption_YR__c);
        System.assertEquals(true, et.Embargo__c);
    
        // Route mapping
        System.assertEquals('Y', et.Booking_Class__c);
        System.assertEquals('TPE', et.DepatureID__c);
        System.assertEquals('NRT', et.ArrivalID__c);
    
        // Embargo mapping
        System.assertNotEquals(null, et.Embargo_This_Year_Taiwan_to_World__c);
        System.assertNotEquals(null, et.Embargo_Next_Year_Taiwan_to_World__c);
        System.assertNotEquals(null, et.Embargo_This_Year_World_to_Taiwan__c);
    
        // New field
        System.assertEquals(
            'Annual Conference',
            et.Organizer_Event_Title__c
        );
    }*/
    
    @IsTest
    static void fakeTest() {
        RestMiddlewarePfaApi.fakeMethod();
        PfaData.fakeMethod();
        PfaRequest.fakeMethod();
        ResponseModelPfa.fakeMethod();
        PfaResponseModel.fakeMethod();
    }
}