force-app/main/default/objects/External_Tickets__c/External_Tickets__c.object-meta.xml
<CustomObject>
    <label>External Tickets</label>
    <nameField>
        <label>External Tickets</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>External Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Certificate__c/Ticket_Certificate__c.object-meta.xml
<CustomObject>
    <label>Ticket Certificate</label>
    <nameField>
        <label>Ticket No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Certificates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Certificate__c/fields/External_Tickets__c.field-meta.xml
<CustomField>
    <fullName>External_Tickets__c</fullName>
    <label>External Tickets</label>
    <referenceTo>External_Tickets__c</referenceTo>
    <relationshipName>Ticket_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TicketCertificateControllerTest.cls
@isTest
private class TicketCertificateControllerTest {
	@isTest 
    private static void testMethod1() {
        External_Tickets__c externalTicket = new External_Tickets__c();
        insert externalTicket;
        
        Ticket_Certificate__c ticketCertificate = new Ticket_Certificate__c(Name ='Test', External_Tickets__c = externalTicket.Id);
        insert ticketCertificate;
        
        PageReference pageRef = Page.Ticket_BarterTickets_PDF;
        Test.setCurrentPage(pageRef);
        
        pageRef.getParameters().put('Id', String.valueOf(ticketCertificate.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(ticketCertificate);
        TicketCertificateController testController = new TicketCertificateController(sc);
        ApexPages.StandardController std = NULL;
	}
}