force-app/main/default/objects/Payment_Deposit_Fine_Details__c/Payment_Deposit_Fine_Details__c.object-meta.xml
<CustomObject>
    <label>Payment / Deposit / Fine Details</label>
    <nameField>
        <displayFormat>PDD-{YYYY}{MM}{00000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment / Deposit / Fine Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment / Deposit / Fine Details</relationshipLabel>
    <relationshipName>Payment_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <description>Master-detail to case object to associate/roll up payment details to case object</description>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Payment / Deposit / Fine Details</relationshipLabel>
    <relationshipName>Payment_Deposit_Fine_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/fields/Cheque_Clearance_Date__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Clearance_Date__c</fullName>
    <label>Cheque Clearance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/fields/Cheque_Issuance_Date__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Issuance_Date__c</fullName>
    <label>Cheque Issuance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/fields/Cheque_No__c.field-meta.xml
<CustomField>
    <fullName>Cheque_No__c</fullName>
    <label>Cheque No.</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
                <isActive>false</isActive>
                <label>Deposit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/fields/Replenishment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Replenishment_Amount__c</fullName>
    <label>Replenishment Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deposit Required</fullName>
            </value>
            <value>
                <fullName>Deposit Received</fullName>
            </value>
            <value>
                <fullName>Deposit Reviewed</fullName>
            </value>
            <value>
                <fullName>Deposit Returned</fullName>
            </value>
            <value>
                <fullName>Deposit Cancel</fullName>
            </value>
            <value>
                <fullName>Fine Required</fullName>
            </value>
            <value>
                <fullName>Fine Received</fullName>
            </value>
            <value>
                <fullName>Fine Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Deposit_Fine_Details__c/recordTypes/Payment.recordType-meta.xml
<RecordType>
    <fullName>Payment</fullName>
    <active>true</active>
    <label>Payment</label>
</RecordType>

force-app/main/default/objects/Replenishment__c/Replenishment__c.object-meta.xml
<CustomObject>
    <description>回補額度紀錄</description>
    <label>Replenishment</label>
    <nameField>
        <displayFormat>RE{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>Replenishment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Replenishment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Replenishment__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>旅行社名稱</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Replenishment</relationshipLabel>
    <relationshipName>Account_Replenishment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Replenishment__c/fields/Business_Number__c.field-meta.xml
<CustomField>
    <fullName>Business_Number__c</fullName>
    <description>統一編號</description>
    <formula>AccountId__r.Business_Number__c</formula>
    <label>Business Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Replenishment__c/fields/Replenishment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Replenishment_Amount__c</fullName>
    <description>回補金額</description>
    <label>Replenishment Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SapReceiveChequeStatusApi_Test.cls
@IsTest
public class SapReceiveChequeStatusApi_Test {
    @TestSetup
    public static void SetupData(){
        Account fakeAccount = new Account();
        fakeAccount.Name = 'Aaron';
        fakeAccount.Credit_Balance__c = 3000000;
        fakeAccount.Status__c = 'Active';
        fakeAccount.Business_Number__c = 'AaronTest';
        Insert fakeAccount;
        
        Case fakeCase = new Case();
        fakeCase.Status = 'Waiting for Payment';
        Insert fakeCase;
                
        Replenishment__c  fakeReplenishment = new Replenishment__c();
        fakeReplenishment.AccountId__c = fakeAccount.Id;
        fakeReplenishment.Replenishment_Amount__c = 3000000;
		INSERT fakeReplenishment;
        
        System.debug([SELECT Credit_Balance__c, Credit_Balance2__c FROM Account WHERE Id= : fakeAccount.Id]);
        
        Id PaymentRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Payment' and SObjectType = 'Payment_Deposit_Fine_Details__c'].Id;
        
        Payment_Deposit_Fine_Details__c fakeData = new Payment_Deposit_Fine_Details__c();
        fakeData.RecordTypeId = PaymentRecordTypeId;
        fakeData.Case_ID__c = fakeCase.Id;
        fakeData.Account_ID__c = fakeAccount.Id;
        fakeData.Cheque_No__c = 'Y123456';
        fakeData.Payment_Mode__c = 'Cheque';
        fakeData.Payment_Amount__c = 234220.0;
        fakeData.Cheque_Clearance_Date__c = Date.today();
        fakeData.Cheque_Issuance_Date__c = Date.today();
		INSERT fakeData;
    }
    
	@IsTest
    static void receiveChequeStatusApi_Test() {
        Map<String, String> fakeCheque = new Map<String, String> {'businessNumber' => 'AaronTest', 'chequeNo' => 'Y123456', 'chequeStatus' => 'Cashed', 'amount' => '234220.0'};
        List<Map<String, String>> fakeCheques = new List<Map<String, String>>();
        fakeCheques.add(fakeCheque);
        
        String JsonMsg=JSON.serialize(fakeCheques);
        
        SapResponseChequeStatusWrapper.deserializeJson(JsonMsg);
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        req.requestURI = '/receive/chequeStatus';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JsonMsg);
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        SapReceiveChequeStatusApi.receiveChequeStatusApi();
        //ResponseResultModel resultModel = RestLoginApi.login('123456', '1234qwer');
        Test.stopTest();
    }
}