force-app/main/default/objects/UserManagement__c/UserManagement__c.object-meta.xml
<CustomObject>
    <description>B2B平台使用者帳號</description>
    <label>User Management</label>
    <nameField>
        <displayFormat>JX{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserManagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>請輸入至少8個字元，且僅限英文字、數字、特殊字元</inlineHelpText>
    <label>Account</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserManagement__c/fields/CN_Passport__c.field-meta.xml
<CustomField>
    <fullName>CN_Passport__c</fullName>
    <label>Chinese Passport</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserManagement__c/fields/EN_Passport__c.field-meta.xml
<CustomField>
    <fullName>EN_Passport__c</fullName>
    <label>English Passport</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserManagement__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <defaultValue>&quot;Starlux#2020&quot;</defaultValue>
    <label>Password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserManagement__c/fields/Resend__c.field-meta.xml
<CustomField>
    <fullName>Resend__c</fullName>
    <defaultValue>true</defaultValue>
    <description>勾選觸發產生帳號驗證連結並寄信</description>
    <inlineHelpText>勾選觸發產生帳號驗證連結並寄信</inlineHelpText>
    <label>Resend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserManagement__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>先生</fullName>
            </value>
            <value>
                <fullName>女士</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/B2BTempTest.cls
@isTest
public class B2BTempTest {
    @isTest static void userManagment() {
        UserManagement__c newUser = new UserManagement__c(
            Email__c = 'testuser@example.com',
            Account__c = '1234567800',
            CN_Passport__c = '育瑋', 
            EN_Passport__c = 'Aaronabc', 
            Salutation__c = '先生',
            Resend__c = false,
            password__c = 'Jet..%13239686'
        );
        
        Test.startTest();
        insert newUser;
        Test.stopTest();
    }
    
    @isTest static void testMethods() {
        AmadeusUtil.fakeMethod();
        AirRetrieveSeatMap.fakeMethod();
        AmadeusUtilDCS.fakeMethod();
        AmadeusUtilRetrieveSeatMap.fakeMethod();
        AmadeusXmlParser.fakeMethod();
        AccountMaintainController.fakeMethod();
        AccountManagementController.fakeMethod();
        AutoLogoutController.fakeMethod();
        BoardingPassPDFController.fakeMethod();
        BoardingPassPrintingController.fakeMethod();
        B2BForgotPasswordController.fakeMethod();
        CheckINController.fakeMethod();
        CheckINReportPDFController.fakeMethod();
        CheckInReportController.fakeMethod();
        CommonController.fakeMethod();
        EditTravelerController.fakeMethod();
        EmailTemplateHelper.fakeMethod();
        HOME_Controller.fakeMethod();
        HistoryLogController.fakeMethod();
        LoginUtility.fakeMethod();
        LoginController.fakeMethod();
        InfobipUtility.fakeMethod();
        MessageResponse.fakeMethod();
        NavbarController.fakeMethod();
        OperationHistoryUtil.fakeMethod();
        PassengerDataWrapper.fakeMethod();
        PageUtility.fakeMethod();
        ResetPasswordController.fakeMethod();
        SeatSelectionController.fakeMethod();
        UserUtilities.fakeMethod();
    }
}