force-app/main/default/objects/CGD_Contract__c/CGD_Contract__c.object-meta.xml
<CustomObject>
    <description>For CGD</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CGD_Contract__c/fields/Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Code__c</fullName>
    <description>簽約客戶</description>
    <label>Account Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.CGD_Account_For__c</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CGD_Contract__c/recordTypes/Global_Region_Incentive.recordType-meta.xml
<RecordType>
    <fullName>Global_Region_Incentive</fullName>
    <active>true</active>
    <description>激勵佣金方案</description>
    <label>Global/Region Incentive</label>
</RecordType>

force-app/main/default/objects/CGD_Join_Account__c/CGD_Join_Account__c.object-meta.xml
<CustomObject>
    <description>For CGD</description>
    <label>Join Account</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Join Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Join Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CGD_Join_Account__c/fields/Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Code__c</fullName>
    <label>Account Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Join Accounts</relationshipLabel>
    <relationshipName>Join_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/CGD_Join_Account__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>CGD_Contract__c</referenceTo>
    <relationshipLabel>Join Accounts</relationshipLabel>
    <relationshipName>Join_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/CGD_Sub_Contract__c.object-meta.xml
<CustomObject>
    <description>BSA各航線/月份目標值</description>
    <label>Sub-Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>CGD_Contract__c</referenceTo>
    <relationshipLabel>Sub-Contracts</relationshipLabel>
    <relationshipName>Sub_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Incentive_Destination_Airport__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Destination_Airport__c</fullName>
    <description>For Calculate</description>
    <label>Incentive Destination Airport</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Incentive_Origin_Airport__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Origin_Airport__c</fullName>
    <description>For Calculate</description>
    <label>Incentive Origin Airport</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Target_Month__c.field-meta.xml
<CustomField>
    <fullName>Target_Month__c</fullName>
    <description>合約目標月份</description>
    <inlineHelpText>合約目標月份</inlineHelpText>
    <label>Target Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Target_Year__c.field-meta.xml
<CustomField>
    <fullName>Target_Year__c</fullName>
    <label>Target Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/recordTypes/Sub_Contract_Incentive.recordType-meta.xml
<RecordType>
    <fullName>Sub_Contract_Incentive</fullName>
    <active>true</active>
    <description>Sub-Contract - Incentive</description>
    <label>Sub-Contract - Incentive</label>
</RecordType>

force-app/main/default/classes/Batch_CalculateContractIncentive.cls
/*******************************************************************
Description: This class is used to calculate Contract Incentive.
Database.executeBatch(new Batch_CalculateContractIncentive(), 1);
*******************************************************************/
global class Batch_CalculateContractIncentive extends BatchMaster implements Database.Batchable < sObject > , Database.Stateful {
    global String query;
    public Id contractRecordTypeId = Schema.SObjectType.CGD_Contract__c.getRecordTypeInfosByDeveloperName().get('Global_Region_Incentive').getRecordTypeId();
    public Id subRecordTypeId = Schema.SObjectType.CGD_Sub_Contract__c.getRecordTypeInfosByDeveloperName().get('Sub_Contract_Incentive').getRecordTypeId();
    
    global Batch_CalculateContractIncentive() {
        this.query = 'SELECT Id, Account_Code__r.Name, ' +
            '(SELECT Id, Incentive_Origin_Airport__c, Incentive_Destination_Airport__c, Target_Year__c, Target_Month__c ' +
            'FROM Sub_Contracts__r WHERE RecordTypeId = :subRecordTypeId), ' +
            '(SELECT Id, Account_Code__r.Name ' +
            'FROM Join_Accounts__r) ' +
            'FROM CGD_Contract__c ' +
            'WHERE Id IN (SELECT Contract__c FROM CGD_Sub_Contract__c WHERE RecordTypeId = :subRecordTypeId) AND RecordTypeId = :contractRecordTypeId';
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List <CGD_Contract__c> records) {
        for (CGD_Contract__c contract : records) {
            List<CGD_Sub_Contract__c> subs = contract.Sub_Contracts__r;
            List<CGD_Join_Account__c> joins = contract.Join_Accounts__r;
            
            if (subs == null || joins == null) continue;
            
            List<String> joinNames = new List<String>();
            if (contract.Account_Code__r.Name != null) joinNames.add(contract.Account_Code__r.Name);
            
            for (CGD_Join_Account__c joinAcc : joins) {
                if (joinAcc.Account_Code__r != null) joinNames.add(joinAcc.Account_Code__r.Name);
            }

            System.enqueueJob(new Queue_CalculateContractIncentive(subs, joinNames));
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
    
 
}