force-app/main/default/objects/Ticket_Certificate__c/Ticket_Certificate__c.object-meta.xml
<CustomObject>
    <label>Ticket Certificate</label>
    <nameField>
        <label>Ticket No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Certificates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Certificate__c/fields/Coupon_Number__c.field-meta.xml
<CustomField>
    <fullName>Coupon_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Coupon Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/QRcode__c.field-meta.xml
<CustomField>
    <fullName>QRcode__c</fullName>
    <formula>&apos;https://api.qrserver.com/v1/create-qr-code/?size=150x150&amp;data=&apos;+ Full_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QRcode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket_Certificate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Exchanged</fullName>
                <default>true</default>
                <label>Not Exchanged</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Booking In Progress</fullName>
            </value>
            <value>
                <fullName>Booking Confirmed (HK)</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QRcodeScanController.cls
public class QRcodeScanController {
    public String scannedValue { get; set; }
    public String errorMessage { get; set; }
    public String couponNumber { get; set; }
    public Ticket_Certificate__c ticket { get; set; }
    
    public QRcodeScanController() {
        
    }
    
    public void afterScan() {
		scannedValue = ApexPages.currentPage().getParameters().get('scannedValue');
        System.debug(scannedValue);
        
        List<Ticket_Certificate__c> tickets = [SELECT Id, Coupon_Number__c, Status__c, QRcode__c
                   FROM Ticket_Certificate__c
                   WHERE Id = : scannedValue LIMIT 1];
        
        if(tickets.size() == 0) {
            errorMessage = 'No Coupon Number!!!';
        } else {
            Ticket_Certificate__c ticket = tickets[0];
            if(ticket.Status__c != 'Not Exchanged') {
                errorMessage = 'Coupon has Already been Exchanged!!!';
            } else {
                couponNumber = ticket.Coupon_Number__c;
                ticket.Status__c = 'In Progress';
                update ticket;
            }
        }
    }
    
    public static void fakeMethod() {
        Integer i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
    }
}