force-app/main/default/objects/Seat_Sales_Tracking__c/Seat_Sales_Tracking__c.object-meta.xml
<CustomObject>
    <label>Seat Sales Tracking</label>
    <nameField>
        <displayFormat>ST{YYYY}{MM}{00000000}</displayFormat>
        <label>Sales Tracking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Sales Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Sales_Tracking__c/fields/Case_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_ID__c</fullName>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Seat Sales Trackings</relationshipLabel>
    <relationshipName>Sales_Trackings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Seat_Sales_Tracking__c/fields/Departing_Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Departing_Flight_Date__c</fullName>
    <formula>Case_ID__r.Departing_Flight_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departing Flight Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Seat_Sales_Tracking__c/fields/Departing_Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Departing_Flight_Number__c</fullName>
    <formula>Case_ID__r.Departing_Flight_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departing Flight Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Sales_Tracking__c/fields/Returning_Flight_Date__c.field-meta.xml
<CustomField>
    <fullName>Returning_Flight_Date__c</fullName>
    <formula>Case_ID__r.Returning_Flight_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Returning Flight Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Seat_Sales_Tracking__c/fields/Returning_Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Returning_Flight_Number__c</fullName>
    <formula>Case_ID__r.Returning_Flight_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Returning Flight Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seat_Sales_Tracking__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <formula>Text(Case_ID__r.Route__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Route</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteSSTTest.cls
@isTest (SeeAllData=true)
private class DeleteSSTTest {

    @isTest static void testDeleteSST() {
		//Date thisDate = Date.today();
        //Id caseRecord = [SELECT Id,ContactId,Departing_Flight_Date__c FROM Case where Status = 'Ticket Issued' AND Departing_Flight_Date__c < 2024-05-28 Limit 1].Id;
		Id newCaseId = createNewCase();        
        //List<Seat_Sales_Tracking__c> testRecords = new List<Seat_Sales_Tracking__c>();
        //for(Integer i=0; i<2; i++) {
           //testRecords.add(new Seat_Sales_Tracking__c(Case_ID__c = caseRecord));
        //}
        //insert testRecords;

        // Call the batch class
        Test.startTest();
        Database.executeBatch(new DeleteSST(),200);
        Test.stopTest();
        
    }
    
    private static Id createNewCase(){

        Id accountRT = [SELECT Id FROM RecordType WHERE Name = 'Travel Agency' ].Id;
        Id accountId = [SELECT Id FROM Account WHERE RecordTypeId =: accountRT LIMIT 1].Id;
        Id contactId = [SELECT Id FROM Contact WHERE AccountId =: accountId LIMIT 1].Id;
        Id caseRT = [SELECT Id FROM RecordType WHERE Name = 'Group Booking'].Id;
        
        Case testCase = new Case();
        testCase.AccountId = accountId;
        testCase.ContactId = contactId;
        testCase.RecordTypeId = caseRT;
        testCase.Departing_Flight_Number__c = 'JX701';
        testCase.Returning_Flight_Number__c = 'JX702';
        testCase.Departing_Flight_Date__c = Date.today().addDays(-14);
        testCase.Departing_Flight_Arrival_Date__c = Date.today().addDays(-14);
        testCase.Returning_Flight_Date__c = Date.today().addDays(-7);
        testCase.Returning_Flight_Arrival_Date__c = Date.today().addDays(-7);
        testCase.Route__c = 'TPE-DAD-TPE';
        testCase.Status = 'Ticket Issued';
        Insert testCase;
        return testCase.Id;
    }

}