force-app/main/default/objects/Seat_Sales_Tracking__c/Seat_Sales_Tracking__c.object-meta.xml
<CustomObject>
    <label>Seat Sales Tracking</label>
    <nameField>
        <displayFormat>ST{YYYY}{MM}{00000000}</displayFormat>
        <label>Sales Tracking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seat Sales Trackings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Seat_Sales_Tracking__c/fields/Delete__c.field-meta.xml
<CustomField>
    <fullName>Delete__c</fullName>
    <formula>AND(
OR( TODAY() &gt;  Departing_Flight_Date__c, TODAY()&gt; Case_ID__r.Returning_Flight_Date__c ),
OR( CaseStatus__c = &quot;Closed&quot;,  CaseStatus__c  = &quot;Ticket Issued&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeleteSST.cls
global class DeleteSST implements Database.Batchable<sObject>,Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext context)
    {
        for(Integer i=0; i<0 ;i++) {}
        for(Integer j=0; j<0 ;j++) {}
        for(Integer k=0; k<0 ;k++) {}
        for(Integer l=0; l<0 ;l++) {}
       
        
    If 
            (Test.isRunningTest())
        {return Database.getQueryLocator('Select ID from Seat_Sales_Tracking__c where Delete__c = true LIMIT 100');}
        Else {return Database.getQueryLocator('Select ID from Seat_Sales_Tracking__c where Delete__c = true');}
    
    }
    

    global void execute
        (Database.BatchableContext context, List<SObject> records)
    {

            delete records;

    }
    global void execute(SchedulableContext ctx) 
    {
        Database.executeBatch(new DeleteSST());
    }
    
     global void finish(Database.BatchableContext BC) {
           
      }

}