force-app/main/default/objects/CGD_Join_Account__c/CGD_Join_Account__c.object-meta.xml
<CustomObject>
    <description>For CGD</description>
    <label>Join Account</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Join Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Join Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CGD_Raw_Data__c/CGD_Raw_Data__c.object-meta.xml
<CustomObject>
    <label>Raw Data</label>
    <nameField>
        <label>Raw Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raw Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CGD_Raw_Data__c/fields/CGD_Sub_Contract__c.field-meta.xml
<CustomField>
    <fullName>CGD_Sub_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CGD Sub-Contract</label>
    <referenceTo>CGD_Sub_Contract__c</referenceTo>
    <relationshipLabel>Raw Datas</relationshipLabel>
    <relationshipName>Raw_Datas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CGD_Raw_Data__c/fields/Chargeable_Weight_in_kg__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Weight_in_kg__c</fullName>
    <label>Chargeable Weight in kg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CGD_Raw_Data__c/fields/Incentive_All_All_Key__c.field-meta.xml
<CustomField>
    <fullName>Incentive_All_All_Key__c</fullName>
    <formula>IF(Source__c=&apos;Incentive&apos;,
Account_Code__c
&amp;&quot;_All_All_&quot;&amp;

First_JX_Flight_Year__c,
&apos;&apos;
)</formula>
    <label>Incentive All All Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CGD_Raw_Data__c/fields/Incentive_All_Destination_Key__c.field-meta.xml
<CustomField>
    <fullName>Incentive_All_Destination_Key__c</fullName>
    <formula>IF(Source__c=&apos;Incentive&apos;,
Account_Code__c
&amp;&quot;_All_&quot;&amp;
Destination_Airport__c&amp;&quot;_&quot;&amp;
First_JX_Flight_Year__c,
&apos;&apos;
)</formula>
    <label>Incentive All Destination Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CGD_Raw_Data__c/fields/Incentive_Key__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Key__c</fullName>
    <formula>IF(Source__c=&apos;Incentive&apos;,
Account_Code__c&amp;&quot;_&quot;&amp;
Origin_Airport__c&amp;&quot;_&quot;&amp;
Destination_Airport__c&amp;&quot;_&quot;&amp;
First_JX_Flight_Year__c,
&apos;&apos;
)</formula>
    <label>Incentive Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CGD_Raw_Data__c/fields/Incentive_Origin_All_Key__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Origin_All_Key__c</fullName>
    <formula>IF(Source__c=&apos;Incentive&apos;,
Account_Code__c&amp;&quot;_&quot;&amp;
Origin_Airport__c
&amp;&quot;_All_&quot;&amp;
First_JX_Flight_Year__c,
&apos;&apos;
)</formula>
    <label>Incentive Origin All Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CGD_Raw_Data__c/recordTypes/Contract_Incentive.recordType-meta.xml
<RecordType>
    <fullName>Contract_Incentive</fullName>
    <active>true</active>
    <label>Contract - Incentive</label>
</RecordType>

force-app/main/default/objects/CGD_Sub_Contract__c/CGD_Sub_Contract__c.object-meta.xml
<CustomObject>
    <description>BSA各航線/月份目標值</description>
    <label>Sub-Contract</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Actual_Chargeable_Weight__c.field-meta.xml
<CustomField>
    <fullName>Actual_Chargeable_Weight__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Chargeable Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Incentive_Destination_Airport__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Destination_Airport__c</fullName>
    <description>For Calculate</description>
    <label>Incentive Destination Airport</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Incentive_Origin_Airport__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Origin_Airport__c</fullName>
    <description>For Calculate</description>
    <label>Incentive Origin Airport</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Target_Month__c.field-meta.xml
<CustomField>
    <fullName>Target_Month__c</fullName>
    <description>合約目標月份</description>
    <inlineHelpText>合約目標月份</inlineHelpText>
    <label>Target Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CGD_Sub_Contract__c/fields/Target_Year__c.field-meta.xml
<CustomField>
    <fullName>Target_Year__c</fullName>
    <label>Target Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Queue_CalculateContractIncentive.cls
public class Queue_CalculateContractIncentive implements Queueable {
    public List<CGD_Sub_Contract__c> subs;
    //public List<CGD_Join_Account__c> joins;
    public List<String> joinNames;
    public Id recordTypeId = Schema.SObjectType.CGD_Raw_Data__c.getRecordTypeInfosByDeveloperName().get('Contract_Incentive').getRecordTypeId();
    
    
    public Queue_CalculateContractIncentive(List<CGD_Sub_Contract__c> subs, List<String> joinNames) {
        this.subs = subs;
        this.joinNames = joinNames;
    }
    
    public void execute(QueueableContext context) {
        try {
            if (!(subs.isEmpty() || joinNames.isEmpty())) {
                List<String> externalKeys = new List<String>();
                CGD_Sub_Contract__c sub = subs[0];
                for (String joinAccName : joinNames) {
                    String accountCode = joinAccName;
                    String airports = sub.Incentive_Origin_Airport__c != null ? sub.Incentive_Origin_Airport__c : '';
                    String dest = sub.Incentive_Destination_Airport__c != null ? sub.Incentive_Destination_Airport__c : '';
					String yearStr = sub.Target_Year__c != null ? String.valueOf(sub.Target_Year__c) : '';
                    //String monthStr = sub.Target_Month__c != null ? String.valueOf(sub.Target_Month__c) : '';
                    
                    for (String airport : airports.split(';')) {
                        for (String des : dest.split(';')) {
                            String key = String.join(
                                new List<String>{accountCode, airport, des, yearStr},
                                '_'
                            );
                            externalKeys.add(key);
                        }
                    }
                  
                    
                    AggregateResult[] results = [
                        /* 2025/11/14 針對有All的組法新增Raw Data三種有All的Key值組合。因為如果用Flow Mapping全部場站都要塞到Incentive欄位裡面，會有9420個場站名稱要塞，欄位塞不下，Flow也跑不動。
                        SELECT SUM(Chargeable_Weight_in_kg__c) sumTotal
                        FROM CGD_Raw_Data__c 
                        WHERE RecordTypeId = :recordTypeId AND Incentive_Key__c IN :externalKeys AND LastModifiedDate = TODAY
						*/
                        
                        SELECT SUM(Chargeable_Weight_in_kg__c) sumTotal
                        FROM CGD_Raw_Data__c 
                        WHERE RecordTypeId = :recordTypeId 
                          AND (Incentive_Key__c IN :externalKeys
                             OR Incentive_All_Destination_Key__c IN :externalKeys
                             OR Incentive_All_All_Key__c IN :externalKeys
                             OR Incentive_Origin_All_Key__c IN :externalKeys)
                          
                    ];
                    
                    //Decimal total = (Decimal)results[0].get('sumTotal'); 2025/11/14 調整沒有抓到值null，回傳0
                    Decimal total = (results.size() > 0 && results[0].get('sumTotal') != null)? (Decimal)results[0].get('sumTotal') : 0;

                    
                    update new CGD_Sub_Contract__c(Id = sub.Id, Actual_Chargeable_Weight__c = total);
                }
                
                subs.remove(0);
            }
            
			if (!subs.isEmpty()) System.enqueueJob(new Queue_CalculateContractIncentive(subs, joinNames));            
        } catch (Exception e) {
            
        }
    }
}