force-app/main/default/objects/Airport_Operation__c/Airport_Operation__c.object-meta.xml
<CustomObject>
    <description>Custom object storing flight schedule for airport operation</description>
    <label>Airport Operation</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airport Operation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airport_Operation__c/fields/ARR__c.field-meta.xml
<CustomField>
    <fullName>ARR__c</fullName>
    <label>ARR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Airport_Location</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/Arrival_Flight_Date_Local__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Flight_Date_Local__c</fullName>
    <label>ARR Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/Arrival_Flight_Date_UTC__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Flight_Date_UTC__c</fullName>
    <label>Arrival Flight Date(UTC)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/Departure_Flight_Date_Local__c.field-meta.xml
<CustomField>
    <fullName>Departure_Flight_Date_Local__c</fullName>
    <label>DEP Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/Departure_Flight_Date_UTC__c.field-meta.xml
<CustomField>
    <fullName>Departure_Flight_Date_UTC__c</fullName>
    <label>Departure Flight Date(UTC)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETA_Date_Local__c.field-meta.xml
<CustomField>
    <fullName>ETA_Date_Local__c</fullName>
    <label>ETA Date(Local)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETA_Date_UTC__c.field-meta.xml
<CustomField>
    <fullName>ETA_Date_UTC__c</fullName>
    <label>ETA Date(UTC)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETA_Offset__c.field-meta.xml
<CustomField>
    <fullName>ETA_Offset__c</fullName>
    <label>ETA Offset</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETA_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>ETA_Time_Local__c</fullName>
    <label>ETA</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETA_Time_UTC__c.field-meta.xml
<CustomField>
    <fullName>ETA_Time_UTC__c</fullName>
    <label>ETA Time(UTC)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETD_Date_Local__c.field-meta.xml
<CustomField>
    <fullName>ETD_Date_Local__c</fullName>
    <label>ETD Date(Local)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETD_Date_UTC__c.field-meta.xml
<CustomField>
    <fullName>ETD_Date_UTC__c</fullName>
    <label>ETD Date(UTC)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETD_Offset__c.field-meta.xml
<CustomField>
    <fullName>ETD_Offset__c</fullName>
    <label>ETD Offset</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETD_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>ETD_Time_Local__c</fullName>
    <label>ETD</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/ETD_Time_UTC__c.field-meta.xml
<CustomField>
    <fullName>ETD_Time_UTC__c</fullName>
    <label>ETD Time(UTC)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/FLT_Carrier__c.field-meta.xml
<CustomField>
    <fullName>FLT_Carrier__c</fullName>
    <label>Flight Carrier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/STA_Date_Local__c.field-meta.xml
<CustomField>
    <fullName>STA_Date_Local__c</fullName>
    <label>STA Date(Local)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/STA_Date_UTC__c.field-meta.xml
<CustomField>
    <fullName>STA_Date_UTC__c</fullName>
    <label>STA Date(UTC)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/STA_TIme_Local__c.field-meta.xml
<CustomField>
    <fullName>STA_TIme_Local__c</fullName>
    <label>STA</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/STA_Time_UTC__c.field-meta.xml
<CustomField>
    <fullName>STA_Time_UTC__c</fullName>
    <label>STA Time(UTC)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/STD_Date_Local__c.field-meta.xml
<CustomField>
    <fullName>STD_Date_Local__c</fullName>
    <label>STD Date(Local)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/STD_Date_UTC__c.field-meta.xml
<CustomField>
    <fullName>STD_Date_UTC__c</fullName>
    <label>STD Date(UTC)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/STD_Time_Local__c.field-meta.xml
<CustomField>
    <fullName>STD_Time_Local__c</fullName>
    <label>STD</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Airport_Operation__c/fields/STD_Time_UTC__c.field-meta.xml
<CustomField>
    <fullName>STD_Time_UTC__c</fullName>
    <label>STD Time(UTC)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/Airport_Operation_Checklist__mdt.object-meta.xml
<CustomObject>
    <description>Stores all the parameters for the mandatory checklist records for each airport operation record</description>
    <label>Airport Operation Checklist</label>
    <pluralLabel>Airport Operation Checklists</pluralLabel>
</CustomObject>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/fields/EstimatedEndBase__c.field-meta.xml
<CustomField>
    <fullName>EstimatedEndBase__c</fullName>
    <description>Describes the date time field to be used from the parent record to use for the estimated complete base time calculation</description>
    <label>Estimated End Base</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/fields/EstimatedEndOffset__c.field-meta.xml
<CustomField>
    <fullName>EstimatedEndOffset__c</fullName>
    <description>Describes the time duration offset for the estimated complete time for the checklist record</description>
    <label>Estimated End Offset</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/fields/EstimatedStartBase__c.field-meta.xml
<CustomField>
    <fullName>EstimatedStartBase__c</fullName>
    <description>Describe the estimated start date time field to be used from the Airport Operation record</description>
    <label>Estimated Start Base</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/fields/EstimatedStartOffset__c.field-meta.xml
<CustomField>
    <fullName>EstimatedStartOffset__c</fullName>
    <description>Describes the time duration offset for the estimated start time of the checklist record</description>
    <label>Estimated Start Offset</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/fields/GroupInCharge__c.field-meta.xml
<CustomField>
    <fullName>GroupInCharge__c</fullName>
    <description>Describes the group which is in charge of the checklist record</description>
    <label>Group In Charge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ROS</fullName>
                <default>true</default>
                <label>ROS</label>
            </value>
            <value>
                <fullName>CIQ</fullName>
            </value>
            <value>
                <fullName>LCS</fullName>
            </value>
            <value>
                <fullName>GPS</fullName>
            </value>
            <value>
                <fullName>CCS</fullName>
            </value>
            <value>
                <fullName>Acars</fullName>
            </value>
            <value>
                <fullName>LNF</fullName>
            </value>
            <value>
                <fullName>GHD</fullName>
            </value>
            <value>
                <fullName>OPS+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/fields/ListOrder__c.field-meta.xml
<CustomField>
    <fullName>ListOrder__c</fullName>
    <description>Describes the sequence order of the checklist record</description>
    <label>List Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/fields/ScheduleType__c.field-meta.xml
<CustomField>
    <fullName>ScheduleType__c</fullName>
    <description>Describes whether the flight operation is &apos;Arrival&apos; or &apos;Departure&apos;</description>
    <label>Schedule Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <description>Describes whether the checklist record belongs to &apos;Above Wing&apos; or &apos;Below Wing&apos;</description>
    <label>Site</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Airport_Operation_Checklist__mdt/fields/StageName__c.field-meta.xml
<CustomField>
    <fullName>StageName__c</fullName>
    <description>Describes the stage name of the checklist record</description>
    <label>Stage Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arrival_Checklist__c/Arrival_Checklist__c.object-meta.xml
<CustomObject>
    <label>Arrival Checklist</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Arrival Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Arrival_Checklist__c/fields/Airport_Operation_ID__c.field-meta.xml
<CustomField>
    <fullName>Airport_Operation_ID__c</fullName>
    <label>Airport Operation ID</label>
    <referenceTo>Airport_Operation__c</referenceTo>
    <relationshipLabel>Arrival Checklists</relationshipLabel>
    <relationshipName>Arrival_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Arrival_Checklist__c/fields/Flight_Date_Local__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date_Local__c</fullName>
    <label>Flight Date(Local)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Arrival_Checklist__c/fields/List_Order__c.field-meta.xml
<CustomField>
    <fullName>List_Order__c</fullName>
    <label>List Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Arrival_Checklist__c/fields/Plane_Location__c.field-meta.xml
<CustomField>
    <fullName>Plane_Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Plane_Location</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Arrival_Checklist__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Airport_Operation_Checklist_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Arrival_Checklist__c/recordTypes/Completed.recordType-meta.xml
<RecordType>
    <fullName>Completed</fullName>
    <active>true</active>
    <description>Read-only page layout for completed checklist</description>
    <label>Completed</label>
</RecordType>

force-app/main/default/objects/Departure_Checklist__c/Departure_Checklist__c.object-meta.xml
<CustomObject>
    <label>Departure Checklist</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departure Checklist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Departure_Checklist__c/fields/Airport_Operation_ID__c.field-meta.xml
<CustomField>
    <fullName>Airport_Operation_ID__c</fullName>
    <label>Airport Operation ID</label>
    <referenceTo>Airport_Operation__c</referenceTo>
    <relationshipName>Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Departure_Checklist__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Division(Text)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Departure_Checklist__c/fields/Flight_Date_UTC__c.field-meta.xml
<CustomField>
    <fullName>Flight_Date_UTC__c</fullName>
    <label>Flight Date(UTC)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Departure_Checklist__c/recordTypes/Completed.recordType-meta.xml
<RecordType>
    <fullName>Completed</fullName>
    <active>true</active>
    <description>Read-only page layout for completed checklist</description>
    <label>Completed</label>
</RecordType>

force-app/main/default/objects/System_Settings__mdt/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AirportOperationTriggerHandler.cls
/********************************************************************************************************
NAME:           AirportOperationTriggerHandler
AUTHOR:         Edmond To (eto@salesforce.com)
PURPOSE:        To perform upsertions of Checklist__c records upon Airport_Operation records upsertions  
                Upon creation of Airport Operation record, a list of Checklist records will be created based on two checking parameters; Site & ScheduleType, controlled by custom metadata
                Upon updates of Airport Operation record, certain Checklist records will be updated accordingly based on their Status, controlled by the object field

UPDATE HISTORY:
DATE            AUTHOR          COMMENTS
-------------------------------------------------------------
17/06/2019      Edmond To       First version
27/08/2019      Edmond To       Revised to account for new object schema for Arrival Checklist and Departure Checklist records
********************************************************************************************************/

public class AirportOperationTriggerHandler extends TriggerHandler {
    public AirportOperationTriggerHandler() {
        
    }
    
    //Application Log 061819
    private static List<System_Settings__mdt> logLevelCMD;
    private static DateTime startTime = DateTime.now();
    private static String processLog;
    private static String payLoad;
    private static Integer totalRecords = 0, errorRecords = 0, successfulRecords = 0;
    private static List<String> failureRecords = new List<String>();
    
    public override void afterInsert() { //Create associated Checklist records based on settings in Custom Metadata settings
        createNewChecklists();
    }
    
    public override void afterUpdate() { //Update associated Checklist records based on settings in Custom Metadata settings
        
        updateChecklists();
    }
 
    private static void createNewChecklists() {
        
        //Application Log 061819
        System_Settings__mdt logLevelCMD = [Select Id, MasterLabel, Debug__c, Info__c, Warning__c, Error__c From
                                            System_Settings__mdt
                                            Where MasterLabel = 'Airport Operation Trigger Handler'
                                            limit 1];
        
        Timezone userTime = UserInfo.getTimeZone();
        Integer timeOffset = -(userTime.getOffset(DateTime.newInstance(2012,11,23,12,0,0))/(60000));
        system.debug('DBG TimeOffset: '+timeOffset);
        //Airport Operation masterlist
        List<Airport_Operation__c> operationRecordsToUpdate = new List<Airport_Operation__c>(); 
        
        //Arrival checklist masterlist
        List<Arrival_Checklist__c> arrivalRecordsToUpsert = new List<Arrival_Checklist__c>(); 
        
        //Departure checklist masterlist
        List<Departure_Checklist__c> departureRecordsToUpsert = new List<Departure_Checklist__c>();
        
        //Query for all new Airport Operation records upserted
        List<Airport_Operation__c> newOperations = [SELECT Id, Name,ETA_Date_Local__c, ETA_Time_Local__c, ETA_Date_UTC__c, ETA_Time_UTC__c,
                                                    ETD_Date_Local__c, ETD_Time_Local__c,ETD_Date_UTC__c, ETD_Time_UTC__c,FLT_Carrier__c,
                                                    STA_Date_Local__c,STA_Date_UTC__c, STA_Time_Local__c, STA_Time_UTC__c,STD_Date_Local__c, STD_Date_UTC__c, 
                                                    STD_Time_Local__c,STD_Time_UTC__c,Departure_Flight_Date_UTC__c, Departure_Flight_Date_Local__c,
                                                    Arrival_Flight_Date_UTC__c,Arrival_Flight_Date_Local__c, ETD_Offset__c, ETA_Offset__c
                                                    FROM Airport_Operation__c WHERE ID IN :Trigger.new]; 
        
        List<Airport_Operation_Checklist__mdt> newArrivalChecklist = [SELECT Id, ScheduleType__c, ListOrder__c, GroupInCharge__c, Site__c, StageName__c, EstimatedStartBase__c, EstimatedEndBase__c, EstimatedStartOffset__c, EstimatedEndOffset__c 
                                                                      FROM Airport_Operation_Checklist__mdt WHERE ScheduleType__c = 'Arrival' ORDER BY ScheduleType__c, Site__c, ListOrder__c]; //Query for all Arrival related Checklist metadata records
        
        List<Airport_Operation_Checklist__mdt> newDepartureChecklist = [SELECT Id, ScheduleType__c, ListOrder__c, GroupInCharge__c, Site__c, StageName__c, EstimatedStartBase__c, EstimatedEndBase__c, EstimatedStartOffset__c, EstimatedEndOffset__c 
                                                                      FROM Airport_Operation_Checklist__mdt WHERE ScheduleType__c = 'Departure' ORDER BY ScheduleType__c, Site__c, ListOrder__c]; //Query for all Departure related Checklist metadata records
        system.debug('DBG depchecklist: '+newDepartureChecklist);
        processLog += '\r\n'+'afterInsert:Excute newOperations'+'\r\n';
        for (Airport_Operation__c op : newOperations) { //Iterate through all Airport Operation records found earlier
            if (Trigger.isInsert) { //Condition for only inserted records
                //if (String.isEmpty(op.Arr__c) == false) { //Condition for only Arrival records
                //Update airport operation fields from DIH
                op.Name = op.FLT_Carrier__c + op.Name;
                op.ETA_Date_Local__c = op.STA_Date_Local__c;
                op.ETA_Date_UTC__c = op.STA_Date_UTC__c;
                op.ETA_Time_Local__c = op.STA_Time_Local__c;
                op.ETA_Time_UTC__c = op.STA_Time_UTC__c;    
                op.ETD_Date_Local__c = op.STD_Date_Local__c;
                op.ETD_Date_UTC__c = op.STD_Date_UTC__c;
                op.ETD_Time_Local__c = op.STD_Time_Local__c;
                op.ETD_Time_UTC__c = op.STD_Time_UTC__c; 
                    
                op.Departure_Flight_Date_UTC__c = op.STD_Date_UTC__c;
                op.Departure_Flight_Date_Local__c = op.STD_Date_Local__c;
                op.Arrival_Flight_Date_UTC__c = op.STA_Date_UTC__c;
                op.Arrival_Flight_Date_Local__c = op.STA_Date_Local__c;
                
                totalRecords++;
                operationRecordsToUpdate.add(op);
                
                    for (Airport_Operation_Checklist__mdt c : newArrivalChecklist) { //Iterate through each Arrival related Checklist metadata records
                       
                        //Populate relevant fields on Checklist record 
                        Arrival_Checklist__c ChecklistRecord = new Arrival_Checklist__c();
                        ChecklistRecord.Airport_Operation_ID__c = op.Id;
                        ChecklistRecord.Plane_Location__c = c.Site__c;
                        ChecklistRecord.Status_Picklist__c = 'Not Started';
                        ChecklistRecord.Name = c.StageName__c;
                        ChecklistRecord.Division__c = c.GroupInCharge__c;
                        ChecklistRecord.List_Order__c = c.ListOrder__c;
                        ChecklistRecord.Flight_Date_UTC__c = op.STA_Date_UTC__c;
                        ChecklistRecord.Flight_Date_Local__c = op.STA_Date_Local__c;
                        ChecklistRecord.Timezone_Offset__c = op.ETA_Offset__c;   
                        
                        if (c.EstimatedStartBase__c == 'ETA' || c.EstimatedStartBase__c == 'ETD') { 
                            ChecklistRecord.Estimated_Planned_Start_Time_Local__c = op.ETA_Time_Local__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                            ChecklistRecord.Estimated_Planned_Start_Time_UTC__c = op.ETA_Time_UTC__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                            ChecklistRecord.Actual_Planned_Start_Time_Local__c = op.ETA_Time_Local__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                            ChecklistRecord.Actual_Planned_Start_Time_UTC__c = op.ETA_Time_UTC__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                        } 
                        /*else if (c.EstimatedStartBase__c == 'ATA' || c.EstimatedStartBase__c == 'ATD') {
                            ChecklistRecord.Estimated_Planned_Start_Time__c = op.Actual_Flight_Time__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                            ChecklistRecord.Actual_Planned_Start_Time__c = op.Actual_Flight_Time__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                        }*/ 
                        if (c.EstimatedEndBase__c == 'ETA' || c.EstimatedEndBase__c == 'ETD') {
                            ChecklistRecord.Estimated_Planned_End_Time_Local__c = op.ETA_Time_Local__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                            ChecklistRecord.Estimated_Planned_End_Time_UTC__c = op.ETA_Time_UTC__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                            ChecklistRecord.Actual_Planned_Completion_Time_Local__c = op.ETA_Time_Local__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                            ChecklistRecord.Actual_Planned_Completion_Time_UTC__c = op.ETA_Time_UTC__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                        } 
                        /*else if (c.EstimatedEndBase__c == 'ATA' || c.EstimatedEndBase__c == 'ATD') {
                            ChecklistRecord.Estimated_Planned_End_Time__c = op.Actual_Flight_Time__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                            ChecklistRecord.Actual_Planned_Completion_Time__c = op.Actual_Flight_Time__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                        }*/
                        
                        totalRecords++;
                        arrivalRecordsToUpsert.add(ChecklistRecord); //Add Checklist record to master list
                    }
               // } else {
                    for (Airport_Operation_Checklist__mdt c : newDepartureChecklist) {
                        //Populate relevant fields on Checklist record
                        Departure_Checklist__c ChecklistRecord = new Departure_Checklist__c();
                        ChecklistRecord.Airport_Operation_ID__c = op.Id;
                        ChecklistRecord.Plane_Location__c = c.Site__c;
                        ChecklistRecord.Status__c = 'Not Started';
                        ChecklistRecord.Name = c.StageName__c;
                        ChecklistRecord.Division__c = c.GroupInCharge__c;
                        ChecklistRecord.List_Order__c = c.ListOrder__c;
                        ChecklistRecord.Flight_Date_UTC__c = op.STD_Date_UTC__c;
                        ChecklistRecord.Flight_Date_Local__c = op.STD_Date_Local__c;
                        ChecklistRecord.Timezone_Offset__c = op.ETD_Offset__c;        
                        
                        if (c.EstimatedStartBase__c == 'ETA' || c.EstimatedStartBase__c == 'ETD' || c.EstimatedStartBase__c == 'ATA' || c.EstimatedStartBase__c == 'ATD') { 
                            ChecklistRecord.Estimated_Planned_Start_Time_Local__c = op.ETD_Time_Local__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                            ChecklistRecord.Estimated_Planned_Start_Time_UTC__c = op.ETD_Time_UTC__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                            ChecklistRecord.Actual_Planned_Start_Time_Local__c = op.ETD_Time_Local__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                            ChecklistRecord.Actual_Planned_Start_Time_UTC__c = op.ETD_Time_UTC__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                        } 
                        /*else if (c.EstimatedStartBase__c == 'ATA' || c.EstimatedStartBase__c == 'ATD') {
                            ChecklistRecord.Estimated_Planned_Start_Time__c = op.Actual_Flight_Time__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                            ChecklistRecord.Actual_Planned_Start_Time__c = op.Actual_Flight_Time__c.addMinutes(Integer.valueOf(c.EstimatedStartOffset__c));
                        } */
                        if (c.EstimatedEndBase__c == 'ETA' || c.EstimatedEndBase__c == 'ETD' || c.EstimatedEndBase__c == 'ATA' || c.EstimatedEndBase__c == 'ATD') {
                            ChecklistRecord.Estimated_Planned_End_Time_Local__c = op.ETD_Time_Local__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                            ChecklistRecord.Estimated_Planned_End_Time_UTC__c = op.ETD_Time_UTC__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                            ChecklistRecord.Actual_Planned_Completion_Time_Local__c = op.ETD_Time_Local__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                            ChecklistRecord.Actual_Planned_Completion_Time_UTC__c = op.ETD_Time_UTC__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                        } 
                        /*else if (c.EstimatedEndBase__c == 'ATA' || c.EstimatedEndBase__c == 'ATD') {
                            ChecklistRecord.Estimated_Planned_End_Time__c = op.Actual_Flight_Time__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                            ChecklistRecord.Actual_Planned_Completion_Time__c = op.Actual_Flight_Time__c.addMinutes(Integer.valueOf(c.EstimatedEndOffset__c));
                        }*/
                        
                        totalRecords++;
                        departureRecordsToUpsert.add(ChecklistRecord); //Add Checklist record to master list
                    }
                //}
            }
        }
       
        
        //Try catch to insert the checklist records
        try {
            Database.SaveResult[] SaveResult = database.update(operationRecordsToUpdate, false);
            for (Integer i = 0; i < SaveResult.size(); i++) {
                if (!SaveResult[i].isSuccess()) {
                    for (Database.Error err : SaveResult[i].getErrors()) {
                        errorRecords++;
                        failureRecords.add(SaveResult[i].Id);
                        processLog += 'Unable to insert Record ID: ' + SaveResult[i].Id + '\r\n';
                        processLog += 'Root Cause: ' + err.getStatusCode() + ':' + err.getMessage() + '\r\n';
                        processLog += 'Fields that caused this error: ' + err.getFields() + '\r\n';
                    }
                } else {
                    successfulRecords++;
                }
            }
            
            Database.SaveResult[] SaveResult2 = database.insert(arrivalRecordsToUpsert, false);
            for (Integer i = 0; i < SaveResult2.size(); i++) {
                system.debug('DBG arrChecklistInsert: '+SaveResult2[i]);
                if (!SaveResult2[i].isSuccess()) {
                    for (Database.Error err : SaveResult2[i].getErrors()) {
                        errorRecords++;
                        failureRecords.add(SaveResult2[i].Id);
                        processLog += 'Unable to insert Record ID: ' + SaveResult2[i].Id + '\r\n';
                        processLog += 'Root Cause: ' + err.getStatusCode() + ':' + err.getMessage() + '\r\n';
                        processLog += 'Fields that caused this error: ' + err.getFields() + '\r\n';
                    }
                } else {
                    successfulRecords++;
                }
            }
            
            Database.SaveResult[] SaveResult3 = database.insert(departureRecordsToUpsert, false);
            for (Integer i = 0; i < SaveResult3.size(); i++) {
                system.debug('DBG depChecklistInsert: '+SaveResult3[i]);
                if (!SaveResult3[i].isSuccess()) {
                    for (Database.Error err : SaveResult3[i].getErrors()) {
                        errorRecords++;
                        failureRecords.add(SaveResult3[i].Id);
                        processLog += 'Unable to insert Record ID: ' + SaveResult3[i].Id + '\r\n';
                        processLog += 'Root Cause: ' + err.getStatusCode() + ':' + err.getMessage() + '\r\n';
                        processLog += 'Fields that caused this error: ' + err.getFields() + '\r\n';
                    }
                } else {
                    successfulRecords++;
                }
            }
            
            processLog = '#########################\r\n' +
            'Job Name: ' + logLevelCMD.MasterLabel + '\r\n' +
            'Start Date Time: ' + string.valueof(startTime) + '\r\n' +
            'End Date Time: ' + string.valueof(DateTime.Now()) + '\r\n' +
            'Total Processed Records: ' + totalRecords + '\r\n' +
            'Total Successful Inserted Records: ' + successfulRecords + '\r\n' +
            'Total Failed Records: ' + errorRecords + '\r\n' + 
            'List of Failed Records: ' + failureRecords + '\r\n' +
            '#########################\r\n' + processLog;
            
            system.debug('DBG ProcessLog: '+processLog);
            
            //Application Log 061819
            GlobalUtility.logMessage(Utilities.createApplicationLog('Info', 'AirportOperationTriggerHandler', 'createNewChecklists', null, 'Airport Operation Checklist Records Creation', processLog, payLoad, 'Job Log', startTime, logLevelCMD, null));
        
        } catch (DmlException DMLError) {
            
            //Application Log 061819
            GlobalUtility.logMessage(Utilities.createApplicationLog('Error', 'AirportOperationTriggerHandler', 'createNewChecklists', null, 'Airport Operation Checklist Records Creation', processLog, payLoad, 'Error Log', startTime, logLevelCMD, DMLError));
        }
    }
    
    private static void updateChecklists() {
        
        //Application Log 061819
        System_Settings__mdt logLevelCMD = [Select Id, MasterLabel, Debug__c, Info__c, Warning__c, Error__c From
                                            System_Settings__mdt
                                            Where MasterLabel = 'Airport Operation Trigger Handler'
                                            limit 1];

        Timezone userTime = UserInfo.getTimeZone();
        Integer timeOffset = -(userTime.getOffset(DateTime.newInstance(2012,11,23,12,0,0))/(60000));
        //Airport Operation masterlist
        List<Airport_Operation__c> operationRecordsToUpsert = new List<Airport_Operation__c>(); 
        List<Airport_Operation__c> operationNameRecordsToUpsert = new List<Airport_Operation__c>(); //Used to store records which doesn't fit the condition below in order to update Name field
        
        //Arrival checklist masterlist
        List<Arrival_Checklist__c> arrivalRecordsToUpsert = new List<Arrival_Checklist__c>(); 
        
        //Departure checklist masterlist
        List<Departure_Checklist__c> departureRecordsToUpsert = new List<Departure_Checklist__c>();
        
        //Add schedule datetime in SQL Chris 20200110
        List<Airport_Operation__c> newOperations = [SELECT Id,Name,AIRBORNE_Date__c,AIRBORNE_Time__c,ATA_Date__c,ATA_Time__c,LANDING_TIME__c,LANDING_DATE__c,ATD_Date__c,ATD_Time__c,
                                                    FLT_Carrier__c,ETA_Date_Local__c, ETA_Time_Local__c, ETA_Date_UTC__c, ETA_Time_UTC__c,
                                                    ETD_Date_Local__c, ETD_Time_Local__c,ETD_Date_UTC__c, ETD_Time_UTC__c,
                                                    STA_Date_Local__c,STA_Date_UTC__c, STA_Time_Local__c, STA_Time_UTC__c,STD_Date_Local__c, STD_Date_UTC__c, 
                                                    STD_Time_Local__c,STD_Time_UTC__c,
                                                    (SELECT Id,Actual_Start_Date__c,Actual_Completion_Date__c,Start_Now__c,Complete_Now__c,Actual_Start_Time_Local__c,
                                                     Actual_Start_Time_UTC__c,Actual_Completion_Time_Local__c,Actual_Completion_Time_UTC__c, Status_Picklist__c,Estimated_Planned_Start_Time_Local__c, Estimated_Planned_Start_Time_UTC__c, Actual_Planned_Start_Time_Local__c,
                                                     Actual_Planned_Start_Time_UTC__c,Estimated_Planned_End_Time_Local__c,Estimated_Planned_End_Time_UTC__c,Actual_Planned_Completion_Time_Local__c,
                                                     Actual_Planned_Completion_Time_UTC__c, Name FROM Arrival_Checklists__r),
                                                   (SELECT Id, Actual_Start_Date__c,Actual_Completion_Date__c,Start_Now__c,Complete_Now__c,Actual_Start_Time_Local__c,
                                                     Actual_Start_Time_UTC__c,Actual_Completion_Time_Local__c,Actual_Completion_Time_UTC__c,Status__c,Estimated_Planned_Start_Time_Local__c, Estimated_Planned_Start_Time_UTC__c, Actual_Planned_Start_Time_Local__c,
                                                     Actual_Planned_Start_Time_UTC__c,Estimated_Planned_End_Time_Local__c,Estimated_Planned_End_Time_UTC__c,Actual_Planned_Completion_Time_Local__c,
                                                     Actual_Planned_Completion_Time_UTC__c, Name FROM Checklists__r)
                                                    FROM Airport_Operation__c WHERE ID IN :Trigger.new]; //Query for all new Airport Operation records upserted
        
        List<Airport_Operation__c> finalOperations = new List<Airport_Operation__c>(); //Used to store all ETA/ETD shortlisted operations based on condition below
        List<Airport_Operation__c> nameOperations = new List<Airport_Operation__c>(); //Used to store the rest of the operations that don't fit the condition below, in order to update Name field
        
        for (Airport_Operation__c op : newOperations) {
            Airport_Operation__c oldOp = (Airport_Operation__c)Trigger.oldMap.get(op.Id);
            //Chris 20200312
            if((op.ETA_Time_UTC__c != null && op.ETA_Time_UTC__c != oldOp.ETA_Time_UTC__c) ||
                      (op.ETD_Time_UTC__c != null && op.ETD_Time_UTC__c != oldOp.ETD_Time_UTC__c) ||
                      (op.ETA_Date_UTC__c != null && op.ETA_Date_UTC__c != oldOp.ETA_Date_UTC__c)||
                      (op.ETD_Date_UTC__c != null && op.ETD_Date_UTC__c != oldOp.ETD_Date_UTC__c)||
                      (op.AIRBORNE_Date__c != null && op.AIRBORNE_Date__c != oldOp.AIRBORNE_Date__c)||
                      (op.AIRBORNE_Time__c != null && op.AIRBORNE_Time__c != oldOp.AIRBORNE_Time__c)||
                      (op.ATA_Date__c != null && op.ATA_Date__c != oldOp.ATA_Date__c)||
                      (op.ATA_Time__c != null && op.ATA_Time__c != oldOp.ATA_Time__c)||
                      (op.LANDING_DATE__c != null && op.LANDING_DATE__c != oldOp.LANDING_DATE__c)||
                      (op.LANDING_TIME__c != null && op.LANDING_TIME__c != oldOp.LANDING_TIME__c)||
                      (op.ATD_Date__c != null && op.ATD_Date__c != oldOp.ATD_Date__c)||
                      (op.ATD_Time__c != null && op.ATD_Time__c != oldOp.ATD_Time__c)){
                finalOperations.add(op);
                processLog += '\r\n'+'afterupdate:Excute finalOperations,Flight Number='+op.Name+'\r\n';//Chris 20200310
            }
            /*if (op.ETA_Time_UTC__c != oldOp.ETA_Time_UTC__c || op.ETD_Time_UTC__c != oldOp.ETD_Time_UTC__c || op.ETA_Date_UTC__c != oldOp.ETA_Date_UTC__c || op.ETD_Date_UTC__c != oldOp.ETD_Date_UTC__c || op.AIRBORNE_Date__c != oldOp.AIRBORNE_Date__c || op.AIRBORNE_Time__c != oldOp.AIRBORNE_Time__c || op.ATA_Date__c != oldOp.ATA_Date__c || op.ATA_Time__c != oldOp.ATA_Time__c || op.LANDING_DATE__c != oldOp.LANDING_DATE__c || op.LANDING_TIME__c != oldOp.LANDING_TIME__c || op.ATD_Date__c != oldOp.ATD_Date__c || op.ATD_Time__c != oldOp.ATD_Time__c) {
                finalOperations.add(op);
                processLog += '\r\n'+'afterupdate:Excute finalOperations,Flight Number='+op.Name+'\r\n';//Chris 20200110
            }*/
            else {
                nameOperations.add(op);
                processLog += 'afterupdate:Excute nameOperations,Flight Number='+op.Name+'\r\n';//Chris 20200110
            }
        }
        List<Airport_Operation_Checklist__mdt> newArrivalChecklist = [SELECT Id,ListOrder__c, GroupInCharge__c, Label, Site__c, EstimatedStartOffset__c, EstimatedEndOffset__c, ActualStartBase__c, ActualEndBase__c, ActualStartOffset__c, ActualEndOffset__c 
                                                                      FROM Airport_Operation_Checklist__mdt WHERE ScheduleType__c = 'Arrival']; //Query for all Arrival related Checklist metadata records
        
        List<Airport_Operation_Checklist__mdt> newDepartureChecklist = [SELECT Id, ListOrder__c, GroupInCharge__c, Label, Site__c, EstimatedStartOffset__c, EstimatedEndOffset__c, ActualStartBase__c, ActualEndBase__c, ActualStartOffset__c, ActualEndOffset__c 
                                                                      FROM Airport_Operation_Checklist__mdt WHERE ScheduleType__c = 'Departure']; //Query for all Departure related Checklist metadata records
        
        for (Airport_Operation__c op : nameOperations) {
            if (op.Name.startsWith(op.FLT_Carrier__c) != true) {
                op.Name = op.FLT_Carrier__c + op.Name;
                //Set ETD as STD in case schedule change - Chris 20200110
                if(op.STD_Date_Local__c != op.ETD_Date_Local__c || op.STD_Date_UTC__c != op.ETD_Date_UTC__c || op.STD_Time_Local__c != op.ETD_Time_Local__c || op.STD_Time_UTC__c != op.ETD_Time_UTC__c) {                        
                    op.ETD_Date_Local__c = op.STD_Date_Local__c;
                    op.ETD_Date_UTC__c = op.STD_Date_UTC__c;
                    op.ETD_Time_Local__c = op.STD_Time_Local__c;
                    op.ETD_Time_UTC__c = op.STD_Time_UTC__c; 
                    
                    op.Departure_Flight_Date_UTC__c = op.STD_Date_UTC__c;
                    op.Departure_Flight_Date_Local__c = op.STD_Date_Local__c;
                    processLog += '\r\n'+'schedule change(STD)';
                }
                //Set ETA as STA in case schedule change - Chris 20200110
                if(op.STA_Date_Local__c != op.ETA_Date_Local__c || op.STA_Date_UTC__c != op.ETA_Date_UTC__c || op.STA_Time_Local__c != op.ETA_Time_Local__c || op.STA_Time_UTC__c != op.ETA_Time_UTC__c) {
                    op.ETA_Date_Local__c = op.STA_Date_Local__c;
                    op.ETA_Date_UTC__c = op.STA_Date_UTC__c;
                    op.ETA_Time_Local__c = op.STA_Time_Local__c;
                    op.ETA_Time_UTC__c = op.STA_Time_UTC__c;  
                   
                    op.Arrival_Flight_Date_UTC__c = op.STA_Date_UTC__c;
                    op.Arrival_Flight_Date_Local__c = op.STA_Date_Local__c;
                    processLog += '\r\n'+'schedule change(STA)';
                }
                
                totalRecords++;
                operationNameRecordsToUpsert.add(op);
            }     
        }
            
        for (Airport_Operation__c op : finalOperations) { //Iterating through list of shortlisted Airport Operation records
            if (Trigger.isUpdate) { //Checking that record was updated 
                Airport_Operation__c oldOp = (Airport_Operation__c)Trigger.oldMap.get(op.Id);
                
                //if (op.ETA_Time_UTC__c != oldOp.ETA_Time_UTC__c || op.ETD_Time_UTC__c != oldOp.ETD_Time_UTC__c || op.ETA_Date_UTC__c != oldOp.ETA_Date_UTC__c || op.ETD_Date_UTC__c != oldOp.ETD_Date_UTC__c){
                    if (op.Name.startsWith(op.FLT_Carrier__c) != true) {
                        op.Name = op.FLT_Carrier__c + op.Name;
                    }
                    op.Departure_Flight_Date_UTC__c = op.ETD_Date_UTC__c;
                    op.Departure_Flight_Date_Local__c = op.ETD_Date_Local__c;
                    op.Arrival_Flight_Date_UTC__c = op.ETA_Date_UTC__c;
                    op.Arrival_Flight_Date_Local__c = op.ETA_Date_Local__c;
                    
                    totalRecords++;
                    operationRecordsToUpsert.add(op);      
                //}
                
                    List<Arrival_Checklist__c> checklistRecords = new List<Arrival_Checklist__c>();
                    checklistRecords = op.Arrival_Checklists__r; //Related Arrival Checklist records to the AO record
                    for (Arrival_Checklist__c ChecklistRecord : checklistRecords) { //Iterating through the list of Arrival Checklist records
                        if (ChecklistRecord.Status_Picklist__c != 'Completed') { //Checking for incomplete Arrival Checklist records
                            for (Integer i=0; i < newArrivalChecklist.size(); i++) { //Iterating through the list of Checklist METADATA records
                                if (newArrivalChecklist[i].Label == ChecklistRecord.Name) {
                                    ChecklistRecord.Flight_Date_UTC__c = op.ETA_Date_UTC__c;
                                    ChecklistRecord.Flight_Date_Local__c = op.ETA_Date_Local__c;
                                    if (newArrivalChecklist[i].ActualStartBase__c == 'ATA' || newArrivalChecklist[i].ActualStartBase__c == 'ATD') {
                                        ChecklistRecord.Estimated_Planned_Start_Time_Local__c = op.ETA_Time_Local__c.addMinutes(Integer.valueOf(newArrivalChecklist[i].EstimatedStartOffset__c));   
                                        ChecklistRecord.Estimated_Planned_Start_Time_UTC__c = op.ETA_Time_UTC__c.addMinutes(Integer.valueOf(newArrivalChecklist[i].EstimatedStartOffset__c));
                                        ChecklistRecord.Actual_Planned_Start_Time_Local__c = op.ETA_Time_Local__c.addMinutes(Integer.valueOf(newArrivalChecklist[i].ActualStartOffset__c));
                                        ChecklistRecord.Actual_Planned_Start_Time_UTC__c = op.ETA_Time_UTC__c.addMinutes(Integer.valueOf(newArrivalChecklist[i].ActualStartOffset__c));    
                                    }
                                    if (newArrivalChecklist[i].ActualEndBase__c == 'ATA' || newArrivalChecklist[i].ActualEndBase__c == 'ATD') {
                                        ChecklistRecord.Estimated_Planned_End_Time_Local__c = op.ETA_Time_Local__c.addMinutes(Integer.valueOf(newArrivalChecklist[i].EstimatedEndOffset__c));
                                        ChecklistRecord.Estimated_Planned_End_Time_UTC__c = op.ETA_Time_UTC__c.addMinutes(Integer.valueOf(newArrivalChecklist[i].EstimatedEndOffset__c));
                                        ChecklistRecord.Actual_Planned_Completion_Time_Local__c = op.ETA_Time_Local__c.addMinutes(Integer.valueOf(newArrivalChecklist[i].ActualEndOffset__c));
                                        ChecklistRecord.Actual_Planned_Completion_Time_UTC__c = op.ETA_Time_UTC__c.addMinutes(Integer.valueOf(newArrivalChecklist[i].ActualEndOffset__c));   
                                    }
                                    
                                    
                                        if (oldOp.LANDING_Date__c != op.LANDING_Date__c && newArrivalChecklist[i].ListOrder__c == 2 && newArrivalChecklist[i].Site__c == 'Above the Wing') {
                                            system.debug('Updating Arrival Checklist 2 Date');
                                            system.debug(ChecklistRecord.Actual_Start_Date__c);
                                            ChecklistRecord.Actual_Start_Date__c = op.LANDING_Date__c;
                                            ChecklistRecord.Actual_Completion_Date__c = op.LANDING_Date__c;
                                            ChecklistRecord.Start_Now__c = true;
                                            ChecklistRecord.Complete_Now__c = true;
                                            system.debug(ChecklistRecord.Actual_Start_Date__c);
                                            if (op.LANDING_TIME__c != null) {
                                                ChecklistRecord.Actual_Start_Time_Local__c = op.LANDING_TIME__c;
                                                ChecklistRecord.Actual_Start_Time_UTC__c = op.LANDING_TIME__c;
                                                ChecklistRecord.Actual_Completion_Time_Local__c = op.LANDING_TIME__c;
                                                ChecklistRecord.Actual_Completion_Time_UTC__c = op.LANDING_TIME__c;
                                            }
                                        }
                                        if (oldOp.LANDING_TIME__c != op.LANDING_TIME__c && newArrivalChecklist[i].ListOrder__c == 2 && newArrivalChecklist[i].Site__c == 'Above the Wing') {
                                            system.debug('Updating Arrival Checklist 2 Time');
                                            ChecklistRecord.Actual_Start_Time_Local__c = op.LANDING_TIME__c;
                                            ChecklistRecord.Actual_Start_Time_UTC__c = op.LANDING_TIME__c;
                                            ChecklistRecord.Actual_Completion_Time_Local__c = op.LANDING_TIME__c;
                                            ChecklistRecord.Actual_Completion_Time_UTC__c = op.LANDING_TIME__c;
                                            if (op.LANDING_Date__c != null) {
                                                ChecklistRecord.Actual_Start_Date__c = op.LANDING_Date__c;
                                                ChecklistRecord.Actual_Completion_Date__c = op.LANDING_Date__c;
                                                ChecklistRecord.Start_Now__c = true;
                                                ChecklistRecord.Complete_Now__c = true;
                                            }
                                        }
                                        if (oldOp.ATA_Date__c != op.ATA_Date__c && newArrivalChecklist[i].ListOrder__c == 3 && newArrivalChecklist[i].Site__c == 'Above the Wing') {
                                            system.debug('Updating Arrival Checklist 3 Date');
                                            ChecklistRecord.Actual_Start_Date__c = op.ATA_Date__c;
                                            ChecklistRecord.Actual_Completion_Date__c = op.ATA_Date__c;
                                            ChecklistRecord.Start_Now__c = true;
                                            ChecklistRecord.Complete_Now__c = true;
                                            if (op.ATA_Time__c != null) {
                                                ChecklistRecord.Actual_Start_Time_Local__c = op.ATA_Time__c;
                                                ChecklistRecord.Actual_Start_Time_UTC__c = op.ATA_Time__c;
                                                ChecklistRecord.Actual_Completion_Time_Local__c = op.ATA_Time__c;
                                                ChecklistRecord.Actual_Completion_Time_UTC__c = op.ATA_Time__c;
                                            }
                                        }
                                        if (oldOp.ATA_Time__c != op.ATA_Time__c && newArrivalChecklist[i].ListOrder__c == 3 && newArrivalChecklist[i].Site__c == 'Above the Wing') {
                                            system.debug('Updating Arrival Checklist 3 Time');
                                            ChecklistRecord.Actual_Start_Time_Local__c = op.ATA_Time__c;
                                            ChecklistRecord.Actual_Start_Time_UTC__c = op.ATA_Time__c;
                                            ChecklistRecord.Actual_Completion_Time_Local__c = op.ATA_Time__c;
                                            ChecklistRecord.Actual_Completion_Time_UTC__c = op.ATA_Time__c;
                                            if (op.ATA_Date__c != null) {
                                                ChecklistRecord.Actual_Start_Date__c = op.ATA_Date__c;
                                                ChecklistRecord.Actual_Completion_Date__c = op.ATA_Date__c;
                                                ChecklistRecord.Start_Now__c = true;
                                                ChecklistRecord.Complete_Now__c = true;
                                            }
                                        }
                                    totalRecords++;
                                    arrivalRecordsToUpsert.add(ChecklistRecord);
                                }    
                            }     
                        }     
                    }
                //} 
                    //if (op.ATD_Local__c != null) { //Check whether has necessary value in ATD Local field
                        List<Departure_Checklist__c> checklistRecords2 = new List<Departure_Checklist__c>();
                        checklistRecords2 = op.Checklists__r; //Related Departure Checklist records to the AO record
                        for (Departure_Checklist__c ChecklistRecord : checklistRecords2) { //Iterating through the list of Departure Checklist records
                            if (ChecklistRecord.Status__c != 'Completed') { //Checking for incomplete Departure Checklist records
                                for (Integer i=0; i < newDepartureChecklist.size(); i++) { //Iterating through the list of Checklist METADATA records
                                    if (newDepartureChecklist[i].Label == ChecklistRecord.Name) {
                                        ChecklistRecord.Flight_Date_UTC__c = op.ETD_Date_UTC__c;
                                        ChecklistRecord.Flight_Date_Local__c = op.ETD_Date_Local__c;
                                        
                                        if (newDepartureChecklist[i].ActualStartBase__c == 'ATA' || newDepartureChecklist[i].ActualStartBase__c == 'ATD') {
                                            ChecklistRecord.Estimated_Planned_Start_Time_Local__c = op.ETD_Time_Local__c.addMinutes(Integer.valueOf(newDepartureChecklist[i].EstimatedStartOffset__c));
                                            ChecklistRecord.Estimated_Planned_Start_Time_UTC__c = op.ETD_Time_UTC__c.addMinutes(Integer.valueOf(newDepartureChecklist[i].EstimatedStartOffset__c));
                                            ChecklistRecord.Actual_Planned_Start_Time_Local__c = op.ETD_Time_Local__c.addMinutes(Integer.valueOf(newDepartureChecklist[i].ActualStartOffset__c));
                                            ChecklistRecord.Actual_Planned_Start_Time_UTC__c = op.ETD_Time_UTC__c.addMinutes(Integer.valueOf(newDepartureChecklist[i].ActualStartOffset__c));
                                        } 
                                        if (newDepartureChecklist[i].ActualEndBase__c == 'ATA' || newDepartureChecklist[i].ActualEndBase__c == 'ATD') {
                                            ChecklistRecord.Estimated_Planned_End_Time_Local__c = op.ETD_Time_Local__c.addMinutes(Integer.valueOf(newDepartureChecklist[i].EstimatedEndOffset__c));
                                            ChecklistRecord.Estimated_Planned_End_Time_UTC__c = op.ETD_Time_UTC__c.addMinutes(Integer.valueOf(newDepartureChecklist[i].EstimatedEndOffset__c));
                                            ChecklistRecord.Actual_Planned_Completion_Time_Local__c = op.ETD_Time_Local__c.addMinutes(Integer.valueOf(newDepartureChecklist[i].ActualEndOffset__c));
                                            ChecklistRecord.Actual_Planned_Completion_Time_UTC__c = op.ETD_Time_UTC__c.addMinutes(Integer.valueOf(newDepartureChecklist[i].ActualEndOffset__c));
                                        }
                                        
                                        if (oldOp.ATD_Date__c != op.ATD_Date__c && newDepartureChecklist[i].ListOrder__c == 22) {
                                            system.debug('Updating Departure Checklist 22 Date');
                                            system.debug('ChecklistRecord: '+ChecklistRecord.Actual_Start_Date__c);
                                            ChecklistRecord.Actual_Start_Date__c = op.ATD_Date__c;
                                            ChecklistRecord.Actual_Completion_Date__c = op.ATD_Date__c;
                                            ChecklistRecord.Start_Now__c = true;
                                            ChecklistRecord.Complete_Now__c = true;
                                            system.debug('ChecklistRecord: '+ChecklistRecord.Actual_Start_Date__c);
                                            if (op.ATD_Time__c != null) {
                                                ChecklistRecord.Actual_Start_Time_Local__c = op.ATD_Time__c;
                                                ChecklistRecord.Actual_Start_Time_UTC__c = op.ATD_Time__c;
                                                ChecklistRecord.Actual_Completion_Time_Local__c = op.ATD_Time__c;
                                                ChecklistRecord.Actual_Completion_Time_UTC__c = op.ATD_Time__c;
                                            }
                                        }
                                        if (oldOp.ATD_Time__c != op.ATD_Time__c && newDepartureChecklist[i].ListOrder__c == 22) {
                                            system.debug('Updating Departure Checklist 22 Time');
                                             system.debug('ChecklistRecord: '+ChecklistRecord.Actual_Start_Time_Local__c);
                                            ChecklistRecord.Actual_Start_Time_Local__c = op.ATD_Time__c;
                                            ChecklistRecord.Actual_Start_Time_UTC__c = op.ATD_Time__c;
                                            ChecklistRecord.Actual_Completion_Time_Local__c = op.ATD_Time__c;
                                            ChecklistRecord.Actual_Completion_Time_UTC__c = op.ATD_Time__c;
                                             system.debug('ChecklistRecord: '+ChecklistRecord.Actual_Start_Time_Local__c);
                                            if (op.ATD_Date__c != null) {
                                                ChecklistRecord.Actual_Start_Date__c = op.ATD_Date__c;
                                                ChecklistRecord.Actual_Completion_Date__c = op.ATD_Date__c;
                                                ChecklistRecord.Start_Now__c = true;
                                                ChecklistRecord.Complete_Now__c = true;
                                            }
                                        }
                                        system.debug('DBG oldAIRBORNE: '+oldOp.AIRBORNE_Date__c);
                                        system.debug('DBG opAIRBORNE: '+op.AIRBORNE_Date__c);
                                        if (oldOp.AIRBORNE_Date__c != op.AIRBORNE_Date__c && newDepartureChecklist[i].ListOrder__c == 23) {
                                             system.debug('Updating Departure Checklist 23 Date');
                                            ChecklistRecord.Actual_Start_Date__c = op.AIRBORNE_Date__c;
                                            ChecklistRecord.Actual_Completion_Date__c = op.AIRBORNE_Date__c;
                                            ChecklistRecord.Start_Now__c = true;
                                            ChecklistRecord.Complete_Now__c = true;
                                            if (op.AIRBORNE_Time__c != null) {
                                                ChecklistRecord.Actual_Start_Time_Local__c = op.AIRBORNE_Time__c;
                                                ChecklistRecord.Actual_Start_Time_UTC__c = op.AIRBORNE_Time__c;
                                                ChecklistRecord.Actual_Completion_Time_Local__c = op.AIRBORNE_Time__c;
                                                ChecklistRecord.Actual_Completion_Time_UTC__c = op.AIRBORNE_Time__c;
                                            }
                                        }
                                        if (oldOp.AIRBORNE_Time__c != op.AIRBORNE_Time__c && newDepartureChecklist[i].ListOrder__c == 23) {
                                            system.debug('Updating Departure Checklist 23 Time');
                                            system.debug('ChecklistRecord: '+ChecklistRecord.Actual_Start_Time_Local__c);
                                            ChecklistRecord.Actual_Start_Time_Local__c = op.AIRBORNE_Time__c;
                                            ChecklistRecord.Actual_Start_Time_UTC__c = op.AIRBORNE_Time__c;
                                            ChecklistRecord.Actual_Completion_Time_Local__c = op.AIRBORNE_Time__c;
                                            ChecklistRecord.Actual_Completion_Time_UTC__c = op.AIRBORNE_Time__c;
                                            system.debug('ChecklistRecord: '+ChecklistRecord.Actual_Start_Time_Local__c);
                                            if (op.AIRBORNE_Date__c != null) {
                                                ChecklistRecord.Actual_Start_Date__c = op.AIRBORNE_Date__c;
                                                ChecklistRecord.Actual_Completion_Date__c = op.AIRBORNE_Date__c;
                                                ChecklistRecord.Start_Now__c = true;
                                                ChecklistRecord.Complete_Now__c = true;
                                            }
                                        }
                                        totalRecords++;
                                        departureRecordsToUpsert.add(ChecklistRecord);
                                    }
                                } 
                            }     
                        }    
                   // }
                
            }
        }
        system.debug('DBG operationRecordsToUpsert: ' + operationRecordsToUpsert);
        //Try catch to upsert the checklist records
        try {
            
            Database.UpsertResult[] SaveResult2 = database.upsert(arrivalRecordsToUpsert, false);
            for (Integer i = 0; i < SaveResult2.size(); i++) {
                if (!SaveResult2[i].isSuccess()) {
                    for (Database.Error err : SaveResult2[i].getErrors()) {
                        errorRecords++;
                        failureRecords.add(SaveResult2[i].Id);
                        processLog += 'Unable to upsert Record ID: ' + SaveResult2[i].Id + '\r\n';
                        processLog += 'Root Cause: ' + err.getStatusCode() + ':' + err.getMessage() + '\r\n';
                        processLog += 'Fields that caused this error: ' + err.getFields() + '\r\n';
                    }
                } else {
                    //system.debug('DBG SaveResult[i]: '+ SaveResult[i]);
                    successfulRecords++;
                }
            }
            
            Database.UpsertResult[] SaveResult3 = database.upsert(departureRecordsToUpsert, false);
            for (Integer i = 0; i < SaveResult3.size(); i++) {
                system.debug('DBG saveresult3: '+SaveResult3[i]);
                if (!SaveResult3[i].isSuccess()) {
                    for (Database.Error err : SaveResult3[i].getErrors()) {
                        system.debug('DBG Failed Record: '+SaveResult3[i].Id);
                        errorRecords++;
                        failureRecords.add(SaveResult3[i].Id);
                        processLog += 'Unable to upsert Record ID: ' + SaveResult3[i].Id + '\r\n';
                        processLog += 'Root Cause: ' + err.getStatusCode() + ':' + err.getMessage() + '\r\n';
                        processLog += 'Fields that caused this error: ' + err.getFields() + '\r\n';
                    }
                } else {
                    //system.debug('DBG SaveResult[i]: '+ SaveResult[i]);
                    successfulRecords++;
                }
            }
            
            Database.SaveResult[] SaveResult = database.update(operationRecordsToUpsert, false);
            for (Integer i = 0; i < SaveResult.size(); i++) {
                if (!SaveResult[i].isSuccess()) {
                    for (Database.Error err : SaveResult[i].getErrors()) {
                        errorRecords++;
                        failureRecords.add(SaveResult[i].Id);
                        processLog += 'Unable to upsert Record ID: ' + SaveResult[i].Id + '\r\n';
                        processLog += 'Root Cause: ' + err.getStatusCode() + ':' + err.getMessage() + '\r\n';
                        processLog += 'Fields that caused this error: ' + err.getFields() + '\r\n';
                    }
                } else {
                    //system.debug('DBG SaveResult[i]: '+ SaveResult[i]);
                    successfulRecords++;
                }
            }
            
            Database.SaveResult[] SaveResult4 = database.update(operationNameRecordsToUpsert, false);
            for (Integer i = 0; i < SaveResult4.size(); i++) {
                if (!SaveResult4[i].isSuccess()) {
                    for (Database.Error err : SaveResult4[i].getErrors()) {
                        errorRecords++;
                        failureRecords.add(SaveResult4[i].Id);
                        processLog += 'Unable to upsert Record ID: ' + SaveResult4[i].Id + '\r\n';
                        processLog += 'Root Cause: ' + err.getStatusCode() + ':' + err.getMessage() + '\r\n';
                        processLog += 'Fields that caused this error: ' + err.getFields() + '\r\n';
                    }
                } else {
                    //system.debug('DBG SaveResult[i]: '+ SaveResult[i]);
                    successfulRecords++;
                }
            }
            
            processLog = '#########################\r\n' +
            'Job Name: ' + logLevelCMD.MasterLabel + '\r\n' +
            'Start Date Time: ' + string.valueof(startTime) + '\r\n' +
            'End Date Time: ' + string.valueof(DateTime.Now()) + '\r\n' +
            'Total Processed Records: ' + totalRecords + '\r\n' +
            'Total Successful Upserted Records: ' + successfulRecords + '\r\n' +
            'Total Failed Records: ' + errorRecords + '\r\n' + 
            'List of Failed Records: ' + failureRecords + '\r\n' +
            '#########################\r\n' + processLog;
            
            system.debug('DBG ProcessLog: '+processLog);
            
            //Application Log 061819
            GlobalUtility.logMessage(Utilities.createApplicationLog('Info', 'AirportOperationTriggerHandler', 'updateChecklists', null, 'Airport Operation Checklist Records Upsertion', processLog, payLoad, 'Job Log', startTime, logLevelCMD, null));
        
        } catch (DmlException DMLError) {
            
            //Application Log 061819
            GlobalUtility.logMessage(Utilities.createApplicationLog('Error', 'AirportOperationTriggerHandler', 'updateChecklists', null, 'Airport Operation Checklist Records Upsertion', processLog, payLoad, 'Error Log', startTime, logLevelCMD, DMLError));
        }
        
    }
    public static void fakeMethod(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}