force-app/main/default/objects/Integration_Field_Display__mdt/Integration_Field_Display__mdt.object-meta.xml
<CustomObject>
    <description>This is used in lightning component to map the configuration and design attribute</description>
    <label>Integration Field Display</label>
    <pluralLabel>Integration Fields Display</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Field_Display__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Lang</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
                <default>true</default>
                <label>en_US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interface_Operation_Setting__mdt/Interface_Operation_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Interface Operation Setting</label>
    <pluralLabel>Interface Operation Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Interface_Operation_Setting__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Abbreviated language setting of the User. This will be used for the LTC API Fields Map.</description>
    <inlineHelpText>Abbreviated language setting of the User. This will be used for the LTC API Fields Map.</inlineHelpText>
    <label>Language</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InterfaceOpsDynamicListCompAttr.cls
global class InterfaceOpsDynamicListCompAttr extends VisualEditor.DynamicPickList {
    global override VisualEditor.DataRow getDefaultValue() {
        VisualEditor.DataRow defaultValue = new VisualEditor.DataRow('None', 'None');
        return defaultValue;
    }

    global override VisualEditor.DynamicPickListRows getValues() {
        return getIntegrationComponentPickList();
    }

    private VisualEditor.DynamicPickListRows getIntegrationComponentPickList() {
        VisualEditor.DynamicPickListRows listForSelection = new VisualEditor.DynamicPickListRows();
        // Hard code to exclude Grant Entitlement for now because it should not be displayed for the Dynamic List component
        String queryCondition = 'Language__c = ' + '\'' + UserInfo.getLanguage() + '\'' + ' AND ' + 'DeveloperName !=' + '\'' + 'Grant_Entitlement' + '\'';
        //Retiring the line below because we are deprecating the Integration Field Display custom metadata for Mediacorp
        //List<Integration_Field_Display__mdt> customMetadataList = lib_UtilityHelper.getSObjectRecords('Integration_Field_Display__mdt', queryCondition, false);
        List<Interface_Operation_Setting__mdt> customMetadataList = lib_UtilityHelper.getSObjectRecords('Interface_Operation_Setting__mdt', queryCondition, false);
        for (Interface_Operation_Setting__mdt pickVal : customMetadataList) {
            listForSelection.addRow(new VisualEditor.DataRow((String) pickVal.Label, (String) pickVal.DeveloperName));
        }

        return listForSelection;
    }
}