force-app/main/default/objects/Application_Setting__mdt/Application_Setting__mdt.object-meta.xml
<CustomObject>
    <description>We will use this to store multiple data such as our Trigger Name and value, archival age, etc</description>
    <label>Application Setting</label>
    <pluralLabel>Application Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Application_Setting__mdt/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>This should be key.</description>
    <inlineHelpText>This should be key, Please use key as Lable as well.</inlineHelpText>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Application_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>This should be key corresponding value.</description>
    <inlineHelpText>This should be key corresponding value.</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Additional_Filter__c.field-meta.xml
<CustomField>
    <fullName>Additional_Filter__c</fullName>
    <label>Additional Filter</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <label>Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Date_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Date_Field_API_Name__c</fullName>
    <label>Date Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/is_Trigger__c.field-meta.xml
<CustomField>
    <fullName>is_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Number_Of_Retry__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Retry__c</fullName>
    <label>Number Of Retry</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/SObject_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Api_Name__c</fullName>
    <label>SObject Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Settings__mdt/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Utilities.cls
/**
* Using without sharing as need to run query on Organization table
*/

public without sharing class Utilities {
	public static String getAppSettingsMdtValueByKey(String key) {
    	return [Select Value__c from Application_Setting__mdt where Key__c = : key].Value__c;
    }

 	public static Map < String, String > getAppSettings() {
  		Map < String, String > appSettingsMap = new Map < String, String > ();
  		for (Application_Setting__mdt eachAppSettings: [Select Key__c, Value__c from Application_Setting__mdt]) {
   			appSettingsMap.put(eachAppSettings.Key__c, eachAppSettings.Value__c);
  		}
  		return appSettingsMap;
 	}


 	public static System_Settings__mdt getLogLevel(String metadata_label_name) {
  		List < System_Settings__mdt > routingLogSysStngCMD = [Select Id, Label, Date_Field_API_Name__c, Additional_Filter__c, Batch_Size__c, 
                                                              SObject_Api_Name__c, Debug__c, Info__c, Warning__c, Error__c From System_Settings__mdt 
                                                              Where MasterLabel = : metadata_label_name limit 1];
  		if (!routingLogSysStngCMD.isEmpty())
   			return routingLogSysStngCMD[0];
  		
        return null;
 	}

 	public static ApplicationLogWrapper createApplicationLog(String logLevel, String sourceClass, String sourceFunction, String failedRecordId, String applicationName, String processLog, String payLoad, String type, DateTime startTime, System_Settings__mdt logLevelCMD, Exception thrownExeption) {
  		ApplicationLogWrapper appLogWrapper = new ApplicationLogWrapper();
  		appLogWrapper.logLevel = logLevel;
  		appLogWrapper.sourceClass = sourceClass;
  		appLogWrapper.sourceFunction = sourceFunction;
  		appLogWrapper.logMessage = processLog;
  		appLogWrapper.applicationName = applicationName;
  		appLogWrapper.exceptionThrown = thrownExeption;
  		appLogWrapper.startDate = startTime;
  		appLogWrapper.endDate = DateTime.now();
  		appLogWrapper.type = 'Error Log';

  		if (String.isNotEmpty(type))
   			appLogWrapper.type = type;

  		if (String.isNotEmpty(payLoad))
   			appLogWrapper.payLoad = payLoad;

  		if (thrownExeption != null)
   			appLogWrapper.logLevel = 'Error';

  		if (String.isNotEmpty(failedRecordId))
   			appLogWrapper.referenceId = failedRecordId;

  		// Set Log Level
  		if (logLevelCMD != null) {
   			appLogWrapper.isDebug = logLevelCMD.Debug__c;
   			appLogWrapper.isInfo = logLevelCMD.Info__c;
   			appLogWrapper.isError = logLevelCMD.Error__c;
   			appLogWrapper.isWarning = logLevelCMD.Warning__c;
  		}

  		System.debug('appLogWrapper' + appLogWrapper);

  		return appLogWrapper;
 	}

 	public static List < System_Settings__mdt > getLogSettings(String sysMetadataLabelName) {
  		return [Select Id, is_Trigger__c, Number_Of_Retry__c, Debug__c, Info__c, Warning__c, 
                Error__c From System_Settings__mdt Where MasterLabel = : sysMetadataLabelName limit 1];

 	}
 	/*
 	public static String getQueueIdByName(String queueName) {
  		String queueId='';
  		List<Group> groupList = [select Id from Group where Name = : queueName AND Type = 'Queue'];
  		if(groupList!=null && !groupList.isEmpty()){
      		queueId = groupList[0].Id;
  		}
  		return queueId;
 	}
	*/
}